sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MarshalSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Column.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/expected/com/test/UserModel.java, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqliteGotoDeclarationHandler.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/util/SqliteRenameUtil.kt
Found while NameAllocator-ing.
=> Update naming to reflect historical changes.

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/generating/TableGenerator.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightFileViewProviderFactory.kt
=> Use File.separatorChar

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MarshalSpec.kt, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-boolean/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-enum/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine-as-library/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/expected/com/test/UserModel.java
Fixes [Issue 141](https://github.com/square/sqldelight/issues/141)
=> Add copy constructor to generated Marshal class.

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqlitePluginException.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/TableGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Column.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Table.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/TableGenerator.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/SqlDelightPluginTest.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightFileViewProviderFactory.kt
also let the tablegenerator throw sqlite exceptions which propogate properly
=> Cleanup the column and table classes 

sqldelight-studio-plugin/build.gradle
This includes the functionality which adds the plugin zip to the archive set automatically.
=> Update to the latest IntelliJ plugin.

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/TableGenerator.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/generating/TableGenerator.kt
=> Throw some exceptions if folder structure is set up improperly

sqldelight-gradle-plugin/build.gradle, sqldelight-studio-plugin/build.gradle
Looks like:
```
com.squareup.sqldelight.SqlDelightPluginTest > nullableBoolean PASSED
com.squareup.sqldelight.SqlDelightPluginTest > forbiddenColumnName PASSED
com.squareup.sqldelight.SqlDelightPluginTest > syntaxError PASSED
com.squareup.sqldelight.SqlDelightPluginTest > columnSqlCollision PASSED
com.squareup.sqldelight.SqlDelightPluginTest > duplicateSqlIdentifier PASSED
com.squareup.sqldelight.SqlDelightPluginTest > worksFine PASSED
com.squareup.sqldelight.SqlDelightPluginTest > worksFineAsLibrary PASSED
com.squareup.sqldelight.SqlDelightPluginTest > nullableEnum PASSED
com.squareup.sqldelight.SqlDelightPluginTest > unknownType PASSED
com.squareup.sqldelight.SqlDelightPluginTest > duplicateColumnName PASSED
com.squareup.sqldelight.SqlDelightPluginTest > worksForKotlin SKIPPED …
```
=> Log test lifecycle to console.

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/SymbolTable.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/ErrorListener.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/test/fixtures/duplicate-column-name/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/duplicate-table-name/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/duplicate-table-name/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/duplicate-table-name/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/fixtures/duplicate-table-name/src/main/sqldelight/com/test/Table.sq, sqldelight-gradle-plugin/src/test/fixtures/duplicate-table-name/src/main/sqldelight/com/test/Table2.sq, sqldelight-gradle-plugin/src/test/fixtures/forbidden-column-name/failure.txt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightFileViewProviderFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDocumentAnnotator.kt
Also fixed that bug with the carets whoo. Closes #111
=> Adding in the symbol table

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightFileViewProviderFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqliteGotoDeclarationHandler.kt
=> Fix for windows

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqliteFindUsagesProvider.kt
=> File description is file name

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightCommenter.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
=> Intellij comments stuff

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDocumentAnnotator.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqliteFile.kt
=> Fix the status stuff

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
=> Dont use StringUtils

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/Status.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/SymbolTable.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/util/BiMultiMap.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/ExpressionValidator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-compiler/src/test/kotlin/com.squareup.sqldelight.types/ResolverTests.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/test/fixtures/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/src/main/sqldelight/com/sample/HockeyPlayer.sq, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/SqlDelightStartupActivity.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/SqlDelightVirtualFileListener.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightFileViewProviderFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDocumentAnnotator.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqliteFile.kt
=> Keep track of virtual file dependencies

.gitignore, RELEASING.md, build.gradle, sqldelight-compiler/build.gradle, sqldelight-gradle-plugin/.gitignore, sqldelight-gradle-plugin/build.gradle, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-studio-plugin/build.gradle, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/SqlDelightErrorHandler.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
=> Add error handling

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightStructureViewFactory.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
=> Structure View Provider

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/create-table-column-named-create-table/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/create-table-column-named-create-table/src/main/sqldelight/com/sample/Test.sq
=> Specific message for create table column name

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-boolean/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-enum/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/sql-types-to-java-types/expected/com/test/TypeModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/TeamModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine-as-library/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine/expected/com/test/UserModel.java, sqldelight-runtime/src/main/java/com/squareup/sqldelight/RowMapper.java
=> Create RowMapper interface for use by all mappers.

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
So apparently the plugin hasn't been doing its job for a while. Cool
Closes #221
=> Refresh the model files on sqlite edit.

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-gradle-plugin/src/test/fixtures/invalid-column-type/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/invalid-column-type/src/main/sqldelight/com/sample/Test.sq
=> Enforce the casing of sqlite types

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt, sqldelight-gradle-plugin/src/test/fixtures/outside-columns-in-join/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/outside-columns-in-join/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/subqueries-ambiguous/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/subqueries-ambiguous/src/main/java/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/src/main/sqldelight/com/sample/HockeyPlayer.sq
=> Subqueries inside joins do not have access to tables joined against

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightModuleComponent.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/GradleUtil.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
=> Check that gradle plugin is installed and updated from IDE

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/ResolutionError.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Value.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/ExpressionValidator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFile.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/ColumnNameElementRef.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/SqliteElementRef.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
=> Autocomplete based off of resolver

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/ExpressionValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/expression-like/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/expression-like/src/main/sqldelight/com/sample/Test.sq
=> Subexpressions require their own validation block

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
These logs go nowhere in production but at least when we eventually add proper logging Ill change this
Closes #256
=> Its not guaranteed this will be non-null apparently. 

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt, sqldelight-studio-plugin/build.gradle, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/completion/CompletionTests.kt, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/Alias.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/CommonTable.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/Expression.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/JoinSubquery.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/ResultColumn.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/TableName.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/TableNamePrefixed.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/Test1.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/Test2.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/ViewResultColumn.sq, sqldelight-studio-plugin/testData/completion/src/main/sqldelight/com/sample/ViewResultColumnPrefixed.sq
=> Studio Tests For Autocomplete

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/SymbolTable.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/DeleteValidator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/UpdateValidator.kt
upstream change: https://github.com/bkiers/sqlite-parser/pull/13
=> Remove a common table redundency in the grammar

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt, sqldelight-gradle-plugin/src/test/fixtures/trigger-raise/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/trigger-raise/src/main/sqldelight/com/sample/Test.sq
=> Allow selects which only grab a function

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/InsertValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/insert-default-values/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/insert-default-values/src/main/sqldelight/com/sample/Test.sq
=> Insert default values fix

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightModuleComponent.kt
=> Builds not using sqldelight shouldnt crash the plugin

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFindUsagesHandlerFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFindUsagesProvider.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteGotoDeclarationHandler.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/IdentifierElement.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/SqlDelightElementRef.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/SqliteElement.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/ParseUtil.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/SqliteRenameUtil.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/SqlDelightFixtureTestCase.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/findusages/FindUsagesTests.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/util.kt, sqldelight-studio-plugin/testData/findusages/main/sqldelight/com/sample/AliasedColumn.sq, sqldelight-studio-plugin/testData/findusages/main/sqldelight/com/sample/ColumnName.sq, sqldelight-studio-plugin/testData/findusages/main/sqldelight/com/sample/CommonTable.sq, sqldelight-studio-plugin/testData/findusages/main/sqldelight/com/sample/TableName.sq, sqldelight-studio-plugin/testData/findusages/main/sqldelight/com/sample/ViewName.sq, sqldelight-studio-plugin/testData/main/Test1.sq
(and fix find usages because of course it doesnt work right now)
=> Add tests for find usages 

build.gradle, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/src/main/java/com/test/User.kt, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/src/main/sqldelight/com/test/User.sq
Unfortunately the test still doesn't work when using the `GradleRunner`. Works fine if you build it locally (and add `sqldelight:gradle-plugin:0.3.1` to the classpath) and looks like some weird bug between `GradleRunner`, Android and Kotlin.
=> Kotlin 1.0.2

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightManager.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightModuleComponent.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightStartupActivity.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightVirtualFileListener.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFile.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/SqlDelightElementRef.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/SqlDelightFixtureTestCase.kt
=> Put all module-local objects into a single manager

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightStartupActivity.kt
=> Startup activity should be run on a read thread

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Column.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/test/fixtures/import-collision/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/import-collision/src/main/sqldelight/com/test/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/works-fine/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine/src/main/sqldelight/com/test/User.sq, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/ClassCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteASTFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/ClassNameElementAnnotator.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/ClassNameElementRef.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/ImportElement.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
=> Add imports to the grammar and auto-add when completing

README.md
Fixes unchecked assignment error and a syntax error in AutoValue example implementation
=> Correct unchecked assignment in AutoValue implementation

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/ExpressionValidator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SelectOrValuesValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/function-name-tests/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/function-name-tests/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/update-validation-failures/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/update-validation-failures/src/main/sqldelight/com/sample/Test.sq
Only 2500 lines added jake should be ezmode.
(99% are tests)
=> Validate function names and parameter count

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt
=> Ranges can have multiple errors if they have different messages

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
=> Run the delete from a write action

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFile.kt
=> Catch SQLitePluginException in the onError block

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MarshalSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Column.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/test/fixtures/duplicate-column-name/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/duplicate-column-name/src/main/sqldelight/com/test/IdentifierTable.sq, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/src/main/java/com/sample/Test.java, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/src/main/sqldelight/com/sample/Test.sq, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/completion/CompletionTests.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/reference/ReferenceTests.kt, sqldelight-studio-plugin/testData/main/Test1.sq, sqldelight-studio-plugin/testData/reference/main/sqldelight/com/sample/QuotedIdentifier.sq
=> Use name allocator for everything

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/Status.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/SelectResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/TableResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/QueryResults.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-compiler/src/test/data/ResolverTestData.sq, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/types/ResolverTests.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/types/ValidatorTests.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/util/ParseUtil.kt
=> Translate select statement resolutions into a query type for compiler usage

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MarshalSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Table.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/QueryResults.kt, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/expression-like/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/insert-default-values/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/src/main/java/com/sample/Test.java, sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/sample/Test1Model.java, sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/test/Test2Model.java, sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/thing/Test3Model.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-boolean/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-boolean/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-enum/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-enum/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/sql-types-to-java-types/expected/com/test/TypeModel.java, sqldelight-gradle-plugin/src/test/fixtures/trigger-raise/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/TeamModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine-as-library/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine-as-library/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/src/main/java/com/test/User.kt
I dropped the table name from the marshal because you're going to create them from the factory in the future anyways (they'll also be final).
=> Generate Mapper creators

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/ExpressionValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/function-name-tests/failure.txt
see https://www.sqlite.org/lang_aggfunc.html
=> Group concat takes 1 or 2 args

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/SelectResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/TableResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/SymbolTable.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Value.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/QueryResults.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/types/ValidatorTests.kt, sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test1Model.java, sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test2Model.java, sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/src/main/sqldelight/com/sample/Test1.sq, sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/src/main/sqldelight/com/sample/Test2.sq
=> Generate creator/model interfaces for views included in selects

CHANGELOG.md, README.md, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
Feel free to take over for release, otherwise i can give it a go
=> Documentation for 0.4 release

CHANGELOG.md, sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Column.kt, sqldelight-gradle-plugin/src/test/fixtures/column-casing/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/column-casing/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/works-fine/src/main/sqldelight/com/test/User.sq, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/ClassCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteASTFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/ClassNameElement.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
=> Allow any combo of casing on column names

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/QueryResults.kt
Closes #338 
Is there a way to specify the java version gradle runs on? It would be good to have a java6 test somewhere but I don't know how to make one.
=> Use kotlin functions instead of java8

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/ExpressionValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/function-name-tests/src/main/sqldelight/com/sample/Capitals.sq
=> Allow capitals in function names

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
=> Verify the input file has been parsed already before generating interface

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/QueryResults.kt, sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test2Model.java
This will require a 0.4.3 once its merged
=> Guarantee order of creators on mappers and in factory method parameters

README.md
I was following the examples in the Join Projection section in the README and noticed a few typos.
I've signed the CLA.
=> Minor typos in Join Projection example

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/QueryResults.kt, sqldelight-gradle-plugin/src/test/fixtures/sum-uses-int/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/sum-uses-int/src/main/sqldelight/com/sample/Test.sq
=> Make the return type for sum and round smarter

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/SelectResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Result.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Table.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Value.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/ForeignKey.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SelectOrValuesValidator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SelectStmtValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/expected/com/sample/FolderModel.java, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/expected/com/sample/MessageModel.java, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/src/main/sqldelight/com/sample/Folder.sq, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/src/main/sqldelight/com/sample/Message.sq
=> Bug around inner selects having duplicates of scoped values

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteGotoDeclarationHandler.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/SqliteElement.kt
=> Dont assume that a SqliteElement contains a child Identifier element

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-gradle-plugin/src/test/fixtures/cast-as-text/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/cast-as-text/src/main/sqldelight/com/sample/Test.sq
=> Bug around casting

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-gradle-plugin/src/test/fixtures/use-adapter-from-factory/expected/com/sample/BookModel.java, sqldelight-gradle-plugin/src/test/fixtures/use-adapter-from-factory/src/main/sqldelight/com/sample/Book.sq, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java
=> Use the existing factory adapters for single value selects

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteGotoDeclarationHandler.kt
=> Check if virtual file is null before getting source root

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/QueryResults.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Table.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Value.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/ForeignKey.kt, sqldelight-gradle-plugin/src/test/fixtures/duplicate-result-column-name/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/duplicate-result-column-name/src/main/sqldelight/com/sample/Test.sq
=> Generated names should use the table name if there are duplicates

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/TableResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/ForeignKey.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/CreateTableValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/create-table-validation-failures/failure.txt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFile.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/completion/CompletionTests.kt, sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/ExpressionAnd.sq, sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/ForeignKey.sq, sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/References.sq
=> Autocomplete fixes mainly in create table statements

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/TableResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/ForeignKey.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/CreateTableValidator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/create-table-validation-failures/failure.txt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/CopyAsSqliteAction.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFile.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/completion/CompletionTests.kt, sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/ExpressionAnd.sq, sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/ForeignKey.sq, sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/References.sq
=> Add editor action for copying sqldelight code as sqlite

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-gradle-plugin/src/test/fixtures/sqlite-keyword-java-package/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/sqlite-keyword-java-package/src/main/java/no/test/TestEnum.java, sqldelight-gradle-plugin/src/test/fixtures/sqlite-keyword-java-package/src/main/sqldelight/com/sample/Test.sq
Closes #388 
That was easier than I expected.
=> Allow sqlite keywords in java package names

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-gradle-plugin/src/test/fixtures/javadoc/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/javadoc/src/main/sqldelight/com/sample/Test.sq, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightCommenter.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteASTFactory.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteHighlighter.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/psi/SqlDelightComment.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/PsiUtil.kt
=> Include javadoc on generated strings for sql selects

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDocumentAnnotator.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteFile.kt
Biggest difference this makes is that when you open the IDE the files will be guarded.
=> Guard the generated document on write

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightManager.kt
=> Dont assume we have a SqliteFile for a parse context

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-gradle-plugin/src/test/fixtures/function-nullability/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/function-nullability/src/main/sqldelight/com/sample/Test.sq
=> function nullability fixes

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/QueryResults.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/javadoc/expected/com/sample/TestModel.java
=> Add javadoc to generated factory and mappers

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Column.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/SqliteType.kt, sqldelight-gradle-plugin/src/test/fixtures/sql-types-to-java-types/expected/com/test/TypeModel.java, sqldelight-gradle-plugin/src/test/fixtures/sql-types-to-java-types/src/main/sqldelight/com/test/Type.sq
=> Add Short as a support datatype for INTEGER columns.

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/InsertValidator.kt
=> Fall back to full insert for nulls

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDocumentAnnotator.kt
=> Dont attempt annotation on out-of-folder .sq files

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightVirtualFileListener.kt
=> Check VirtualFile validity before performing operations

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/dots-in-folder/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/dots-in-folder/src/main/sqldelight/com.sample.test/Test.sq
=> If the containing folder has dots in it dont explode into multiple folders

CHANGELOG.md, README.md, gradle.properties, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
Wait for the other one to merge. I'm also wondering why its failing and want to see if its actually that branch or something whack on travis
=> Prepare version 0.4.4

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
=> Ensure the Gradle task is invalidated on version change.

sqldelight-studio-plugin/src/main/java/org/antlr/intellij/adaptor/lexer/AntlrLexerAdapter.java, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/formatter/AbstractLeaf.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/formatter/CreateTableBlock.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/formatter/JavadocBlock.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/formatter/SqlDelightBlock.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/formatter/SqlDelightFormattingModelBuilder.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/formatter/SqlStmtBlock.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/formatter/util/ASTUtil.kt, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/formatting/FormattingTests.kt, sqldelight-studio-plugin/testData/formatting/Formatting_after.sq, sqldelight-studio-plugin/testData/formatting/Formatting_before.sq, sqldelight-studio-plugin/testData/formatting/Formatting_create_table_after.sq, sqldelight-studio-plugin/testData/formatting/Formatting_create_table_before.sq
=> Add some formatting for sqlite files

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/Column.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Value.kt, sqldelight-gradle-plugin/src/test/fixtures/column-annotations/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/column-annotations/src/main/java/com/sample/ClassAnnotation.java, sqldelight-gradle-plugin/src/test/fixtures/column-annotations/src/main/java/com/sample/IntegerAnnotation.java, sqldelight-gradle-plugin/src/test/fixtures/column-annotations/src/main/java/com/sample/MultipleValuesAnnotation.java, sqldelight-gradle-plugin/src/test/fixtures/column-annotations/src/main/java/com/sample/StringArrayAnnotation.java, sqldelight-gradle-plugin/src/test/fixtures/column-annotations/src/main/sqldelight/com/sample/Test.sq
=> Add ability to annotate generated methods

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/UpdateValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/timestamp-literals/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/timestamp-literals/src/main/sqldelight/com/sample/Test.sq
=> Support timestamp literals when setting a column value

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SelectOrValuesValidator.kt
=> Remove an unnecessary complication in the select validator that was causing bugs

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MarshalSpec.kt, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/src/main/sqldelight/com/test/User.sq, sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test1Model.java, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/sample/Test1Model.java, sqldelight-gradle-plugin/src/test/fixtures/nullable-enum/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/sql-types-to-java-types/expected/com/test/TypeModel.java, sqldelight-gradle-plugin/src/test/fixtures/sqlite-keyword-java-package/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-fine/expected/com/test/UserModel.java, sqldelight-runtime/src/main/java/com/squareup/sqldelight/ColumnAdapter.java, sqldelight-runtime/src/main/java/com/squareup/sqldelight/EnumColumnAdapter.java
=> Remove the need to handle nulls in a column adapter.

sqldelight-gradle-plugin/build.gradle, sqldelight-gradle-plugin/src/test/build.gradle, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/BuildFilesRule.kt
=> Ensure fixtures use the same compile and build tools versions.

sqldelight-gradle-plugin/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/src/main/java/com/test/Gender.java, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/src/main/java/com/test/User.kt, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/src/main/sqldelight/com/test/User.sq
Thanks to @alkemist for the tested project classpath guidance.
=> Restore the Kotlin test to working order.

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Value.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Arguments.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/test/fixtures/expression-like/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/expected/com/sample/FolderModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java, sqldelight-gradle-plugin/src/test/integration/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle-plugin/src/test/integration/src/main/sqldelight/com/squareup/sqldelight/integration/Person.sq, sqldelight-runtime/src/main/java/com/squareup/sqldelight/SqlDelightStatement.java, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
Still need to add the methods for non-query statements using `SqliteProgram`s before I can close out #435 
Also going to write a load more tests since theres a lot of weird stateful behaviour going on and the existing tests are pretty horrible examples of bind arg usage
=> Generate methods on the factory for sql statements with contain bind args

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Arguments.kt, sqldelight-gradle-plugin/src/test/fixtures/bind-object/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/bind-object/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/bind-object/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/statement-bind-args/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/statement-bind-args/src/main/java/com/sample/Test.java, sqldelight-gradle-plugin/src/test/fixtures/statement-bind-args/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/expected/com/sample/FolderModel.java
=> Add a method to the factory which accepts a SQLiteProgram for non-queries

sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqliteASTFactory.kt
=> Fix a bug around clicking parameterized types

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/QueryResults.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Value.kt, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/integration/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle-plugin/src/test/integration/src/main/java/com/squareup/sqldelight/integration/DatabaseHelper.java, sqldelight-gradle-plugin/src/test/integration/src/main/java/com/squareup/sqldelight/integration/SqliteKeywords.java, sqldelight-gradle-plugin/src/test/integration/src/main/sqldelight/com/squareup/sqldelight/integration/SqliteKeywords.sq
=> Remove the escapes from the generated string constants since cursor doesnt like them

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
=> Fall back to the raw sqlite text if pretty printing fails

sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4, sqldelight-gradle-plugin/src/test/fixtures/string-array-arg/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/string-array-arg/src/main/java/com/sample/SomeEnum.java, sqldelight-gradle-plugin/src/test/fixtures/string-array-arg/src/main/sqldelight/com/sample/Test.sq
Upstream change: https://github.com/bkiers/sqlite-parser/pull/16
=> Reduce the in precedence so that expressions populate args correctly

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/bind-object/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/keyword_identifiers/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/statement-bind-args/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/expected/com/sample/FolderModel.java, sqldelight-gradle-plugin/src/test/integration/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java
Closes #491 
I'll update the readme PR after merge
=> Make binding statements type safe

CHANGELOG.md, README.md, sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
Lots of changes in the readme so I thought I'd open a PR. Don't merge until everything is tested and we're ready for release.
=> Prepare for version 0.5.0

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/DeleteValidator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/UpdateValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/create-trigger-duplicate-column/expected/com/sample/SimpleTableModel.java, sqldelight-gradle-plugin/src/test/fixtures/create-trigger-duplicate-column/src/main/sqldelight/com/sample/SimpleTable.sq
=> Fix column ambiguity in trigger bodies

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-gradle-plugin/src/test/fixtures/left-join-bind-args/expected/com/sample/TableAModel.java, sqldelight-gradle-plugin/src/test/fixtures/left-join-bind-args/expected/com/sample/TableBModel.java, sqldelight-gradle-plugin/src/test/fixtures/second-arg-requires-factory/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/second-arg-requires-factory/expected/com/sample/TestViewModel.java, sqldelight-gradle-plugin/src/test/fixtures/second-arg-requires-factory/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/second-arg-requires-factory/src/main/sqldelight/com/sample/TestView.sq
=> Fix a bug where a bind arg that doesnt require a factory will signal that no factory is needed for subsequent args

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/Value.kt, sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/thing/Test3Model.java, sqldelight-gradle-plugin/src/test/fixtures/second-arg-requires-factory/expected/com/sample/TestViewModel.java
References #358 
cc @gabrielittner
=> For factories with no table, clean up signatures by moving foreign factories to fields

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/query/QueryResults.kt, sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test2Model.java, sqldelight-gradle-plugin/src/test/fixtures/view-file-no-args/expected/com/sample/SettingsModel.java, sqldelight-gradle-plugin/src/test/fixtures/view-file-no-args/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/view-file-no-args/src/main/sqldelight/com/sample/Settings.sq, sqldelight-gradle-plugin/src/test/fixtures/view-file-no-args/src/main/sqldelight/com/sample/Test.sq
=> Selects on views which have factory dependencies should also get factory fields

README.md
Nested AutoValue classes must be static.
=> Update README - Make nested AutoValue class static

README.md
Hello.  I am attempting to use your fine library.  I noticed some small errors in your README
=> Readme quickfixes

build.gradle, gradle/wrapper/gradle-wrapper.properties
Updated
- Gradle: `3.3` -> `3.4.1`
- Android plugin: `2.2.1` -> `2.3.0`
=> Update Gradle and Android plugin versions

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/TableResolver.kt, sqldelight-gradle-plugin/src/test/fixtures/inner_view_query_using_join/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/inner_view_query_using_join/src/main/sqldelight/com/sample/Test.sq
=> Dont scope in values when resolving a view

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-gradle-plugin/src/test/fixtures/delete-compiled-statement/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/delete-compiled-statement/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/inner_view_query_using_join/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/insert-default-values/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/subselect-in-delete/expected/com/sample/MessageModel.java
=> Generate compiled statements for all mutator statements

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-gradle-plugin/src/test/fixtures/enum-bind-args/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/in-custom-foreign-type/expected/com/sample/TableOneModel.java, sqldelight-gradle-plugin/src/test/fixtures/in-custom-foreign-type/expected/com/sample/TableTwoModel.java, sqldelight-gradle-plugin/src/test/fixtures/in-custom-foreign-type/src/main/sqldelight/com/sample/TableOne.sq, sqldelight-gradle-plugin/src/test/fixtures/in-custom-foreign-type/src/main/sqldelight/com/sample/TableTwo.sq
=> Generify foreign factories for SqlDelightStatements

README.md
Notably string constants aren't generated anymore
=> Update readme to reflect 0.6.1 release

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-gradle-plugin/src/test/fixtures/enum-bind-args/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/inner_view_query_using_join/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/left-join-bind-args/expected/com/sample/TableAModel.java, sqldelight-gradle-plugin/src/test/fixtures/second-arg-requires-factory/expected/com/sample/TestViewModel.java, sqldelight-gradle-plugin/src/test/fixtures/statement-bind-args/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/tables-through-view/expected/com/sample/Test2Model.java, sqldelight-gradle-plugin/src/test/fixtures/unnecessary-current-index/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/unnecessary-current-index/src/main/sqldelight/com/sample/Test.sq, sqldelight-gradle-plugin/src/test/fixtures/update-inner-select/expected/com/sample/FolderModel.java, sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java
=> Fix dead local storage of currentIndex & improve the creation of args in empty cases.

sqldelight-sample/build.gradle, sqldelight-sample/src/main/java/com/example/sqldelight/hockey/ui/PlayersActivity.java, sqldelight-sample/src/main/java/com/example/sqldelight/hockey/ui/TeamsActivity.java
Current sample doesn't work with version 0.6.1. This PR is to fix it.
=> Update sample to version v0.6.1

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/test/data/ResolverTestData.sq, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/types/ResolverTests.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/types/ValidatorTests.kt, sqldelight-gradle-plugin/src/test/fixtures/function-type-tests/expected/com/test/UserModel.java, sqldelight-gradle-plugin/src/test/fixtures/function-type-tests/src/main/java/com/test/User.java, sqldelight-gradle-plugin/src/test/fixtures/function-type-tests/src/main/sqldelight/com/test/User.sq
Attempt at fixing #636 
In addition to the tests, I also checked the fix by modifying a fixture in the `sqldelight-gradle-plugin` tests and looking at the generated code. I didn't find a fixture that generally tests aggregate functions, should I add one?
I also submitted the CLA form.
=> Add AVG column type mapping

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-gradle-plugin/src/test/fixtures/update-bind-args-order/expected/com/sample/TestModel.java, sqldelight-gradle-plugin/src/test/fixtures/update-bind-args-order/src/main/sqldelight/com/sample/Test.sq
=> Fix bind args ordering

sqldelight-compiler/build.gradle, sqldelight-gradle-plugin/build.gradle, sqldelight-jps-plugin/build.gradle, sqldelight-studio-plugin/build.gradle
Still wrapping my head around `api` vs `implementation`, but decided to submit this early. Would love some input on this.
=> Upgrade to Gradle 4.0.2

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/SqlStmt.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/SelectResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/TableResolver.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Arguments.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/ForeignKey.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/SymbolTable.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/util/JavadocUtil.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/CreateTableValidator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/types/ValidatorTests.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/ClassCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightCompletionContributor.kt, sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/PsiUtil.kt, sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/util.kt
* 'x..y-1' can be 'x until y'
* map().filterNotNull() can be mapNotNull()
* filter{}.first() can be first{}
* filter{}.isNotEmpty() can be any{}
=> Multiple operator and iteration optimizations.

sqldelight-core/src/main/grammars/sqldelight.bnf, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/TableInterfaceGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/ViewInterfaceGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightParserDefinition.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/SqliteTypeMixin.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/util/QueryUtil.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/views/InterfaceGeneration.kt, sqldelight-core/src/test/view-interface-fixtures/only-table-type/sqldelight/com/sample/Data.sq, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/PersonAndFriends.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/PersonCool.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/sqldelight/com/sample/Data.sq
Serves as basis for generating interface from query
Also adds a bunch of copyright headers i forgot.
If I can keep this whole thing stateless by completion I'll be sooooo happy
=> Generate interfaces for views.

.travis.yml, sqldelight-gradle-plugin/src/test/fixtures/duplicate-table-name/ignored.txt
cc @jaredsburrows same as your change to the tarvis file plus ignoring the test thats messing things up
=> Fix the cli

.travis.yml, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/ExpressionValidator.kt, sqldelight-gradle-plugin/src/test/fixtures/function-name-tests/failure.txt, sqldelight-gradle-plugin/src/test/fixtures/function-name-tests/src/main/sqldelight/com/sample/Test.sq
=> Fix julianday function name

build.gradle, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/NamedQuery.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/DatabaseTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/QueriesFunctionTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/QueriesPropertyTest.kt, sqldelight-core/src/test/query-interface-fixtures/query-requires-type/com/sample/JoinedWithUsing.kt, sqldelight-core/src/test/table-interface-fixtures/requires-adapter/com/sample/Person.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/com/sample/PersonAndFriends.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/com/sample/PersonCool.kt
Also a bunch of kotlin indentation fixes for kotlinpoot which truthfully should have been their own pr
=> Generate the api exposed for select statements

build.gradle, sqldelight-runtime/build.gradle, sqldelight-runtime/src/test/java/com/squareup/sqldelight/internal/SqliteLiteralsTest.java
We all love it, but it's overkill for this one thing...
=> Remove Okio.

gradle/dependencies.gradle, sqldelight-gradle-plugin/src/test/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/works-fine-as-library/build.gradle, sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/build.gradle, sqldelight-gradle-plugin/src/test/integration/build.gradle, sqldelight-gradle-plugin/src/test/integration/src/main/AndroidManifest.xml, sqldelight-runtime/build.gradle, sqldelight-sample/build.gradle
=> Bump minSdkVersion to 14.

build.gradle, sqldelight-runtime/build.gradle, sqldelight-sample/build.gradle
AFAIK there's no performance gain anymore since the issue causing the slowdown was fixed
=> Remove preDexLibraries flag tweak

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/FactorySpec.kt, sqldelight-gradle-plugin/src/test/fixtures/enum-bind-args/expected/com/sample/ForeignTableModel.java, sqldelight-gradle-plugin/src/test/fixtures/enum-bind-args/src/main/sqldelight/com/sample/ForeignTable.sq
=> Add missing opening paren.

sqldelight-studio-plugin/build.gradle
=> Switch plugin to compile dependencies.

sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Integer primary keys are always non null but can be inserted as null

sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-core-integration-tests/src/test/kotlin/com/squareup/sqldelight/core/integration/IntegrationTest.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueriesTypeGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedMutator.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
Closes https://github.com/square/sqldelight/issues/635
=> Enable collection parameters for mutator queries

sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
Closes https://github.com/square/sqldelight/issues/646
=> If a bind arg is used in multiple places throw out any unknown types

sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt
The driver robolectric uses causes errors if they arent
=> Create views in order of dependencies being fulfilled

runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt, runtime/sqldelight-runtime/src/main/java/com/squareup/sqldelight/db/SqlDatabase.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/MigrationFile.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/MigrationFileType.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt, sqldelight-gradle/android-plugin/src/test/integration/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle/android-plugin/src/test/integration/src/androidTest/java/com/squareup/sqldelight/integration/MigrationTest.java, sqldelight-gradle/android-plugin/src/test/integration/src/main/AndroidManifest.xml, sqldelight-gradle/android-plugin/src/test/integration/src/main/sqldelight/com/squareup/sqldelight/integration/Person.sq, sqldelight-gradle/android-plugin/src/test/integration/src/main/sqldelight/migrations/1.sqm, sqldelight-gradle/plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt, sqldelight-gradle/plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
Closes https://github.com/square/sqldelight/issues/89
=> Generate migration code inside the query wrapper

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFix.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/Intentions.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/PsiUtil.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFixTest.kt
=> Add intention to expand wildcard in select statement into column names

sqldelight-idea-plugin/src/main/resources/intentionDescriptions/ExpandColumnNamesWildcardQuickFix/description.html
=> Add Expand columns quick fix metadata

sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/ExpressionTest.kt
https://www.sqlite.org/lang_aggfunc.html#sumunc
=> Min and Max functions are always nullable

sqldelight-core-integration-tests/src/test/kotlin/com/example/Player.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/SelectNull.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/Team.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryInterfaceGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/TableInterfaceGenerator.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/views/InterfaceGeneration.kt, sqldelight-core/src/test/query-interface-fixtures/query-requires-type/output/com/sample/JoinedWithUsing.kt, sqldelight-core/src/test/table-interface-fixtures/requires-adapter/output/com/sample/Person.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonAndFriends.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonCool.kt, sqldelight-gradle/android-plugin/src/test/integration/src/main/java/com/squareup/sqldelight/integration/MyPerson.java, sqldelight-gradle/android-plugin/src/test/integration/src/main/java/com/squareup/sqldelight/integration/SqliteKeywords.java, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/rename/SqlStmtIdentifierTests.kt, sqldelight-idea-plugin/testData/project/src/main/java/com/example/GeneratesTypeImplJava.java, sqldelight-idea-plugin/testData/project/src/main/java/com/example/MainImplJava.java, sqldelight-idea-plugin/testData/project/src/main/java/com/example/ViewImplJava.java
It doesn't work with JS since the method name
conflicts with the value name. I dont really care
about java/AutoValue anymore so I don't think
they're worth having anyway.
=> Remove the abstract model implementation

runtime/rxjava2-extensions/src/main/kotlin/com/squareup/sqldelight/runtime/rx/QueryObservable.kt
- Extend from AtomicBoolean to merge object overhead.
- Implement Runnable for scheduled work lambda body.
=> Optimize RxJava extension internals.

runtime/sqldelight-runtime/src/main/kotlin/com/squareup/sqldelight/db/SqlDatabase.kt
=> Rename base parameter name to match generated code

gradle/dependencies.gradle, sqldelight-gradle/android-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightAndroidPlugin.kt, sqldelight-gradle/android-plugin/src/test/kotlin/com/squareup/sqldelight/VariantTest.kt
=> Upgrade to agp alpha16

sqldelight-gradle/plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt, sqlite-migrations/src/main/kotlin/com/squareup/sqlite/migrations/DatabaseFilesCollector.kt
Wanna reuse this in migrations plugin stuff
=> Move logic to collect DB snapshots into the migrations module

sqldelight-core-integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt, sqldelight-gradle/android-plugin/src/test/integration/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle/android-plugin/src/test/integration/src/androidTest/java/com/squareup/sqldelight/integration/MigrationTest.java
=> Name the companion object the same as the nested interface it implements

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFix.kt
=> Only enable quick fix in sqldelight files

runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt, runtime/android-driver/src/test/java/com/squareup/sqldelight/android/DriverTest.kt, runtime/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/TestDb.kt, runtime/sqldelight-runtime/jdk/src/test/kotlin/com/squareup/sqldelight/QueryTest.kt, runtime/sqldelight-runtime/src/main/kotlin/com/squareup/sqldelight/db/SqlDatabaseConnection.kt, runtime/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/SqliteJdbcOpenHelper.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/TeamQueries.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Pass the SQL argument count to the runtime

sqldelight-gradle/android-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightAndroidPlugin.kt, sqldelight-gradle/android-plugin/src/test/kotlin-project/build.gradle, sqldelight-gradle/android-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt, sqldelight-gradle/plugin/build.gradle, sqldelight-gradle/plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle/plugin/src/test/android-project/build.gradle, sqldelight-gradle/plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt
=> Throw an exception if the wrong plugin is applied for the project

sqldelight-gradle/android-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt
This one was copy pasta from the Kotlin test.
=> Fix testing name in PluginTest.

runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt
=> make SqlDelightDatabaseHelper.Callback open

gradle/dependencies.gradle, sqldelight-core-integration-tests/src/test/kotlin/com/example/Player.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/Team.kt, sqldelight-core-integration-tests/src/test/kotlin/com/example/TeamQueries.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt, sqldelight-core/src/test/table-interface-fixtures/requires-adapter/output/com/sample/Person.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonAndFriends.kt, sqldelight-core/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonCool.kt
=> KotlinPoet 1.0.0-RC1

sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
=> Do not emit "0 + ..." for argument counts

runtime/sqldelight-runtime/jdk/src/main/kotlin/com/squareup/sqldelight/db/Closeable.kt, runtime/sqldelight-runtime/js/src/main/kotlin/com/squareup/sqldelight/db/Closeable.kt, runtime/sqldelight-runtime/src/main/kotlin/com/squareup/sqldelight/db/Closeable.kt, runtime/sqldelight-runtime/src/main/kotlin/com/squareup/sqldelight/db/SqlDatabase.kt, runtime/sqldelight-runtime/src/main/kotlin/com/squareup/sqldelight/db/SqlResultSet.kt, sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/MigrationTest.java
=> Use the JDK Closeable for the JDK runtime.

runtime/sqldelight-runtime/build.gradle
=> Add empty source and javadoc jar to new MPP runtime

sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
=> Remove migration support from the IDE for 1.0

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
=> Delete the sqldelight build dir before verifying migrations

runtime/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidDatabaseHelper.kt, runtime/android-driver/src/test/java/com/squareup/sqldelight/android/DriverTest.kt, runtime/android-driver/src/test/java/com/squareup/sqldelight/android/TransacterTest.kt, sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/MigrationTest.java
=> Rename the Android driver implementation to match interfaces

sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedMutator.kt, sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt, sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/triggers/TriggerNotificationTest.kt
=> Take into account triggers when computing the queries to notify for a mutation quedry

.travis.yml
Also remove the target specific artifacts since mpp covers them
=> Publish for all artifacts

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidDatabaseHelper.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/squareup/sqldelight/core/integration/IntegrationTest.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt, sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/MigrationTest.java, sqldelight-gradle-plugin/src/test/integration/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt, sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/db/SqlDatabase.kt
This type manages the version, creation, and migration of the schema. 'Helper' was not descriptive of its behavior.
Refs #977
=> Rename 'Helper' to 'Schema'

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidDatabaseHelper.kt, drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/SqliteJdbcOpenHelper.kt, extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/QueryObservableTest.kt, extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/RecordingObserver.kt, extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/TestDb.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/Query.kt, sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/db/SqlCursor.kt, sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/db/SqlPreparedStatement.kt, sqldelight-runtime/src/jvmTest/kotlin/com/squareup/sqldelight/QueryTest.kt
This reflects its mutable beahvior more accurately.
Refs #977
=> Rename ResultSet to Cursor

sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt
Use Kotlin's buildString helper and re-order addition so offset is always on the left of the plus.
=> Clean up createArguments' implementation

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidDatabaseHelper.kt, extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/TestDb.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt, sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/db/SqlPreparedStatement.kt, sqldelight-runtime/src/jvmTest/kotlin/com/squareup/sqldelight/QueryTest.kt
=> Rename EXEC to EXECUTE

sqldelight-gradle-plugin/build.gradle, sqldelight-gradle-plugin/src/main/resources/META-INF/gradle-plugins/com.squareup.sqldelight.properties
```
$ gw :sq-gr-p:clean :sq-gr-p:ass
$ unzip -p sqldelight-gradle-plugin/build/libs/sqldelight-gradle-plugin-1.0.0-SNAPSHOT.jar META-INF/gradle-plugins/com.squareup.sqldelight.properties
implementation-class=com.squareup.sqldelight.gradle.SqlDelightPlugin
```
=> Use the plugin to generate plugin descriptor

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/ExpressionTest.kt
=> Properly infer type for subselects that are part of an insert

build.gradle, drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/DriverTest.kt, drivers/ios-driver/build.gradle, drivers/ios-driver/src/nativeMain/kotlin/com/squareup/sqldelight/drivers/ios/SQLiterHelper.kt, drivers/ios-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/ios/IosDriverTest.kt, drivers/ios-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/ios/IosTransacterTest.kt, gradle/dependencies.gradle, settings.gradle
=> Add an initial implementation of an iOS driver with failing tests

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt
=> When running the generate task, delete the old generated code first

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt
=> Resolve types to the fully matching import

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/errors/SyntaxErrors.kt
=> Give a proper error for misspelled types

.gitignore, sqldelight-gradle-plugin/build.gradle, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/test/integration-android-library/build.gradle, sqldelight-gradle-plugin/src/test/integration-android/build.gradle, sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java, sqldelight-gradle-plugin/src/test/integration-multiplatform/build.gradle, sqldelight-gradle-plugin/src/test/integration-multiplatform/settings.gradle, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/androidMain/kotlin/com/squareup/sqldelight/integration/android.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/commonMain/kotlin/com/squareup/sqldelight/integration/common.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/commonTest/kotlin/com/squareup/sqldelight/integration/IntegrationTests.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/iosMain/kotlin/com/squareup/sqldelight/integration/ios.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/sqldelight/com/squareup/sqldelight/integration/BigTable.sq, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/sqldelight/com/squareup/sqldelight/integration/NullableTypes.sq, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/sqldelight/com/squareup/sqldelight/integration/Person.sq, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/sqldelight/com/squareup/sqldelight/integration/SqliteKeywords.sq, sqldelight-gradle-plugin/src/test/integration/build.gradle, sqldelight-gradle-plugin/src/test/kotlin-mpp/build.gradle, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/IntegrationTest.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt, sqldelight-gradle-plugin/src/test/variants/build.gradle
- JVM/Android test passes.
- iOS test runs and fails. Will correct in a followup.
=> Integration test for kotlin multiplatform

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/commonTest/kotlin/com/squareup/sqldelight/integration/IntegrationTests.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/sqldelight/com/squareup/sqldelight/integration/lowerCase.sq
=> Handle lowercase .sq file names

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/commonTest/kotlin/com/squareup/sqldelight/integration/IntegrationTests.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/sqldelight/com/squareup/sqldelight/integration/NullableTypes.sq
=> Handle null equality in queries

sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/squareup/sqldelight/core/integration/IntegrationTest.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/ExecuteQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueriesTypeGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedExecute.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedMutator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt
=> Support running any labeled statement at runtime

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
=> Keep bind arg ordering consistent between sql and generated code

sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt
=> Make QueryWrapper also extend Transacter

sqldelight-compiler/integration-tests/src/test/kotlin/com/example/QueryWrapper.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/squareup/sqldelight/core/integration/IntegrationTest.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt
=> Sort the table adapters in query wrappers

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidDatabaseHelper.kt
=> Allow customizing cacheSize with SupportSQLiteOpenHelper constructor

sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
=> Dont factor the array parameter into the max index

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/BindableQueryTest.kt
=> Use type for resulting function when inferring argument type

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/FailureTest.kt, sqldelight-gradle-plugin/src/test/no-package/build.gradle, sqldelight-gradle-plugin/src/test/no-package/src/main/sqldelight/NoPackage.sq
=> Fail compilation when an sq file has no package

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/JavaTypeMixin.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/FileIndex.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/annotations/ClassNameAnnotatorTest.kt, sqldelight-idea-plugin/testData/project/src/main/sqldelight/com/example/Main.sq
=> Default to current package when resolving non-primitive types

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/test/integration-multiplatform/ios-build.gradle
One less weird oddity to forget during setup
=> Link sqlite3 for native builds with the plugin

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Properly get type for REAL and infer type for binary statements

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
Closes #1237 
This might be fixed when as tracks intellij 2019. Will check that later
=> Still need to call registerJavaGeneratingTask to Android Studio picksup the source set

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightErrorHandler.kt
https://youtrack.jetbrains.com/issue/IJSDK-576
=> Include the actual stacktrace in reported errors

README.md
See my mistake in #1275 because I forgot to enable it.
=> Add emphasis on required gradle metadata feature

drivers/ios-driver/build.gradle, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
=> If there is a common target, it needs to be the only one with a registered source directory

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/CopyAsSqliteAction.kt
=> Fallback to the psielement when copying as sqlite

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt, sqldelight-gradle-plugin/src/test/kotlin-mpp/build.gradle, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt
=> Also make sure any link tasks run the sqldelight task

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
=> If were substituting null in make sure there are spaces are IS

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightHighlighter.kt
=> Fix integer highlighting in IDE plugin

sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PropertiesFileTest.kt
okay FINALLY i think this shit works jesus
=> Ensure that we configure the sqldelight tasks after the android plugin has setup variants if the android plugin was applied

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidSqliteDriver.kt
=> Close the database if one was supplied

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
This allows separate modules to run their generateXInterface task at the same time using gradle's `--parallel` flag.
Closes #1380 and #1266
verified doing a clean build with cash which normally fails in parallel. The failure was racy so hard to know if this definitely fixes but seems like it
=> Synchronize creation of the sqldelight environment

sqldelight-gradle-plugin/build.gradle, sqldelight-runtime/build.gradle
This will choose all available targets for the host platform.
Refs #1431
=> Use built-in aggregate tasks for publishing

drivers/ios-driver/build.gradle, gradle.properties, gradle/dependencies.gradle, sqldelight-gradle-plugin/src/test/integration-multiplatform/android-build.gradle, sqldelight-gradle-plugin/src/test/integration-multiplatform/ios-build.gradle, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/FileIndex.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightRenameProcessor.kt, sqldelight-runtime/build.gradle
=> Update to Kotlin 1.3.50

.travis.yml, drivers/ios-driver/build.gradle, gradle.properties, gradle/dependencies.gradle, sample/common/build.gradle, sqldelight-gradle-plugin/src/test/integration-multiplatform/ios-build.gradle
Update dependency versions and minor fix for cli tests
=> Update build for Kotlin 1.3.60 and native test cli args

README.md
Adding `transaction` sample usage into readme.
=> Adding transaction description into readme

drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcSqliteDriver.kt
JdbcSqlliteDriver - fixed memory-leak, where bound parameters were not released by GC because the (org.sqlite.jdbc*) PreparedStatement was not closed properly.
This caused a severy memory leak where all stored BLOBs where never released and kept occupying the heap forever
See org.sqlite.core.CoreStatement.internalClose. It calls conn.getDatabase().finalize(this) -> org.sqlite.core.DB  which removes the Instance out of  the HashMap  org.sqlite.core.DB.stmts (DB.java:277)
=> sqlite-driver (JVM) - fixed memory-leak

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/ExpressionTest.kt
Right now this is just a failing unit test to demonstrate the issue
=> Return type of sum() should be nullable

gradle/wrapper/gradle-wrapper.properties, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
=> Convert GenerateSchemaTask to use Gradle worker

extensions/android-paging/src/main/java/com/squareup/sqldelight/android/paging/QueryDataSourceFactory.kt, extensions/android-paging/src/test/java/com/squareup/sqldelight/android/paging/QueryDataSourceFactoryTest.kt
=> Pass Transacter into QueryDataSourceFactory to avoid race conditions

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/MigrationTest.kt, sqlite-migrations/src/main/kotlin/com/squareup/sqlite/migrations/ObjectDifferDatabaseComparator.kt
=> Change validator logs in Gradle to debug level

.github/workflows/PR.yml
One which runs mac tests
One which runs windows tests
One which runs android emulator tests (on mac)
=> Split CI into three parts

.github/workflows/PR.yml
Also try caching the intellij dep
=> Consolidate to a single matrix job

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidSqliteDriver.kt, drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AndroidDriverTest.kt, drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AssertableSupportSQLiteOpenHelperFactory.kt, gradle/dependencies.gradle
Addresses #1500 
If it is desired to wait for stable version of library I will pause it.
=> usenobackupdirectory support for android driver

.github/workflows/Publish-Website.yml, .github/workflows/prepare_mkdocs.sh
this shit is actually so god damn cool
=> Add action for deploying mkdocs to gh-pages

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightPropertiesFile.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/FileIndex.kt
Fixes #1594 
Glad I had a debugger for this, would've been a nightmare to track down just examining the code 😰
=> Fix path separator handling which broke Goto and Find Usages on Windows

README.md, docs/index.md
=> Sync README.md and index.md

gradle/gradle-mvn-push.gradle
=> Fix the publish script

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueriesTypeGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Support lambdas of any length

build.gradle, extensions/rxjava3-extensions/src/main/kotlin/com/squareup/sqldelight/runtime/rx3/RxJavaExtensions.kt, extensions/rxjava3-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx3/ObservingTest.kt, extensions/rxjava3-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx3/QueryTest.kt, extensions/rxjava3-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx3/TestDb.kt, gradle/dependencies.gradle, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/sqlTypeName.kt
Closes #1675.
I'll update the sql-psi dependency once the release containing https://github.com/AlecStrong/sql-psi/pull/58 is published.
=> Support remaining integer types in MySQL

.github/workflows/PR.yml, sqldelight-gradle-plugin/src/test/integration-mysql/build.gradle, sqldelight-gradle-plugin/src/test/integration-mysql/src/test/kotlin/com/squareup/sqldelight/mysql/integration/MySqlTest.kt
Per Jake Wharton's suggestion in https://github.com/cashapp/sqldelight/pull/1681#issuecomment-629862715, but with regards to MySQL.
=> Use MySQL Testcontainers

.github/workflows/PR.yml, build.gradle, gradle/dependencies.gradle, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/sqlTypeName.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/test/integration-postgresql/build.gradle, sqldelight-gradle-plugin/src/test/integration-postgresql/settings.gradle, sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/com/squareup/sqldelight/postgresql/integration/Dog.sq, sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/com/squareup/sqldelight/postgresql/integration/PostgreSqlTest.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/IntegrationTest.kt
https://github.com/cashapp/sqldelight/issues/1009
~I'll update the sql-psi dependency once the release containing https://github.com/AlecStrong/sql-psi/pull/60 is published.~
=> Support PostgreSQL dialect

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightRefactoringSupportProvider.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
=> [WIP] Support in-place rename

runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/JavadocTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/triggers/TriggerNotificationTest.kt, sqldelight-gradle-plugin/src/test/integration-mysql/src/main/sqldelight/com/squareup/sqldelight/mysql/integration/Dog.sq
I still want to go back and clean up the `QueryGenerator` a bit, this is just from my first pass through. But I wanted to get some early feedback on the approach to make sure I didn't accidentally break tests to get them to go green.
=> Support array parameters for all dialects

drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt
=> Expose a JdbcDriver constructor off of javax.sql.DataSource

sqldelight-gradle-plugin/src/test/integration/src/main/sqldelight/com/squareup/sqldelight/integration/Varargs.sq, sqldelight-gradle-plugin/src/test/integration/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt
=> Add a test which exercises varargs on the sqlite jdbc driver

drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt
=> Use the jdbc transaction APIs instead of sqlite

sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
=> Add a test to verify that group concat properly inherits nullability from a join

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/GenerateSchemaTest.kt
=> If the output db file already exists when generating a schema, delete it

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightFileIndex.kt
otherwise we cause regressions
=> Allow digits in package names

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFileIconProvider.kt
Addresses https://github.com/cashapp/sqldelight/pull/1727#discussion_r434178265.
=> Add support for dialect icons for migration files

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
Still WIP, need to clean up some of this, and make sure it works for the `MutatorQueryGenerator` as well.
=> Use nullable parameters if bindArg is used in IS NULL

gradle/dependencies.gradle, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedMutator.kt
=> Update the sql-psi dependency

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightProjectComponent.kt
=> Remove modules from the file index when a project is closed

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/util/TreeUtilTest.kt
=> FTS 5 Support

sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
I've forgotten to add this with my previous PR, so added it here, just to show this up in case people want to customize the template here:
=> Add migration template to idea-plugin

drivers/native-driver/src/nativeMain/kotlin/com/squareup/sqldelight/drivers/native/NativeSqlDatabase.kt, extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/QueryTest.kt, extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/RecordingObserver.kt, extensions/rxjava3-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx3/QueryTest.kt, extensions/rxjava3-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx3/RecordingObserver.kt, runtime/src/commonMain/kotlin/com/squareup/sqldelight/Query.kt, runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/SelectStmtUtil.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateMigrationOutputTask.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightExtension.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightClassCompletionContributor.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightStructureViewFactory.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/GeneratedVirtualFile.kt, test-util/src/main/kotlin/com/squareup/sqldelight/test/util/FixtureCompiler.kt
A little bit of a spring clean 🧹 ✨
=> Spring Clean

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightFileIndex.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/MigrationFile.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightQueriesFile.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateMigrationOutputTask.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/FileIndex.kt
=> Fix virtualFile references to always be the original file

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/DatabaseGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt
=> Sort the adapter columns

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/DatabaseGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/integration/TableIntegration.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
I copied the existing test and changed the create table to create virtual table using fts5. It should be able to handle kotlin types but it's no bueno
=> fts5 w/ column types fail

docs/common/coroutines-multiplatform.md, docs/common/coroutines.md
=> Point to the correct coroutines extension artifacts

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
=> Enable inserting a value for synthesized columns

docs/android_sqlite/grouping_statements.md, docs/common/grouping_statements.md, docs/jvm_h2/grouping_statements.md, docs/jvm_mysql/grouping_statements.md, docs/jvm_postgresql/grouping_statements.md, docs/jvm_sqlite/grouping_statements.md, docs/multiplatform_sqlite/grouping_statements.md, docs/native_sqlite/grouping_statements.md, mkdocs.yml, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/ExecuteQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedExecute.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightQueriesFile.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ClojureStmtListMixin.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/StmtIdentifierMixin.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/sqldelight.bnf, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
Closes #809. Closes #1368. Closes #1651.
=> Support grouping multiple statements together in .sq files

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/TableInterfaceGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/integration/JavadocIntegration.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/JavadocTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-compiler/src/test/table-interface-fixtures/requires-adapter/com/sample/Data.sq, sqldelight-compiler/src/test/table-interface-fixtures/requires-adapter/output/com/sample/Person.kt
Closes #1224
requires a sql-psi update
=> Support javadoc on create table statements

docs/common/gradle-dependencies.md, docs/common/gradle-multiplatform.md, docs/common/gradle.md, docs/common/gradle_server.md
=> Include documentation for sqldelight dependencies

docs/android_sqlite/testing.md
The version is currently hardcoded to `1.2.0`
=> Inject latest version in testing.md

docs/index.md
=> Update docs/index.md with latest changes from README

drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/TransacterTest.kt
It's becoming a bit tiresome seeing the same simple-to-fix compiler warnings 😅
=> Remove unnecessary non-null assertion

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
Fixes #1586
Anyone has ideas how to make it incremental without needing to copy each input / output for every given task it runs on?
=> Add verifySqlDelightMigration Gradle task.

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidSqliteDriver.kt
=> Rename parameter names to match supertype names.

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
=> Add generateSqlDelightInterface Gradle task.

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
=> Properly retrieve the commonMain source set

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightFileIndexImpl.kt
=> Default to false for schema derivation

.github/workflows/PR.yml
It's failing right now but leaving this PR up as a reminder to re run the task later to see when its resolved
=> Re-enable plugin verifier action

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/BindArgsTest.kt
Closes #1809
This was me hacking away at the problem and finding the first thing that worked, so not sure if this is the best or even technically correct solution.
=> Fix upsert statement compiler error

gradle/dependencies.gradle, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/PropertiesImpl.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightPropertiesFile.kt, sqldelight-compiler/src/main/kotlin/timber/log/Timber.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/CompilationUnitTests.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TemporaryFixture.kt, sqldelight-idea-plugin/build.gradle, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/LoggerTree.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/ProjectService.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FetchProjectModelsBuildAction.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FileIndexMap.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightFixtureTestCase.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightProjectTestCase.kt, test-util/src/main/kotlin/com/squareup/sqldelight/test/util/TestEnvironment.kt
=> Fix daemon bloat and UI thread stalling for IDE plugin

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueriesTypeGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/integration/TableIntegration.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/MigrationFile.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightQueriesFile.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/CreateTableUtil.kt
=> Handle null module scenario

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFileIndexImpl.kt
=> In unconfigured sq files return empty string for the package name

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedExecute.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-gradle-plugin/src/test/integration/src/main/sqldelight/com/squareup/sqldelight/integration/GroupedStatement.sq, sqldelight-gradle-plugin/src/test/integration/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt
=> Fix grouped statements and add an integration test for them

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFindUsagesHandlerFactory.kt
=> Use built in ModuleUtil to find the module for an element

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/MigrationParserDefinition.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/ParserUtil.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightParserDefinition.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/errors/SyntaxErrors.kt
=> Have a better error message for unknown functions

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
Closes https://github.com/AlecStrong/sql-psi/issues/161
=> Expose string as the type for the second parameter of instr

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
Issue #1947 
I checked on a project using it and it worked after the fix.
=> Fix configuration caching. 

drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt, drivers/sqljs-driver/src/main/kotlin/com/squareup/sqldelight/drivers/sqljs/JsSqlDriver.kt, runtime/src/commonMain/kotlin/com/squareup/sqldelight/db/SqlPreparedStatement.kt, runtime/src/commonMain/kotlin/com/squareup/sqldelight/logs/LogSqliteDriver.kt
I assume that the fact that `./gradlew iosX64Test` runs successfully indicates that https://github.com/JetBrains/kotlin-native/issues/2371 has correctly been resolved.
=> Rename bind* parameters to be equal to the types

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/ExpressionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
Fixes #1946 
I felt this approach was better than a `@Suppress` but that would work as well.
=> Fix name shadowing introduced in #1926

.github/workflows/PR.yml
This will test both IJ Community, and IJ Ultimate - other IDEs can also be tested if desired, see here for docs: https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action#ide-versions
=> Update GitHub Action to test both IC & IU

.github/workflows/sql-psi-dev.yml
Closes #1963  Not sure how to test this, I guess we'll just wait and see :D
=> If the sql-psi-dev cannot be rebased on master, open a PR

CONTRIBUTING.md
=> Start some contributing documentation

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt
For example, when the dialect used is PostgreSQL, the function `sqlite_version()` is not flagged in the editor as "Unknown function sqlite_version" as would naturally be expected.
I haven't combed through and categorised _all_ the "common" functions into the respective dialects (for example, `ifnull` is supported by SQLite, MySQL, and HSQLDB, but not PostgreSQL). I've only categorised the ones only defined by SQLite.
=> Flag SQLite specific functions as unknown in non-SQLite dialects

extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/QueryAsFlowTest.kt
This is easier than messing with zip which is not working for reasons that I cannot figure out.
Closes #1903
=> Test multiple collection with multiple coroutines

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt
https://www.postgresql.org/docs/9.1/functions-string.html
=> [PostgreSQL] Support substring function

extensions/coroutines-extensions/build.gradle, gradle/dependencies.gradle
=> Fix IR backend for coroutines-extensions

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/sqlTypeName.kt, sqldelight-gradle-plugin/src/test/kotlin-mpp/src/commonMain/sqldelight/com/sample/Test.sq
Counterpart to https://github.com/AlecStrong/sql-psi/pull/190.
=> Remove duplication of the raw textual representation of all SQLite data types

gradle/dependencies.gradle, sqldelight-gradle-plugin/build.gradle
Since we're compile only we can do whatever we want
=> Remove no more usefull old Android deps

drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidSqliteDriver.kt, drivers/native-driver/src/nativeMain/kotlin/com/squareup/sqldelight/drivers/native/SqliterPreparedStatement.kt, drivers/sqljs-driver/src/main/kotlin/com/squareup/sqldelight/drivers/sqljs/JsSqlDriver.kt
Removes some compiler warnings
=> Rename parameter names to match supertype names

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/integration/JavadocIntegration.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
=> Dont use function references because gradle doesnt like it, and remove the synchronized

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
=> Inherit nullability of underlying type when casting

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt
Closes https://github.com/cashapp/sqldelight/issues/1958
=> Throw a better error message when encountering an unknown expression

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/file/SqlDelightCreateFileAction.kt
=> If theres nowhere to move the cursor, do nothing instead of crashing

drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcSqliteDriver.kt, sqldelight-gradle-plugin/src/test/integration/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/IntegrationTest.kt, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/build.gradle, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/settings.gradle, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/src/main/kotlin/com/example/db/DbHelper.kt, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/src/main/kotlin/com/example/db/utils.kt, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/src/main/sqldelight/tables/TableA.sq, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/src/main/sqldelight/tables/TableB.sq, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/src/main/sqldelight/tables/TableC.sq, sqldelight-gradle-plugin/src/test/multithreaded-sqlite/src/test/kotlin/MultithreadedTest.kt
Closes #1832 
Thank you for the detailed sample repo @melnikovdv
=> Support multithreaded sqlite transactions

sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateMigrationOutputTask.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
=> Use the worker api for all gradle tasks with classLoaderIsolation

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt, sqldelight-gradle-plugin/src/test/no-sqldelight/build.gradle
=> Provide a warning when the sqldelight plugin is applied but no databases are configured

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/ProjectService.kt
=> Trigger a codegen step when the package name changes

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
=> Correctly infer types for conditions of case statements

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
Fix issue: #2062.
Waits for the generation of code to prevent a race condition with kapt.
=> Fix issue: #2062.

gradle/dependencies.gradle
I was facing an obscure Robolectric error when running the tests locally, but all's good after upgrading the Robolectric version.
=> Upgrade Robolectric version to 4.4

gradle/dependencies.gradle
This updates the bundled SQLite to 3.34 as well.
=> Update sqlite-jdbc to latest

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FileIndexMap.kt
Closes #2192 
Closes #2185
Closes #2183
Closes #2182
Closes #2178
Closes #2169
Closes #2161
Closes #2153
Closes #2152
Closes #2148
Closes #2146
Closes #2145
Closes #2138
Closes #2134
Closes #2133
Closes #2127
Closes #2124
Closes #2120
Closes #2111
Closes #2108
Closes #2107
Closes #2106
Closes #2104
Closes #2103
Closes #2102
Closes #2088
Closes #2072
Closes #2043
=> Ignore gradle errors instead of crashing in the IDE.

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/ProjectService.kt
=> If a sqldelight file is moved to a non-sqldelight module, do not attempt codegen

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
=> Ignore codegen errors in IDE

gradle/dependencies.gradle
[Release notes](https://developer.android.com/studio/releases/gradle-plugin#4-1-0)
=> Upgrade Android Gradle Plugin

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/FileIndex.kt
=> Ensure that we dont try to negatively substring

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FileIndexMap.kt
=> Also ensure project is not disposed before running gradle action

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/ExpressionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Arithmetic on nullable types should also be nullable

docs/index.md
=> Add link to js docs on main index

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFix.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFixTest.kt
=> Make 'expand * intention' work with additional projections

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedQueryInspection.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
https://user-images.githubusercontent.com/14963604/114457814-25459580-9be7-11eb-8ef5-3dbbaeefba2c.mov
@AlecStrong it kind of works but only when you change an sq file. do you have any ideas how we can fix this?
=> Add unused query inspection

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt
=> If kotlin resolution fails during GoTo, dont attempt to go to sqldelight files

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FileIndexMap.kt
=> If IntelliJ encounters an exception while sqldelight is indexing, dont crash

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
=> Handle exceptions that happen while detecting errors before codegen in the IDE

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
=> Also write the database if there are only migration files

drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt, drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcSqliteDriver.kt
=> Use multiple connections for threads in the SqliteDriver unless we are in memory

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Dont generate mapper lambda with type annotations

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
=> Prefer using queries files so that we also generate implementations if there are any

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedColumnInspection.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedQueryInspection.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/inspections/SafeDeleteColumnQuickFixTest.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/inspections/SafeDeleteQueryQuickFixTest.kt
=> Add unused column inspection

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightCopyPasteProcessor.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
https://user-images.githubusercontent.com/14963604/115355558-73e4c800-a1c3-11eb-84de-d9de3f0ca1c4.mov
closes #684
=> Automatically bring imports on copy/paste

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/GradleCompatibility.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightPropertiesFile.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/PropertiesImpl.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TemporaryFixture.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TestUtil.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FileIndexMap.kt
=> Pop a balloon when there are incompatibilities between gradle/intellij plugin versions

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/TypedColumn.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/MismatchJoinColumnInspection.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/inspections/MismatchJoinColumnInspectionTest.kt, sqldelight-idea-plugin/testData/join-inspections/expected.xml, sqldelight-idea-plugin/testData/join-inspections/src/DifferentTypes.sq, sqldelight-idea-plugin/testData/join-inspections/src/SameColumn.sq
=> Add inspection on improper join constraints

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Support sql-psi version which smart casts non-null

sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/player/SelectStuff.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/team/SelectStuff.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/squareup/sqldelight/core/integration/IntegrationTest.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt
=> If custom queries would clash, use the file name as an additional package suffix

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/test/diamond-dependency/app/build.gradle, sqldelight-gradle-plugin/src/test/diamond-dependency/app/src/main/sqldelight/com/example/App.sq, sqldelight-gradle-plugin/src/test/diamond-dependency/bottom/build.gradle, sqldelight-gradle-plugin/src/test/diamond-dependency/bottom/src/main/sqldelight/com/example/BottomTest.sq, sqldelight-gradle-plugin/src/test/diamond-dependency/build.gradle, sqldelight-gradle-plugin/src/test/diamond-dependency/middleA/build.gradle, sqldelight-gradle-plugin/src/test/diamond-dependency/middleA/src/main/sqldelight/com/example/MiddleATest.sq, sqldelight-gradle-plugin/src/test/diamond-dependency/middleB/build.gradle, sqldelight-gradle-plugin/src/test/diamond-dependency/middleB/src/main/sqldelight/com/example/MiddleBTest.sq, sqldelight-gradle-plugin/src/test/diamond-dependency/settings.gradle, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/MultiModuleTests.kt
=> Ensure diamond dependencies only get picked up once in the final compilation unit

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/triggers/TriggerNotificationTest.kt
=> Ensure foreign key cascades cause query listeners to be notified

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightParameterInfoHandler.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
https://user-images.githubusercontent.com/14963604/115724131-56615b00-a389-11eb-9660-a3558cbe6945.mov
closes #506
=> Insert Into ... VALUES(?) parameter hints

gradle/dependencies.gradle, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/android/PackageName.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/properties/PropertiesFileTest.kt, sqldelight-gradle-plugin/src/test/properties-file-android/build.gradle, sqldelight-gradle-plugin/src/test/properties-file-android/src/main/AndroidManifest.xml
=> Pick a minimum sqlite version based on minsdk

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> If unioning two of the same type, return the table type

sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Add test for type inference on booleans

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Ensure params to ifnull and coalesce can be nullable

drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt
=> Ensure that we close connections on exception

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedImportInspection.kt, sqldelight-idea-plugin/testData/inspections/expected.xml, sqldelight-idea-plugin/testData/inspections/src/CreateTable.sq
=> Fix unused import false positives on parameterized types and annotations

sqldelight-idea-plugin/build.gradle, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightInlayParameterHintsProvider.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightInlayParameterHintsProviderTest.kt
=> Inline parameter hints

build.gradle, gradle/dependencies.gradle, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/mysql/MySqlExprType.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt, sqldelight-idea-plugin/build.gradle, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightInlayParameterHintsProvider.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightInlayParameterHintsProviderTest.kt
=> Correctly use query-imposed nullability for expressions

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightParameterInfoHandler.kt
=> Add parameter types and annotations

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateSelectAllQueryAction.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/main/resources/liveTemplates/SqlDelight.xml
https://user-images.githubusercontent.com/14963604/116006257-101f2c80-a613-11eb-848d-208c12ea244f.mov
=> Add action to generate 'select all' query

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedImportInspection.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightImportOptimizer.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightImportOptimizerTest.kt
=> Fix import optimizer

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/BaseGenerateAction.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateActionUtil.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateSelectByPrimaryKeyQueryAction.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/main/resources/liveTemplates/SqlDelight.xml
also edited the 'selw' template
https://user-images.githubusercontent.com/14963604/116129306-a1a1a380-a6d2-11eb-84bc-623cceecb04d.mov
=> Add action to generate 'select by primary key' query

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateInsertIntoQueryAction.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/macro/DbColumnsMacro.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/main/resources/liveTemplates/SqlDelight.xml
https://user-images.githubusercontent.com/14963604/116253353-15968700-a779-11eb-8ab0-d4c997b13ebe.mov
=> Add action to generate 'insert into' query

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightColorSettingsPage.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightHighlightVisitor.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightHighlighter.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
=> Add highlighting for column names, stmt identifiers, function names

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightCopyPasteProcessor.kt
=> Fix npe in CopyPasteProcessor

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightInlayParameterHintsProvider.kt
Seems like a [broken index](https://stackoverflow.com/questions/50253826/stub-index-points-to-a-file-without-psi-com-intellij-openapi-filetypes-unknownf) in ide cc: @YiffyToys
closes #2359
=> Fix crash in InlayParameterHintsProvider

gradle/dependencies.gradle
We should be able to release this extension, now 🥳
=> Bump Paging3 version to 3.0.0 stable

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/IntroduceTableAliasIntention.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/intentions/TableAliasIntentionTest.kt
https://user-images.githubusercontent.com/14963604/117812828-f6b0ee00-b26a-11eb-924a-3bf5bfbbf597.mov
This one is inspired by sql plugin in idea ultimate :)
=> Table alias intention action

drivers/driver-test/build.gradle, drivers/native-driver/build.gradle, extensions/coroutines-extensions/build.gradle, gradle/dependencies.gradle, runtime/build.gradle
=> Add watchosX64 support, bump stately

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/IntroduceTableAliasIntention.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/QualifyColumnNameIntention.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightInlayParameterHintsProviderTest.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/intentions/QualifyColumnNameIntentionTest.kt, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/intentions/TableAliasIntentionTest.kt
https://user-images.githubusercontent.com/14963604/118402791-2e0d0980-b674-11eb-9336-09855d418e54.mov
=> Qualify column name intention

sqldelight-gradle-plugin/src/test/integration-android-variants/src/testDebug/java/com/squareup/sqldelight/integration/DebugIntegrationTests.kt, sqldelight-gradle-plugin/src/test/integration-android-variants/src/testRelease/java/com/squareup/sqldelight/integration/ReleaseIntegrationTests.kt
Otherwise they are not actually run at all, not even compiled.
test folders should be named `testVariant`, not `variantTest`
=> Renaming android test folder to correct name

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFindUsagesHandlerFactory.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightRenameProcessor.kt
https://user-images.githubusercontent.com/14963604/119821879-bb195380-befb-11eb-90d1-77d041d537de.mov
closes #2361
=> Go to declaration for kotlin property

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/RedundantNullCheckInspection.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/inspections/RedundantNullCheckInspectionTest.kt, sqldelight-idea-plugin/testData/not-null-check/expected.xml, sqldelight-idea-plugin/testData/not-null-check/src/NotNull.sq
=> Add inspection for redundant not null check

drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcSqliteDriver.kt
=> Call close() on connection before clearing the ThreadLocal

sqldelight-idea-plugin/src/main/resources/intentionDescriptions/IntroduceTableAliasIntention/description.html, sqldelight-idea-plugin/src/main/resources/intentionDescriptions/QualifyColumnNameIntention/description.html
=> Adds descriptions to intention actions

gradle/dependencies.gradle
[ktlint 0.41.0 CHANGELOG](https://github.com/pinterest/ktlint/blob/master/CHANGELOG.md#0410---2021-03-16)
[Spotless 5.14.2 CHANGELOG](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md#5142---2021-07-20)
=> Upgrade Spotless and ktlint

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnTypeMixin.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/errors/SyntaxErrors.kt
=> Clarify the error for the lowercase 'as' in column type

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFindUsagesProvider.kt
=> Log unexpected types in SqlDelightFindUsagesProvider

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightCopyPasteProcessor.kt
=> Catch ClassCastException in CopyPasteProcessor

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
=> Mangle kotlin keywords in arguments inside insert stmt

build.gradle, docs/android_sqlite/index.md, docs/common/index_gradle_database_pre_dialect.md
Follow up to https://github.com/cashapp/sqldelight/pull/2422#issuecomment-852210799.
=> Remove unnecessary IntelliJ Platform Artifacts Repositories urls

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFoldingBuilder.kt
=> Fix npe in SqlDelightFoldingBuilder

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/MixedNamedAndPositionalParamsInspection.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/main/resources/inspectionDescriptions/MixedNamedAndPositionalParams.html, sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/inspections/MixedNamedAndPositionalParamsInspectionTest.kt, sqldelight-idea-plugin/testData/mixed-named-positional-parameters/expected.xml, sqldelight-idea-plugin/testData/mixed-named-positional-parameters/src/Test.sq
=> Mixed named and positional parameters inspection

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/TaskDependenciesTest.kt, sqldelight-gradle-plugin/src/test/task-dependencies/build.gradle.kts, sqldelight-gradle-plugin/src/test/task-dependencies/src/main/sqldelight/example/Test1.sq
Attempt at fixing https://github.com/cashapp/sqldelight/issues/2119
=> Propagate generateDatabaseInterface task dependency to potential consumers

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/suppression/SqlDelightInspectionSuppressor.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/suppression/SqlDelightSuppressInspectionQuickFix.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
https://user-images.githubusercontent.com/14963604/128679241-336e63d4-dc75-4c2b-a8ef-34bc2fab4f03.mov
=> Add inspection suppressor

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt
=> Fix npe in SqlDelightGotoDeclarationHandler

sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
Fixes #1875 
Based on this PR to fix the same issue in one of Gradle's built-in task types: https://github.com/gradle/gradle/pull/16749
=> Make VerifyMigrationTask support Gradle's up-to-date checks

gradle/dependencies.gradle, sqldelight-compiler/build.gradle, sqldelight-compiler/integration-tests/build.gradle, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/DatabaseGenerator.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt, test-util/src/main/kotlin/com/squareup/sqldelight/test/util/FixtureCompiler.kt
=> Topologically sort table creation statemenets

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFindUsagesHandlerFactory.kt
=> Properly handle nulls for find usages

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt
=> Remove unnecessary nonnull cast

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFindUsagesHandlerFactory.kt
=> Wrap PsiElement.generatedVirtualFiles into read action

sqldelight-idea-plugin/src/main/resources/inspectionDescriptions/UnusedColumn.html
=> Add description for UnusedColumnInspection

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/MismatchJoinColumnInspection.kt
=> Fix IndexOutOfBoundsException in MismatchJoinColumnInspection

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/JavaTypeMixin.kt
=> Fix npe in JavaTypeMixin

drivers/native-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/native/connectionpool/WalConcurrencyTest.kt
=> Ignore flaky WAL test

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/FileIndex.kt
=> Add more information for package name errors

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/ProjectService.kt
=> Run the database sync write inside of a write action

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedQueryInspection.kt
=> Avoid crashing during the unused query inspection

sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt
=> If the associated virtual file is null, the module is null

sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/ProjectService.kt
=> Do not reparse under a new dialect if the project is already disposed

drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt
This changes allows you to use more already defined implementation in your custom Jdbc driver.
=> Open JdbcDriver for 3rd party driver implementations

build.gradle, gradle/dependencies.gradle
Not sure when this got out of sync but just opening the PR for it so I can see the build go green before merging
=> Use snapshot version in sql-psi-dev

drivers/android-driver/build.gradle, gradle/dependencies.gradle, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/ExpressionTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Add keyword mangling to select function parameters

sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/test/schema-output/build.gradle
=> Register migration output task without derviving schemas from migrations

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/MismatchJoinColumnInspection.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/NullEqualityInspection.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedColumnInspection.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedImportInspection.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedQueryInspection.kt, sqldelight-idea-plugin/src/main/resources/inspectionDescriptions/MismatchJoinColumn.html, sqldelight-idea-plugin/src/main/resources/inspectionDescriptions/RedundantNullCheck.html, sqldelight-idea-plugin/src/main/resources/inspectionDescriptions/UnusedImport.html, sqldelight-idea-plugin/src/main/resources/inspectionDescriptions/UnusedQuery.html
=> Add missing inspection descriptions

sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
=> Add test for not compileable code produced by query with limit-offset

docs/js_sqlite/index.md
Reference: https://kotlinlang.org/docs/js-project-setup.html#webpack-configuration-file
=> Folder name for webpack config should be webpack.config.d

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt
=> Fix exception in GotoDeclarationHandler

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryInterfaceGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/TableInterfaceGenerator.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/tables/InterfaceGeneration.kt, sqldelight-compiler/src/test/table-interface-fixtures/requires-adapter/output/com/sample/Person.kt, sqldelight-compiler/src/test/view-interface-fixtures/only-table-type/output/com/sample/Person.kt, sqldelight-compiler/src/test/view-interface-fixtures/requires-adapter/output/com/sample/Person.kt, sqldelight-compiler/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonAndFriends.kt, sqldelight-compiler/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonCool.kt
=> Emit annotations on properties instead of types

.github/workflows/PR.yml, gradle.properties
=> Give more memory to gradle

.github/workflows/Release.yml, .github/workflows/rebase.yml, .github/workflows/sql-psi-dev.yml
See https://github.com/square/kotlinpoet/pull/1119.
=> Disable jobs in forked repository

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightFile.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/JavaTypeMixin.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightReferenceContributor.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/ReferenceContrubutorTest.kt
=> Fix unresolved kotlin types

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/ProjectService.kt
This was causing crashes if you undid a file deletion
=> Regenerate the database outside of the thread an undo action is performed on

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/intentions/AddImportIntention.kt
=> Add import hint action

docs/jvm_h2/query_arguments.md, docs/jvm_h2/types.md
I verified this behavior in the HSQL integration tests against `master`
=> Update H2 docs

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
Bets on how long until i start writing presenters for sqldelight
=> Correctly move off the main thread during file parsing and only move back on to write

dialects/sqlite-3-24/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_24/SqliteTypeResolver.kt, dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/SqliteDialect.kt, dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/SqliteTypeResolver.kt, dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/grammar/mixins/ReturningClauseMixin.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/build.gradle, sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/settings.gradle, sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/src/main/sqldelight/app/cash/sqldelight/integration/Person.sq, sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt
Pretty much just copied https://github.com/cashapp/sqldelight/pull/2996
=> Support Sqlite 3.35 returning statements

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/SqliteTypeResolver.kt, sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/QueryWithResults.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedExecute.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightQueriesFile.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-gradle-plugin/src/test/integration/src/main/sqldelight/app/cash/sqldelight/integration/Person.sq, sqldelight-gradle-plugin/src/test/integration/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt
=> Support returning at the end of a grouped statement

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dates.sq, sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt, sqldelight-gradle-plugin/src/test/integration/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt
Closes https://github.com/AlecStrong/sql-psi/issues/153
=> Support postgres date types

sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dog.sq, sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Closes https://github.com/AlecStrong/sql-psi/issues/157
=> Confirm booleans work for postgres

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/PgInsertOnConflictTest.kt
https://github.com/cashapp/sqldelight/pull/2922
=> Supp app satook/pg upsert bug

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/test/fixtures_postgresql/limit-offset/Test.s
Closes https://github.com/AlecStrong/sql-psi/issues/158
=> Support optional limits in Postgres

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/JsonExpressionMixin.kt, dialects/postgresql/src/test/fixtures_postgresql/json_functions/Test.s
Closes https://github.com/AlecStrong/sql-psi/issues/193
=> Support json specific operators

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/test/fixtures_postgresql/column_types/Sample.s
Closes https://github.com/AlecStrong/sql-psi/issues/218
=> Support PG BYTEA type

dialects/postgresql/src/test/fixtures_postgresql/function-casts/Test.s
Test for https://github.com/AlecStrong/sql-psi/issues/222
=> Add test for function casts

dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlTypeResolver.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/dialects/DialectTypes.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/ExpressionTest.kt
Closes https://github.com/AlecStrong/sql-psi/issues/263
=> Correctly pick function types for non-sqlite dialects

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/AlterTableColumnAliasMixin.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/TableInterfaceGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/integration/TableIntegration.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/InsertStmtValuesMixin.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/Columns.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/CreateTableUtil.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/InsertStmtUtil.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/migrations/MigrationQueryTest.kt, sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/com/example/1.sqm, sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/com/example/2.sqm, sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/com/example/3.sqm, sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/com/example/Data.sq, sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/output/com/example/DataQueries.kt, sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/output/com/example/Test.kt, sqldelight-gradle-plugin/src/test/integration-postgresql-migrations/.gitignore, sqldelight-gradle-plugin/src/test/integration-postgresql-migrations/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Products.sq, sqldelight-gradle-plugin/src/test/integration-postgresql-migrations/src/main/sqldelight/migrations/app/cash/sqldelight/postgresql/integration/V3__Product_alter.sqm
Closes https://github.com/AlecStrong/sql-psi/issues/231
=> Correctly resolve alter table rename statements

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/test/fixtures_postgresql/column_types/Sample.s, drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Arrays.sq, sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Closes https://github.com/AlecStrong/sql-psi/issues/194
=> Support PostgreSQL array types

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
Closes https://github.com/AlecStrong/sql-psi/issues/289
=> Properly store/retrieve UUID types in PG

sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
Closes https://github.com/AlecStrong/sql-psi/issues/221
=> Confirm ? IS NULL works on HQL

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt
Closes https://github.com/AlecStrong/sql-psi/issues/191
=> Add some MySQL functions

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/MySql.bnf, dialects/mysql/src/test/fixtures_mysql/replace/Test.s
Closes https://github.com/AlecStrong/sql-psi/issues/271
=> Support MySQL Replace

dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/grammar/hsql.bnf, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/MySql.bnf, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
Closes https://github.com/AlecStrong/sql-psi/issues/229
=> Generated clause to ANSI sql

.github/workflows/PR.yml, dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/grammar/hsql.bnf, dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/grammar/mixins/ResultColumnMixin.kt, dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/grammar/mixins/WindowDefinitionMixin.kt, dialects/hsql/src/test/fixtures_hsql/window-functions/Test.s, dialects/mysql/src/test/fixtures_mysql/generated-columns/1.s, dialects/sqlite-3-25/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_25/grammar/mixins/ResultColumnMixin.kt, dialects/sqlite-3-25/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_25/grammar/sqlite.bnf, dialects/sqlite-3-25/src/test/fixtures_sqlite_3_25/window_functions/Test.s
Closes https://github.com/AlecStrong/sql-psi/issues/230
=> Add HSQL Window functionality and fix SQLite window functionality

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/CopyMixin.kt, dialects/postgresql/src/test/fixtures_postgresql/copy/Sample.s
https://www.postgresql.org/docs/current/sql-copy.html
You still need a [CopyManager](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html). But sqldelight could provide the query.
=> Postgres copy

sqldelight-compiler/integration-tests/src/test/kotlin/app/cash/sqldelight/core/integration/IntegrationTest.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/Player.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/Team.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamForCoach.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/TableInterfaceGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ColumnTypeMixin.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/sqldelight.bnf, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/tables/InterfaceGeneration.kt
Closes https://github.com/cashapp/sqldelight/issues/2713
=> Support generating value types for marked columns

drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt, runtime/src/commonMain/kotlin/app/cash/sqldelight/db/OptimisticLockException.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ColumnTypeMixin.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/tables/OptimisticLockTest.kt, sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/WithLock.sq, sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
=> Throw an optimistic lock exception if an update fails

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt
Closes https://github.com/cashapp/sqldelight/issues/2990
=> Run the goto handler in an empty progress indicator

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/lang/SqlDelightHighlightVisitor.kt
Closes https://github.com/cashapp/sqldelight/issues/2981
Closes https://github.com/cashapp/sqldelight/issues/2976
=> Ensure the highlight visitor doesnt run if the project isnt configured

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
Closes https://github.com/cashapp/sqldelight/issues/1545
=> Support inferring an integer value as a boolean for parameters

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/PragmaWithResults.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/SelectQueryable.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/ParserUtil.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
Closes https://github.com/cashapp/sqldelight/issues/1106
=> Support PRAGMA statements which return a value

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlType.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt
Closes https://github.com/cashapp/sqldelight/issues/2051
=> Support NUMERIC/BigDecimal MySQL types

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
Closes https://github.com/cashapp/sqldelight/issues/1837
=> Ensure transitive generated code is also updated in the IDE

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/SelectQueryable.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
Closes https://github.com/cashapp/sqldelight/issues/1874
Closes https://github.com/cashapp/sqldelight/issues/2313
=> Query result should use tables in the select if there are multiple matches

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlDialect.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/mixins/MySqlBinaryEqualityExpr.kt, dialects/mysql/src/test/fixtures_mysql/mysql-incorrect-equality/Test.s, dialects/mysql/src/test/kotlin/app/cash/sqldelight/dialects/mysql/MySqlFixturesTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
Closes https://github.com/cashapp/sqldelight/issues/2673
=> Error on usage of == in MySQL

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/SelectStmtUtil.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
Closes https://github.com/cashapp/sqldelight/issues/2471
continuing to feel stunned this stuff just works for the most part
=> Support returning queries inside of common table expressions

sqldelight-compiler/integration-tests/src/test/kotlin/app/cash/sqldelight/core/integration/IntegrationTest.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
Closes https://github.com/cashapp/sqldelight/issues/2785
=> Put grouped queries inside a transaction

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlType.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/MySql.bnf, dialects/mysql/src/test/fixtures_mysql/date_functions/Test.s, sqldelight-gradle-plugin/src/test/integration-mysql/src/main/sqldelight/app/cash/sqldelight/mysql/integration/Dates.sq, sqldelight-gradle-plugin/src/test/integration-mysql/src/test/kotlin/app/cash/sqldelight/mysql/integration/MySqlTest.kt
=> Support MySql INTERVAL

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt
Tired of Android Studios embedded jdk finding its way into my settings
=> Use java home for gradle tooling API

sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/FailureTest.kt
Closes https://github.com/cashapp/sqldelight/issues/2719
=> Include the dialect used to compile in failure reports

build.gradle
=> Remove extra kotlinNodeJs.nodeVersion

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/tables/InterfaceGeneration.kt
Closes https://github.com/cashapp/sqldelight/issues/2508
=> Postgres primary key columns are always non-null

sqldelight-gradle-plugin/src/test/integration-multi-dialect-modules/build.gradle, sqldelight-gradle-plugin/src/test/integration-multi-dialect-modules/mysql-module/build.gradle, sqldelight-gradle-plugin/src/test/integration-multi-dialect-modules/mysql-module/src/main/sqldelight/com/example/BackendTable.sq, sqldelight-gradle-plugin/src/test/integration-multi-dialect-modules/settings.gradle, sqldelight-gradle-plugin/src/test/integration-multi-dialect-modules/sqlite-module/build.gradle, sqldelight-gradle-plugin/src/test/integration-multi-dialect-modules/sqlite-module/src/main/sqlite/com/example/ClientTable.sq, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/dialect/DialectIntegrationTests.kt
Closes https://github.com/cashapp/sqldelight/issues/2677
=> Confirm multi-dialects across modules works fine

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/MySql.bnf, dialects/mysql/src/test/fixtures_mysql/select-for/Test.s
Closes https://github.com/cashapp/sqldelight/issues/2784
=> Support FOR SHARE and FOR UPDATE in MySQL

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/MySql.bnf, dialects/mysql/src/test/fixtures_mysql/index-hints/Test.s
Closes https://github.com/cashapp/sqldelight/issues/2794
=> Support MySQL index hints

CHANGELOG.md
=> Extend changelog documentation for alpha01 + alpha02.

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/ide/PostgresConnectionDialog.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/ConnectionOptions.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/SqlDelightRunVisitor.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/SqlDelightStatementExecutor.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/window/ConnectionListPanel.kt
https://user-images.githubusercontent.com/1675456/164507924-d30a3201-a451-4a6c-b72a-d931d00fb99a.mov
=> Use IJ Toolbar control for connections and store them by dialect

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/util/GeneratedVirtualFile.kt
=> Delete files that should be generated directories

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/InspectionExt.kt
=> Ignore NoDescriptor errors during inspections

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/MutatorQueryFunctionTest.kt
Closes https://github.com/cashapp/sqldelight/issues/3146
=> Support the iif ANSI SQL function

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-compiler/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonAndFriends.kt
Closes https://github.com/cashapp/sqldelight/issues/3143
=> Properly inherit nullability on the pipe operator

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/JavaTypeMixin.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightCopyPasteProcessor.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightReferenceContributor.kt
=> Support refactor rename of java types

drivers/android-driver/build.gradle, sample/android/build.gradle, sqldelight-gradle-plugin/src/test/fulfilled-table-variant/build.gradle, sqldelight-gradle-plugin/src/test/integration-android-library/build.gradle, sqldelight-gradle-plugin/src/test/integration-android-variants/build.gradle, sqldelight-gradle-plugin/src/test/integration-android/build.gradle, sqldelight-gradle-plugin/src/test/integration-multiplatform/android-build.gradle, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/properties/PropertiesFileTest.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/CompilationUnitTests.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/GradlePluginCombinationTests.kt, sqldelight-gradle-plugin/src/test/library-project/build.gradle, sqldelight-gradle-plugin/src/test/multi-module/AndroidProject/build.gradle, sqldelight-gradle-plugin/src/test/multi-module/MultiplatformProject/build.gradle, sqldelight-gradle-plugin/src/test/no-kotlin-android/build.gradle, sqldelight-gradle-plugin/src/test/properties-file-android/build.gradle, sqldelight-gradle-plugin/src/test/schema-file-android/build.gradle, sqldelight-gradle-plugin/src/test/variants/build.gradle, sqldelight-gradle-plugin/src/test/working-variants/build.gradle
=> Adopt new AGP dsl

drivers/native-driver/src/linuxMain/kotlin/app/cash/sqldelight/driver/native/util/PTHREAD_MUTEX_RECURSIVE.kt, drivers/native-driver/src/nativeDarwinMain/kotlin/app/cash/sqldelight/driver/native/util/PTHREAD_MUTEX_RECURSIVE.kt, drivers/native-driver/src/nativeLinuxLikeMain/kotlin/app/cash/sqldelight/driver/native/util/PoolLock.kt
https://youtrack.jetbrains.com/issue/KT-48997
=> Fixed PTHREAD_MUTEX_RECURSIVE

dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlDialect.kt, dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlTypeResolver.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlDialect.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlDialect.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/SqliteTypeResolver.kt, dialects/sqlite-3-38/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_38/SqliteDialect.kt
=> Open dialect and resolver to support 3rd party implementations

docs/index.md
Or do you prefer a local file?
=> Docs: Add information about alpha IDEA plugin channel

docs/common/grouping_statements.md
https://github.com/cashapp/sqldelight/issues/2785
=> Docs: Grouping statements are now executed in a transaction

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/DatabaseGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueriesTypeGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueryWrapperTest.kt
=> Don't generate empty query files

docs/common/gradle-dependencies.md
=> Docs: Add deriveSchemaFromMigrations when used with dependency

extensions/coroutines-extensions/build.gradle, extensions/coroutines-extensions/src/commonMain/kotlin/app/cash/sqldelight/coroutines/FlowExtensions.kt
This allows the flow extension to be used with async drivers.
=> Use "async" functions in flow extension

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/test/fixtures_postgresql/serial/ExplicitNotNull.s
Fixes https://github.com/AlecStrong/sql-psi/issues/287
=> PostgreSQL: Support using DEFAULT for generated columns in INSERT 

sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/kotlin/SourceRoots.kt
Same fixes borrowed from https://github.com/square/wire/pull/2310
=> Avoid NPEs in Kotlin 1.7.20

kotlin-js-store/yarn.lock, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncSelectQueryTypeTest.kt
=> Fix codegen for async grouped returning statements

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedQueryInspection.kt
=> IDEA: UnusedQueryInspection - fix ArrayIndexOutOfBoundsException.

settings.gradle
Needed for: https://github.com/AlecStrong/sql-psi/pull/418
Workaround for: https://github.com/gradle/gradle/issues/20070
=> Support overwriting sql-psi

settings.gradle
Reverts cashapp/sqldelight#3432
https://github.com/AlecStrong/sql-psi/pull/418#discussion_r944404492
=> Revert "Support overwriting sql-psi"

sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt
=> Fix description of squash migrations task

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/SqlInsertExcludedTableMixin.kt, sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/OneEntity.sq
=> PostgreSQL: Add Excluded in Insert DO UPDATE

gradle/gradle-mvn-push.gradle
I just copy-pasted how Paparazzi does it, per https://github.com/cashapp/sqldelight/pull/3424#discussion_r941281840.
=> Fix internal publishing helper block

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf, dialects/postgresql/src/test/fixtures_postgresql/column_types/Sample.s
=> PostgreSQL Add NOT operator

dialects/sqlite-3-35/src/test/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/Sqlite335FixturesTest.kt, dialects/sqlite-3-38/src/test/kotlin/app/cash/sqldelight/dialects/sqlite_3_38/Sqlite338FixturesTest.kt
Fixes https://github.com/cashapp/sqldelight/issues/3507
Turns out, it only affects two tests
=> Sqlite Tests: Fix package name

gradle/libs.versions.toml
https://github.com/JetBrains/kotlin/releases/tag/v1.7.20
=> Update to Kotlin 1.7.20

dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlTypeResolver.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, dialects/sqlite-3-18/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_18/SqliteTypeResolver.kt, dialects/sqlite-3-18/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_18/grammar/mixins/StatementValidatorMixin.kt, extensions/coroutines-extensions/src/commonMain/kotlin/app/cash/sqldelight/coroutines/FlowExtensions.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/StringUtil.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/ExecuteQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryInterfaceGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/TableInterfaceGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/integration/TableIntegration.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/BindableQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/Constants.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ColumnTypeMixin.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/Arguments.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightCopyPasteProcessor.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/lang/SqlDelightHighlightVisitor.kt
Mostly lowercase/uppercase/capitalize deprecations
=> Remove some warnings 

build.gradle, gradle/dependencies.gradle, sqldelight-compiler/build.gradle, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/android/PackageName.kt, sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt, sqldelight-gradle-plugin/src/test/fulfilled-table-variant/build.gradle, sqldelight-gradle-plugin/src/test/fulfilled-table-variant/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/integration-android-library/build.gradle, sqldelight-gradle-plugin/src/test/integration-android-variants/build.gradle, sqldelight-gradle-plugin/src/test/integration-android-variants/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/integration-android/build.gradle, sqldelight-gradle-plugin/src/test/integration-android/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/integration-multiplatform/android-build.gradle, sqldelight-gradle-plugin/src/test/integration-multiplatform/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TemporaryFixture.kt, sqldelight-gradle-plugin/src/test/library-project/build.gradle, sqldelight-gradle-plugin/src/test/library-project/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/multi-module/AndroidProject/build.gradle, sqldelight-gradle-plugin/src/test/multi-module/AndroidProject/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/multi-module/MultiplatformProject/build.gradle, sqldelight-gradle-plugin/src/test/multi-module/MultiplatformProject/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/properties-file-android/build.gradle, sqldelight-gradle-plugin/src/test/properties-file-android/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/schema-file-android/build.gradle, sqldelight-gradle-plugin/src/test/schema-file-android/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/variants/build.gradle, sqldelight-gradle-plugin/src/test/variants/src/main/AndroidManifest.xml, sqldelight-gradle-plugin/src/test/working-variants/build.gradle, sqldelight-gradle-plugin/src/test/working-variants/src/main/AndroidManifest.xml
=> Kotlin 1.7.20 compatible release for 1.5.3 users

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ColumnTypeMixin.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/PgInsertReturningTest.kt, sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Value.sq, sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
=> Use value classes from table foreign key clauses

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/SelectQueryable.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/SelectStmtUtil.kt, sqldelight-gradle-plugin/src/test/integration/src/main/sqldelight/app/cash/sqldelight/integration/View.sq, sqldelight-gradle-plugin/src/test/integration/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt
=> Resolve recursive origin table from pure views

extensions/coroutines-extensions/src/commonMain/kotlin/app/cash/sqldelight/coroutines/FlowExtensions.kt, runtime/src/commonMain/kotlin/app/cash/sqldelight/Query.kt
Make Listener functional interface so anonymous function could be used instead of anonymous class in methods that uses Listener.
=> Add fun modifier to Listener interface.

.github/workflows/Renovate.yml
The requirements file could be manually changed, and it failed to trigger on a recent renovate branch too...
=> Update requirements check trigger

.github/workflows/Renovate.yml
Shell scripts are not requirements.txt
Shell scripts are not requirements.txt
Shell scripts are not requirements.txt
Shell scripts are not requirements.txt
Shell scripts are not requirements.txt
=> Shell scripts are not requirements.txt

dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Arrays.sq, sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Fixes https://github.com/cashapp/sqldelight/issues/3655
=> Postgres: Fix Array without type parameter

sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/kotlin/LinkSqlite.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/kotlin/SourceRoots.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/KotlinVersionsTest.kt, sqldelight-gradle-plugin/src/test/settings.gradle
Related https://github.com/cashapp/sqldelight/pull/3671
Do we want to add more versions/tests?
=> Support Kotlin 1.8.0-Beta and add multi version Kotlin test

docs/common/gradle-dependencies.md, docs/common/gradle.md, docs/common/index_server.md, docs/common/query_arguments.md, docs/js_sqlite/gradle.md, docs/native_sqlite/gradle.md
Fix js and native gradle macros
Better wording for "Fresh Schema" and "Derived Schema" (Closes #3344) 
Add some documentation for input sanitization (Closes #3602) 
Add documentation for deriveSchemaFromMigrations (Closes #2695)
Overhaul gradle configuration docs
=> Various documentation improvements

.github/workflows/PR.yml, .github/workflows/Release.yml
Reverts cashapp/sqldelight#3712
=> Revert "Update actions/setup-java action to v3.7.0"

.github/workflows/Publish-Website.yml, mkdocs.yml
I already ran the action so it should be fixed on the pages (soon), but in case we need to make another 1.5.x release.. may as well merge this in.
Closes #3696
Closes #2787
=> Fix broken docs links on 1.5.x branch

gradle/libs.versions.toml, sqldelight-gradle-plugin/build.gradle
=> Shrink IntelliJ from 64 to 34 MB

build.gradle, gradle/dependencies.gradle, sqldelight-compiler/build.gradle, sqldelight-compiler/integration-tests/build.gradle, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt, sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/ParserUtil.kt, sqldelight-gradle-plugin/build.gradle, sqldelight-idea-plugin/build.gradle, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/GradleSystemListener.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightCopyPasteProcessor.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightErrorHandler.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateInsertIntoQueryAction.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateSelectAllQueryAction.kt, sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/QueryByPrimaryKeyHandler.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml, sqlite-migrations/build.gradle, test-util/build.gradle, test-util/src/main/kotlin/com/squareup/sqldelight/test/util/TestEnvironment.kt
Work in progress - Created PR to test it on CI too
At least locally I am able to use the plugin manually, but I didn't upgrade intellij yet.
=> WIP - Try back porting updated IntelliJ to 1.5.3 branch

docs/common/gradle.md, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/CompilationUnitTests.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/SourcesTest.kt, sqldelight-gradle-plugin/src/test/migration-squash/build.gradle, sqldelight-gradle-plugin/src/test/multiple-project-migration-success/build.gradle, sqldelight-gradle-plugin/src/test/sources/build.gradle, sqldelight-gradle-plugin/src/test/sources/main/sqldelight/Test1.sq, sqldelight-gradle-plugin/src/test/sources/settings.gradle
=> Add `srcDirs` to `SqlDelightDatabase`

docs/jvm_mysql/index.md, docs/jvm_postgresql/index.md
The package names are apparently misspelled, not a pretty great new user experience I would say lol
=> Fix dialects package name

.github/workflows/GradleWrapper.yml, .github/workflows/PR.yml, .github/workflows/Release.yml, .github/workflows/gradleWrapper.yml
Because the wrapper validation action is flaky I created a new (failable) action.
=> Add Gradle Wrapper validation and explicit limit the CI token

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFix.kt, sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFixTest.kt
=> Fix for expand wildcard intention to work with qualifier

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/SqlDelightFileIndex.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/FileIndex.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightDirectoryCompletionContributor.kt, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
https://user-images.githubusercontent.com/14963604/226099209-1703ea8e-03b2-4c13-9f86-5f7b254898af.mov
closes #3215
=> Add sqldelight directory suggestions

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt
=> Use available jdk if java home is missing

renovate.json
=> Remove trailing comma

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/intentions/AddImportIntention.kt
Closes https://github.com/cashapp/sqldelight/issues/3969
=> Dont show auto imports for invalid elements

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/FunctionExprMixin.kt
Closes https://github.com/cashapp/sqldelight/issues/3972
=> Do not resolve if a dialect is missing

build.gradle, sqldelight-compiler/build.gradle
Fixes the current failing doc generating workflow
=> Fix some gradle/dokka configuration

.github/workflows/Publish-Website.yml, RELEASING.md, docs/android_sqlite/foreign_keys.md, docs/android_sqlite/index.md, docs/common/types_sqlite.md, docs/jvm_sqlite/foreign_keys.md, docs/multiplatform_sqlite/foreign_keys.md, docs/native_sqlite/foreign_keys.md, mkdocs.yml
Closes https://github.com/cashapp/sqldelight/issues/3931
Closes https://github.com/cashapp/sqldelight/issues/3871
Closes https://github.com/cashapp/sqldelight/issues/3707
Also automates the version number that shows up in the doc pages.
=> Fix some documentation issues

buildLogic/settings.gradle, sample/settings.gradle
Makes easier to analyze failed tasks on the web/mobile
=> Add buildscans to the sample

gradle/libs.versions.toml
Forgot to remove it after #4079
=> Remove unused jna dependency

sqldelight-compiler/environment/build.gradle, sqlite-migrations/environment/build.gradle
Otherwise dokkaHtmlMultiModule and the website fails
=> Add missing dokka plugin for new modules

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedColumnInspection.kt, sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/refactoring/SqlDelightSuggestedRefactoringExecution.kt
=> Fix add migration popup

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/SchemaNeedsMigrationInspection.kt
=> Disable SchemaNeedsMigrationInspection in migration files

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/SignatureData.kt
=> Use sql column name for migration generation instead of type name

extensions/androidx-paging3/build.gradle
Fixes https://github.com/cashapp/sqldelight/issues/4067.
=> Add iosSimulatorArm64 target to androidx-paging3 extension

gradle/libs.versions.toml, runtime/api/runtime.api, runtime/build.gradle
I believe the check just happens automatically, I'll verify after this merges.
Also only doing the runtime, I figure the other modules its less important to have ABI stability with 2.0 but I'm open to doing this elsewhere too if it seems valuable
=> Track the runtime API for compatibility issues

gradle/libs.versions.toml, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueryWrapperTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/async/AsyncQueriesTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/async/AsyncQueryWrapperTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/JavadocTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/MutatorQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/MutatorQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/PgInsertOnConflictTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncMutatorQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncSelectQueryTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/tables/OptimisticLockTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/triggers/TriggerNotificationTest.kt, sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/output/com/example/DataQueries.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/MigrationTest.kt, test-util/src/main/kotlin/app/cash/sqldelight/test/util/FixtureCompiler.kt
Isn't released yet, but need this for cutting a release so getting ready for that release
=> Upgrade to kotlinpoet 1.14

docs/upgrading-2.0.md
Found a small typo in the docs while upgrading to 2.0. Had me stumped for a while until I found an example on another page.
=> Fixes typo in upgrading-2.0.md

.github/workflows/PR-skip.yml, .github/workflows/PR.yml
=> Ignore mkdocs.yml in PR docs

.github/workflows/PR-skip.yml, .github/workflows/PR.yml
https://github.com/cashapp/sqldelight/pull/4264#issuecomment-1587802268
=> Add matrix to PR-skip.yml

sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/GenerateMigrationOutputTask.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/GenerateSchemaTask.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightPlugin.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightTask.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/VerifyMigrationTask.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/kotlin/SourceRoots.kt, sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/squash/MigrationSquashTask.kt
Reverts cashapp/sqldelight#4222
=> Revert "Gradle tweaks"

.github/workflows/PR.yml, .github/workflows/Publish-Website.yml, .github/workflows/Release.yml, .npmrc, drivers/web-worker-driver/sqljs/build.gradle
Following the NPM docs here: https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow
=> Fix npm authentication stuff

dialects/sqlite/json-module/src/test/fixtures/json_table_functions/Test.s
Closes https://github.com/cashapp/sqldelight/issues/4315
=> Verify some json query works

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/android/SqlDelightRunAnnotator.kt
Was causing some warnings that this was happening off the UiThread when it should be on the UiThread
=> Dont instantiate the database project service until needed

dialects/sqlite-3-18/src/test/fixtures_sqlite_3_18/recursive-common-table/Querys.s
Closes https://github.com/cashapp/sqldelight/issues/4057
=> Confirm recursive query works

.github/workflows/PR-skip.yml, .github/workflows/PR.yml
=> Enable PR checks on Windows

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt
=> Fix IDE generation of async code

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightTreeStructureProvider.kt
=> Move assembly of the package structure to be one-time computed and off the EDT

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightReferenceContributor.kt
=> Use the correct stub index key for kotlin type resolution on 2023.2

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
=> Wait for the index to be ready before performing a search

sqldelight-gradle-plugin/src/test/integration-catalog/src/test/kotlin/app/cash/sqldelight/mysql/integration/MySqlTest.kt, sqldelight-gradle-plugin/src/test/integration-mysql-schema/src/test/kotlin/app/cash/sqldelight/mysql/integration/MySqlTest.kt, sqldelight-gradle-plugin/src/test/integration-mysql/src/test/kotlin/app/cash/sqldelight/mysql/integration/MySqlTest.kt
Otherwise on M1 the docker tests fail and 5.7 is eol October 2023.
=> Tests: Use mysql 8.0 which supports arm64

sqldelight-compiler/integration-tests/src/test/kotlin/app/cash/sqldelight/core/integration/IntegrationTest.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/GroupQueries.kt, sqldelight-compiler/integration-tests/src/test/kotlin/com/example/Myftstable2.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt
Fixes https://github.com/cashapp/sqldelight/issues/4039
=> Don't use virtual table as interface type

dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt, dialects/mysql/src/test/fixtures_mysql/date_functions/Test.s, sqldelight-gradle-plugin/src/test/integration-mysql/src/main/sqldelight/app/cash/sqldelight/mysql/integration/Dates.sq, sqldelight-gradle-plugin/src/test/integration-mysql/src/test/kotlin/app/cash/sqldelight/mysql/integration/MySqlTest.kt
=> MySQL: Add now

dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlType.kt, dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlType.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt, dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt, sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/DialectType.kt, sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/PrimitiveType.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/IntermediateType.kt, sqldelight-gradle-plugin/src/test/custom-dialect/dialect/src/main/kotlin/foo/FooDialect.kt
Fixes https://github.com/cashapp/sqldelight/issues/3791
=> Use CodeBlock in prepareStatementBinder in DialectType

sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/src/main/sqldelight/app/cash/sqldelight/integration/Person.sq, sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/IntegrationTest.kt
I didn't find a test using this test fixture, so let's test this fixture.
=> Enable Sqlite 3.35 integration test

docs/common/types_server_migrations.md
=> fix(docs): typo

renovate.json
ain't(nobody): got time for that
=> disable(semantic): commits in Renovate

sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueriesTypeGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SelectQueryGenerator.kt, sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
=> Fix compilation of grouped statements with returns

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightReferenceContributor.kt
Closes https://github.com/cashapp/sqldelight/issues/4325
Was renamed from INSTANCE (default) to Helper in 2023.2
=> Reflectively get the kotlin top level companion object

.github/workflows/PR.yml, .github/workflows/Publish-Website.yml, .github/workflows/Release.yml
They moved to a new repo: https://github.com/gradle/actions
=> CI: Use new Gradle setup action

.github/workflows/PR-skip.yml, .github/workflows/PR.yml, .github/workflows/Publish-Website.yml, .github/workflows/Release.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
They are way faster!
=> CI: Use M1 runner

.github/workflows/PR.yml
Everytime I look at the PR matrix I not sure if we really run a full build due its complexity (and outdated comments) so let's move the sample steps out of the matrix.
=> CI: Move samples out of matrix

.github/workflows/prepare_mkdocs.sh, build.gradle, gradle.properties
for https://github.com/Kotlin/dokka/issues/2954
=> CI: Remove outdated workaround 

sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/window/ConnectionListPanel.kt
=> Specify the thread to use for the connection list clear action

drivers/sqlite-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/sqlite/JdbcSqliteSchema.kt
=> Run SQLite migrations inside transaction as mentioned in documentation

sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/core/SqlDelightEnvironment.kt, sqldelight-gradle-plugin/src/test/bad-underlines/build.gradle, sqldelight-gradle-plugin/src/test/bad-underlines/settings.gradle, sqldelight-gradle-plugin/src/test/bad-underlines/src/main/sqldelight/Test1.sq, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/FailureTest.kt
=> Fixes error alignment when line contains tabs

extensions/androidx-paging3/build.gradle
=> feat(paging3-extension): support macos

.github/workflows/PR.yml, .gitignore, gradle.properties, gradle/libs.versions.toml, sqldelight-idea-plugin/build.gradle, sqldelight-idea-plugin/gradle.properties, sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
Fixes https://github.com/cashapp/sqldelight/issues/5310
Fixes https://github.com/cashapp/sqldelight/issues/5120
=> Migrate to new Gradle IntelliJ plugin

drivers/web-worker-driver/build.gradle, extensions/androidx-paging3/build.gradle, gradle/libs.versions.toml, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/GradlePluginCombinationTests.kt
=> Kotlin 2.1.21

adapters/primitive-adapters/build.gradle, drivers/android-driver/build.gradle, drivers/jdbc-driver/build.gradle, drivers/r2dbc-driver/build.gradle, drivers/sqlite-driver/build.gradle, extensions/androidx-paging3/build.gradle, extensions/async-extensions/build.gradle, extensions/coroutines-extensions/build.gradle, extensions/rxjava2-extensions/build.gradle, extensions/rxjava3-extensions/build.gradle, gradle/libs.versions.toml, sample/common/build.gradle, sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/properties/PropertiesFileTest.kt
=> Towards Gradle 9 compatibility

gradle/libs.versions.toml, sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
=> SQL PSI 0.6.0
