sqldelight/sqldelight

- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/generating/SqlDocumentAnnotator.kt
- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/generating/TableGenerator.kt
- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/util/PsiUtil.kt
- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/util/SqlitePsiUtils.kt
We can provide our own implementations of PsiElements, which will be necessary for the NameAllocator changes and probably others. Also the Psi layer of abstraction is what the rest of the codebase uses.
> Use Psi elements instead of AST

- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/generating/SqlDocumentAnnotator.kt
- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqlDelightFileViewProviderFactory.kt
- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/lang/SqliteFile.kt
- sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
Closes #44
Also fixes an issue where model files aren't generated until you open the `.sq` file
> Create the model files on creation and during the synchronization step

- sqldelight-studio-plugin/build.gradle
This has the Kotlin 1.0 plugin which should resolve the mismatch warnings during development.
> Update to IDEA 15.0.4.

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/Status.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/ForeignKey.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Resolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/Value.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt
Also use the sqlite type during resolution so erroneous java types dont throw
> Dont duplicate the error annotations if many queries in the file reference a broken table

- README.md
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt
- sqldelight-gradle-plugin/src/test/fixtures/custom-class-works-fine/expected/com/test/UserModel.java
- sqldelight-gradle-plugin/src/test/fixtures/expression-like/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/nullable-boolean/expected/com/test/UserModel.java
- sqldelight-gradle-plugin/src/test/fixtures/nullable-enum/expected/com/test/UserModel.java
- sqldelight-gradle-plugin/src/test/fixtures/sql-types-to-java-types/expected/com/test/TypeModel.java
- sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java
- sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/TeamModel.java
- sqldelight-gradle-plugin/src/test/fixtures/works-fine-as-library/expected/com/test/UserModel.java
- sqldelight-gradle-plugin/src/test/fixtures/works-fine/expected/com/test/UserModel.java
This reverts commit 03854d003c21e6237872c7e88f4ce99155215a41.
cc @rharter.
There's a JDK compiler bug with method references that this change can trip in ways that only fail when you exercise certain code paths at runtime. This is far too risky for us to ship at this time. If the bug gets fixed for later JDK 8 builds and/or JDK 9 we can revisit this change (hopefully before a 1.0).
The bug is not public yet. I will try to remember to link it here when it's made public by Oracle.
> Revert "Removes public modifier from generated interfaces."

- sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4
they're currently not supported anyways (you will get compiler errors if you try using them) but this just explicitly removes them from the grammar.
> Remove virtual table support

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/model/File.kt
- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
Noticed this while testing against IJ 2016 since it stores the module file under the `.idea` directory. This change will always place the generated files sibling to the `src` directory, which is the behavior we want.
net 11 lines added, happy jake?
> Use source directory instead of module file

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/types/SymbolTable.kt
- sqldelight-studio-plugin/testData/main/Test4.sq
Closes #304 
antlr treats "errors" and "exceptions" differently, not sure why
`sqldelight-studio-plugin/testData/main/Test3.sq` raises an antlr Error
`sqldelight-studio-plugin/testData/main/Test4.sq` (added in PR) throws an antlr exception
> If an antlr exception causes a rule to break dont add that rule to the symbol table

- sqldelight-studio-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDocumentAnnotator.kt
```
Invalid range specified: (3323,3322); 
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:129)
at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:220)
at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:215)
at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:211)
at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
at com.squareup.sqldelight.intellij.lang.SqlDocumentAnnotator.apply(SqlDocumentAnnotator.kt:37)
at com.squareup.sqldelight.intellij.lang.SqlDocumentAnnotator.apply(SqlDocumentAnnotator.kt:25)
at com.intellij.codeInsight.daemon.impl.ExternalToolPass.applyRelevant(ExternalToolPa …
```
> Antlr exceptions shouldnt cause problems if the text range is invalid

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt
- sqldelight-gradle-plugin/src/test/fixtures/column-casing/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test1Model.java
- sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/sample/Test1Model.java
- sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/test/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/thing/Test3Model.java
- sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java
Since they are always instantiated by the factory, the public/private distinction isn't needed and being non-private avoids a synthetic accessor method.
> Always package scope the mapper constructor.

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/MapperSpec.kt
- sqldelight-gradle-plugin/src/test/fixtures/cast-as-text/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/column-casing/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test1Model.java
- sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/individual_table_columns/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/sample/Test1Model.java
- sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/test/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/mapper-interfaces/expected/com/thing/Test3Model.java
- sqldelight-gradle-plugin/src/test/fixtures/nullability/expected/com/sample/Test1Model.java
- sqldelight-gradle-plugin/src/test/fixtures/nullability/expected/com/sample/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/well-formed-selects/expected/com/sample/HockeyPlayerModel.java
> Make mapper constructors public.

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
This is important for linking gradle errors to a specific file from the IDE, since files can have the same name in separate packages.
> Use the absolute path of the failure file in gradle errors

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/ExpressionResolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/JoinResolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/Resolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/SelectResolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/TableResolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/util/AntlrUtil.kt
- sqldelight-gradle-plugin/src/test/fixtures/with-recursive/failure.txt
- sqldelight-gradle-plugin/src/test/fixtures/with-recursive/src/main/sqldelight/com/sample/Test.sq
- sqldelight-gradle-plugin/src/test/fixtures/with-table-no-column/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/with-table-no-column/failure.txt
- sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/completion/CompletionTests.kt
- sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/findusages/FindUsagesTests.kt
- sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/CommonTable.sq
- sqldelight-studio-plugin/testData/main/Test1.sq
Closes #417 
Notable bugs this uncovered:
- When you specify common table columns it isn't doing a projection it's aliasing the existing columns.
- If there are multiple possible columns for a column name expression it uses the closest scoped column.
> Enabled WITH RECURSIVE syntax

- sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml
Hoping this fixes the `NoClassDef` and `NoMethodDef` errors as well.
> Update the until build to new format

- sqldelight-compiler/src/main/antlr/com/squareup/sqldelight/Sqlite.g4
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/DeleteValidator.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/SqlDelightValidator.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/UpdateValidator.kt
- sqldelight-gradle-plugin/src/test/fixtures/timestamp-literals/failure.txt
- sqldelight-gradle-plugin/src/test/fixtures/update-validation-failures/failure.txt
- sqldelight-gradle-plugin/src/test/fixtures/update-validation-failures/src/main/sqldelight/com/sample/Test.sq
- sqldelight-studio-plugin/src/test/kotlin/com/squareup/sqldelight/completion/CompletionTests.kt
- sqldelight-studio-plugin/testData/completion/main/sqldelight/com/sample/UpdateTableName.sq
Close #443 
Delete/Update limited aren't available on stock android sqlite anyways, you would have to compile yourself with a specific compiler flag.
> Drop limited table support which fixes autocompleting in updates

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/JoinResolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/resolution/Resolver.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/validation/JoinValidator.kt
- sqldelight-gradle-plugin/src/test/fixtures/subselect-in-delete/expected/com/sample/FolderModel.java
- sqldelight-gradle-plugin/src/test/fixtures/subselect-in-delete/expected/com/sample/MessageModel.java
- sqldelight-gradle-plugin/src/test/fixtures/subselect-in-delete/src/main/sqldelight/com/sample/Folder.sq
- sqldelight-gradle-plugin/src/test/fixtures/subselect-in-delete/src/main/sqldelight/com/sample/Message.sq
Fixes #447 
Join validation was improperly unscoping result columns from the left table and treating it as a flat table (with potentially ambiguous columns). The change in `JoinResolver` reverses that (gets rid of the flatmap)
> Fix an error where join was unscoping variables before validating the constraint clause

- build.gradle
Google "accidentally" deleted 24.2.0 in the latest version.
> Update to support-annotations to 24.2.1.

- gradle/wrapper/gradle-wrapper.properties
It gets a methodnotfound error on `getInputs` if the plugin is used with a 2.14 project
> Revert to 2.14 since there are breaking changes

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/SqliteCompiler.kt
- sqldelight-gradle-plugin/src/test/fixtures/duplicate-view-result-column-names/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test1Model.java
- sqldelight-gradle-plugin/src/test/fixtures/generate-view-mappers/expected/com/sample/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/individual_table_columns/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/nullability/expected/com/sample/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/scoped-table-resolution/expected/com/test/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/second-arg-requires-factory/expected/com/sample/TestViewModel.java
- sqldelight-gradle-plugin/src/test/fixtures/tables-through-view/expected/com/sample/Test2Model.java
- sqldelight-gradle-plugin/src/test/fixtures/view-file-no-args/expected/com/sample/TestModel.java
- sqldelight-gradle-plugin/src/test/fixtures/view-preserves-type/expected/com/sample/TestModel.java
This should implement #354. I hope I did it right, please let me know whether something needs changing.
As a side note, I’ve been thinking that generating a field with an immutable list of table names each view consists of would be useful with SQLBrite since it could be used directly as a list of triggers for [`BriteDatabase#createQuery(Iterable<String>, String, String...)`][0].
I’d be happy to implement the above if it sounds reasonable.
[0]: https://square.github.io/sqlbrite/0.x/sqlbrite/com/squareup/sqlbrite/BriteDatabase.html#createQuery-java.lang.Iterable-java.lang.String-java.lang.String...-
> Generate name fields for views

- sqldelight-runtime/src/main/java/com/squareup/sqldelight/SqlDelightStatement.java
It's a value type. There's no reason to subtype or mock.
> Mark SqlDelightStatement as final.

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
I tried writing an integration test for the plugin that applies it to an Android library project, but wasn't able to reproduce the issue, as expected.
Anyways, this fixed the issue for us. The `DependencyResolutionListener` sounds unnecessary to me and AFAIK we should be able to remove it and add the compile dependencies directly.
Fixes #633
> Fix InvalidUserDataException during Gradle configuration with AGP 3 beta

- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/DuplicateSqlIdentifiers.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/ErrorTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/util/FixtureCompiler.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/views/InterfaceGeneration.kt
- Move all under-test compilation logic into `FixtureCompiler`
- Extend setup to enable dynamic fixture creation, which allows using SQL strings as test inputs
> Improve test setup in the core module

- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryInterfaceGenerator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/TableInterfaceGenerator.kt
- sqldelight-core/src/test/query-interface-fixtures/query-requires-type/com/sample/JoinedWithUsing.kt
- sqldelight-core/src/test/table-interface-fixtures/requires-adapter/com/sample/Person.kt
- sqldelight-core/src/test/view-interface-fixtures/requires-adapter/com/sample/PersonAndFriends.kt
- sqldelight-core/src/test/view-interface-fixtures/requires-adapter/com/sample/PersonCool.kt
The idea being that if/when we generate bytecode instead the api is the same, and if we dont generate bytecode then all that changes from the java side is it extends an abstract class (sucks but whevs).
> Make the generated kotlin interface unaffected by the java interface

- README.md
- build.gradle
- sqldelight-gradle-plugin/build.gradle
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
- sqldelight-gradle-plugin/src/test/integration/build.gradle
- sqldelight-runtime/build.gradle
- sqldelight-sample/build.gradle
This also removes Retrolambda in tests and the usage. Since we require AGP 3.x for consumers, it's safe enough to recommend the use of desugar for Java 8 language features.
> Upgrade to Android Gradle Plugin 3.0.

- gradle/dependencies.gradle
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
- sqldelight-gradle-plugin/src/test/build.gradle
- sqldelight-gradle-plugin/src/test/fixtures/works-fine-as-library/build.gradle
- sqldelight-gradle-plugin/src/test/fixtures/works-for-kotlin/build.gradle
- sqldelight-gradle-plugin/src/test/integration/build.gradle
- sqldelight-runtime/build.gradle
This allows us to remove a hack from the Gradle plugin which added them manually for the purpose of tests. Each test build.gradle just adds the runtime transitive deps manually using the variable.
> Use a variable for all runtime transitive deps.

- build.gradle
- gradle/dependencies.gradle
- runtime/android-driver/build.gradle
- runtime/android-driver/gradle.properties
- runtime/android-driver/src/main/AndroidManifest.xml
- runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt
- runtime/android-driver/src/test/java/com/squareup/sqldelight/android/DriverTest.kt
- runtime/sqldelight-runtime/src/main/java/com/squareup/sqldelight/db/SqlDatabaseConnection.kt
- runtime/sqldelight-runtime/src/main/java/com/squareup/sqldelight/db/SqlPreparedStatement.kt
- runtime/sqldelight-runtime/src/test/java/com/squareup/sqldelight/QueryTest.kt
- runtime/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/SqliteJdbcOpenHelper.kt
- settings.gradle
- sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-core-integration-tests/src/test/kotlin/com/example/QueryWrapper.kt
- sqldelight-core-integration-tests/src/test/kotlin/com/example/TeamQueries.kt
- sqldelight-core/build.gradle
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedMutator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
Had to change the signature of `prepareStatement(sql: String)` to also take a statement type since the android runtime prepares selects differently from mutators. Low cost change but touched a lot of files/tests
> Add in an android driver with a basic test

- runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt
- runtime/android-driver/src/test/java/com/squareup/sqldelight/android/TransacterTest.kt
- runtime/sqldelight-runtime/src/main/java/com/squareup/sqldelight/Transacter.kt
- runtime/sqldelight-runtime/src/main/java/com/squareup/sqldelight/db/SqlDatabaseConnection.kt
- runtime/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/SqliteJdbcOpenHelper.kt
- sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-core-integration-tests/src/test/kotlin/com/example/QueryWrapper.kt
- sqldelight-core-integration-tests/src/test/kotlin/com/example/TeamQueries.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueriesTypeGenerator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt
cc @swankjesse 
Puts the burden of maintaining transactions on the database connection. SQLite and Android drivers do super basic single-connection multiple-thread implementations.
> Move ownership of transaction creation to drivers

- gradle/dependencies.gradle
- runtime/rxjava2-extensions/build.gradle
- runtime/rxjava2-extensions/gradle.properties
- runtime/rxjava2-extensions/src/main/kotlin/com/squareup/sqldelight/runtime/rx/QueryObservable.kt
- runtime/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/ObservingTest.kt
- runtime/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/QueryObservableTest.kt
- runtime/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/QueryTest.kt
- runtime/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/RecordingObserver.kt
- runtime/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/TestDb.kt
- runtime/sqldelight-runtime/build.gradle
- runtime/sqldelight-runtime/src/main/java/com/squareup/sqldelight/Query.kt
- runtime/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/SqliteJdbcOpenHelper.kt
- settings.gradle
- sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-core-integration-tests/src/test/kotlin/com/example/TeamQueries.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
Not sure if what I did for scheduling is actually the best api. Should the extension method not apply any scheduling? In my head its similar to the operations that emit after some amount of time (like `throttle`) which all default to something (`computation`) in that case.
But, there is no upstream from `observe()`. Does it make sense to just use the scheduler supplied as a `subscribeOn` to perform the actual query in every case? I can get that via `RxJavaPlugins.getScheduleHandler()` during `subscribeActual` and if its null I just emit on the same thread the notification was received on. That's not really obvious behavior though where the explicit scheduler argument is, which is why I went with this.
> Add in rxjava2 extensions module + tests

- gradle/dependencies.gradle
- runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt
This brings a new argument count method which we do not yet support.
> Update Android DB abstraction to 1.1.0.

- gradle/dependencies.gradle
Could not verify this locally though since I'm getting:
```
* What went wrong:
A problem occurred configuring project ':sqldelight-idea-plugin'.
> Failed to notify project evaluation listener.
> org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifact
> org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifact
> org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifact
> org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifact
```
> Update Android Gradle Plugin to 3.2.0-alpha18

- runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt
- runtime/android-driver/src/test/java/com/squareup/sqldelight/android/DriverTest.kt
Current `SqlResultSet.getLong(index: Int)` and `SqlResultSet.getDouble(index: Int)` implementation in `android-driver` returns `0` and `0.0` respectively if the value in the column is `NULL`.
This change adds a check for `NULL` for all getters.
> Support nullable values in android-driver's SqlDelightResultSet

- sqldelight-core-integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-core-integration-tests/src/test/kotlin/com/example/TeamQueries.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
This will eventually be used for granular updates but for now generates warnings in the generated code.
Closes #915
> Remove unused 'dirtied' function for now

- gradle/dependencies.gradle
- runtime/android-driver/build.gradle
- runtime/android-driver/src/main/java/com/squareup/sqldelight/android/SqlDelightDatabaseHelper.kt
- runtime/android-driver/src/test/java/com/squareup/sqldelight/android/DriverTest.kt
- runtime/android-driver/src/test/java/com/squareup/sqldelight/android/TransacterTest.kt
- sqldelight-gradle-plugin/src/test/integration-android/build.gradle
- sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.java
- sqldelight-gradle-plugin/src/test/integration-android/src/androidTest/java/com/squareup/sqldelight/integration/MigrationTest.java
- sqldelight-sample/build.gradle
Users who have not migrated can use dejetifier for compatibilit with android.arch.persistence.
> Migrate to AndroidX

- runtime/sqldelight-runtime/build.gradle
- settings.gradle
Eventually we'll want to refactor this into a more re-usable mechanism like we have with the 'maven' plugin, but for now just whip up publishing support using the 'maven-publish' plugin (required by the multiplatform plugin).
Up next: publishing a native runtime stub.
> Enable publishing of the multiplatform runtime as a one-off

- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-core/src/test/kotlin/com/squareup/sqldelight/core/views/InterfaceGeneration.kt
> Use the same result type if unioned columns have the same getter

- build.gradle
- gradle/dependencies.gradle
- runtime/sqldelight-runtime/build.gradle
- runtime/sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/Query.kt
- runtime/sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/internal/QueryList.kt
- runtime/sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/internal/sync.kt
- runtime/sqldelight-runtime/src/jsMain/kotlin/com/squareup/sqldelight/internal/sync.kt
- runtime/sqldelight-runtime/src/jvmMain/kotlin/com/squareup/sqldelight/internal/sync.kt
- runtime/sqldelight-runtime/src/nativeMain/kotlin/com/squareup/sqldelight/db/Closeable.kt
- runtime/sqldelight-runtime/src/nativeMain/kotlin/com/squareup/sqldelight/internal/sync.kt
- runtime/sqldelight-runtime/src/nativeTest/kotlin/com/squareup/sqldelight/platform.kt
- sqldelight-core/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-gradle-plugin/src/test/integration-android/build.gradle
- sqldelight-gradle-plugin/src/test/integration/build.gradle
- sqldelight-gradle-plugin/src/test/variants/build.gradle
- sqldelight-idea-plugin/build.gradle
> Create an iOS runtime stub

- .travis.yml
AGP can take care of installing the things it needs itself.
> Get rid of static installation of SDK components

- runtime/sqldelight-runtime/build.gradle
Ensure the required pom information is added to every runtime artifact. Also do some magic to ensure all of the runtime names are the same. Source jars are added to all platform artifacts now as of 1.3 RC2, we still need to add an empty javadoc jar to each platform though.
> Add pom information to all runtime artifacts, fix naming

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
This uses task configuration avoidaance for all tasks created by the
SqlDelightPlugin except the generateSqlDelightInterface task. It must be
configured in order to be passed in to `registerJavaGeneratingTask`.
Fixes #927
> Leverage task configuration avoidance.

- gradle/updateDependencies.gradle
- sqldelight-compiler/build.gradle
Downloading and unzipping of intellij were previously declared inside of
the body of a task instead of during the task action which meant that we
tried to download and unzip intellij whenever any gradle task was
executed.
This changes the download and unzip tasks to be separate tasks and
allows up to date checking to work properly. This reduces the
configuration time of the gradle build by about 15 seconds when the
files are already downloaded and unzipped.
> Move downloading intellij outside configuration.

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
This is temporary, but it simplifies the consumption story in MPP projects which also apply the Android plugin until we can handle multiplatform platforms before variants.
> Force multiplatform to ignore android plugin

- RELEASING.md
This is not aliased to 'uploadArchives' currently for snapshot-deploying purposes on CI.
> Run the 'publish' task explicitly for release

- drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/SqliteJdbcOpenHelper.kt
This should let clients configure underlying Connection (e.g. foreign key support)
> Allow to pass Properties to SqliteJdbcOpenHelper constructor

- gradle/dependencies.gradle
- sqldelight-runtime/src/main/java/com/squareup/sqldelight/SqlDelightQuery.java
- sqldelight-runtime/src/main/java/com/squareup/sqldelight/SqlDelightStatement.java
throw an `UnsupportedOperationException` in `com.squareup.sqldelight.SqlDelightQuery#getArgCount` since it's unused by framework db.
> Reopen #909: Fixes #784: Update arch db to 1.1.1

- drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/TransacterTest.kt
- drivers/ios-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/ios/IosTransacterTest.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/triggers/TriggerNotificationTest.kt
- sqldelight-gradle-plugin/src/test/integration-multiplatform/android-build.gradle
- sqldelight-gradle-plugin/src/test/integration-multiplatform/ios-build.gradle
- sqldelight-gradle-plugin/src/test/integration-multiplatform/src/commonTest/kotlin/com/squareup/sqldelight/integration/IntegrationTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/IntegrationTest.kt
- sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt
- Transacter doesn't freeze itself. This was causing errors where subclasses
would throw Immutability exceptions when they tried to set their own
properties
- Inner mutator classes are not lazy, but the prepared statements are. Having
a lazy delegate create a new inner class is disallowed on frozen objects.
- Will explore freezing the QueryWrapper by default later.
> Fix native implementation

- drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/TransacterTest.kt
- sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt
- sqldelight-runtime/src/jvmTest/kotlin/com/squareup/sqldelight/TransacterTest.kt
- Theres no initCause on kotlin throwables
- Theres no printStackTrace on kotlin throwables
- Given those I think this is the best I can do
> Include both exception during rollback failures

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
Otherwise, the task won't get invalidated if you change them.
There might be more cases where such an annotation is missing. I can dig deeper into that later.
> Add @Input annotation to packageName + className in SqlDelightTask.

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
Closes #1153.
I started to write a test but the changes to the test infrastructure became too big. Right now we use a custom annotation implementation to create one-liner errors. I'll try to migrate it to the normal one in a followup.
Here's proof it works in the form of debugger output:
> Use lineEnd for max line number digit calculation

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
`@Internal` annotation can remove following warnings.
```
> Task :sqldelight-gradle-plugin:validateTaskProperties
Task property validation finished with warnings:
- Warning: Task type 'com.squareup.sqldelight.gradle.GenerateSchemaTask': property 'sourceFolders' is not annotated with an input or output annotation.
- Warning: Task type 'com.squareup.sqldelight.gradle.SqlDelightTask': property 'sourceFolders' is not annotated with an input or output annotation.
- Warning: Task type 'com.squareup.sqldelight.gradle.VerifyMigrationTask': property 'sourceFolders' is not annotated with an input or output annotation.
```
> add Internal annotation to remove build warning

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
The absolute path is not relevant in this case when caching since we
only care about the relative path of the files inside the project.
According to the docs, this is the proper way of configuring the
PathSensitivity for the SourceTask.
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceTask.html
> The PathSensitivity for the sources is configured to be PathSensitivity.ABSOLUTE. If your sources are less strict, please change it accordingly by overriding this method in your subclass.
> Use relative path sensitivity for SourceTask.

- README.md
As a first time user of the library I was putting my `.sq` files in `src/main/java/com...` and didn't understand why codegen wasn't working.  There was a small note in the current README showing an example file path which included `src/main/sqldelight`, but it wasn't clearly called out as a requirement as a first time user, without custom gradle plugin configuration.
I'm submitting this change in hopes that it will improve the first time experience of using SqlDelight and avoid my 30 minutes of trying to figure out why it wasn't generating sources: https://twitter.com/HandstandSam/status/1093513648885116928
I finally figured it out after finding @AlecStrong's blog post and seeing it as a SQL comment in his examples: https://medium.com/square-corner-blog/announcing-sqldelight-1-0-d482aa408f …
> README suggestion of .sq files in src/main/sqldelight

- drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidSqliteDriver.kt
According to the documentation on SupportSQLiteOpenHelper, getWritableDatabase should not be called on the main thread.
Is there a reason why the writableDatabase is accessed at the creation of AndroidSqliteDriver? To me it looks like the database property is only used in queries and transactions and can therefore be a lazy property.
> Use lazy delegate when resolving writable database in AndroidSqliteDriver

- .gitignore
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
- sqldelight-gradle-plugin/src/test/integration/build.gradle
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/multi-module/AndroidProject/build.gradle
- sqldelight-gradle-plugin/src/test/multi-module/AndroidProject/src/main/AndroidManifest.xml
- sqldelight-gradle-plugin/src/test/multi-module/MultiplatformProject/build.gradle
- sqldelight-gradle-plugin/src/test/multi-module/MultiplatformProject/src/main/AndroidManifest.xml
- sqldelight-gradle-plugin/src/test/multi-module/ProjectA/build.gradle
- sqldelight-gradle-plugin/src/test/multi-module/ProjectA/src/main/sqldelight/com/sample/Other.sq
- sqldelight-gradle-plugin/src/test/multi-module/ProjectA/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt
- sqldelight-gradle-plugin/src/test/multi-module/ProjectB/build.gradle
- sqldelight-gradle-plugin/src/test/multi-module/ProjectB/src/main/sqldelight/com/sample/Data.sq
- sqldelight-gradle-plugin/src/test/multi-module/build.gradle
- sqldelight-gradle-plugin/src/test/multi-module/settings.gradle
> Support dependencies between sqldelight modules

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/KotlinPoet.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryWrapperGenerator.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueryWrapperTest.kt
> Break up string literals which are longer than the allowed length

- README.md
Instruction says `.sq` files should be inside `src/main/kotlin`, but it's actually `src/commonMain/sqldelight`.
I think this misinstruction is confusing some users trying to use the library in Multiplatform setup.
> fix multiplatform instruction in README

- drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidSqliteDriver.kt
- drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AndroidDriverTest.kt
I'm not sure if we expect these statements to be closed sometime in the future when the statements are collected or something, but it seems like we should be closing these as well.
> Ensure un-cached statements are closed after use

- extensions/coroutines-extensions/build.gradle
This ensures the artifacts will be included in the snapshot and release process.
> Map old maven plugin tasks to maven-publish tasks

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightExtension.kt
I'm working to implement SqlDelight in a build that uses `build.gradle.kts` files and struggled with the database configuration, since it relies on some dynamic features of Groovy (AFAIK).  I've been able to get my build working using the following extension function:
```kotlin
sqldelight {
operator fun String.invoke(config: SqlDelightDatabase.() -> Unit) {
methodMissing(this, arrayOf(object : Closure<SqlDelightDatabase>(this) {
fun doCall(database: SqlDelightDatabase) {
database.config()
}
}))
}
"MyDatabase" {
packageName = "com.example.db"
}
}
```
This makes for a pretty nice Kotlin DSL that mimics the groovy one pretty closely, but is also a pain and involved unnecessary wrapping when Kotlin's `apply` would work nicely.
I'm running short on time, so this is a bit untested, since it's …
> Adds support for configuration in Kotlin script build files.

- README.md
- build.gradle
- drivers/ios-driver/build.gradle
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightExtension.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/GradlePluginCombinationTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TemporaryFixture.kt
This allows native users of SQLDelight to link their own sqlite, which is useful if you want to use something other than system sqlite (i.e. compile in json1 or FTS).
> Don't link sqlite by default in ios driver; allow linking opt-out

- README.md
- drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcSqliteDriver.kt
- drivers/sqlite-driver/src/test/kotlin/com/squareup/sqldelight/driver/sqlite/SqliteDriverTest.kt
- drivers/sqlite-driver/src/test/kotlin/com/squareup/sqldelight/driver/sqlite/SqliteQueryTest.kt
- drivers/sqlite-driver/src/test/kotlin/com/squareup/sqldelight/driver/sqlite/SqliteTransacterTest.kt
- extensions/coroutines-extensions/src/jvmTest/kotlin/com/squareup/sqldelight/runtime/coroutines/TestDb.kt
- extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/TestDb.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/squareup/sqldelight/core/integration/IntegrationTest.kt
- sqldelight-gradle-plugin/src/test/integration-multiplatform/src/androidMain/kotlin/com/squareup/sqldelight/integration/android.kt
- sqldelight-gradle-plugin/src/test/integration/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt
- sqldelight-gradle-plugin/src/test/multi-module/AndroidProject/androidTest/java/com/squareup/sqldelight/integration/IntegrationTests.kt
- sqldelight-gradle-plugin/src/test/multi-module/ProjectA/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt
Previously the default behavior created an in-memory database by default which is potentially surprising behavior.
> Force JdbcSqliteDriver users to supply a DB URL

- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/TestDb.kt
- extensions/rxjava2-extensions/src/test/kotlin/com/squareup/sqldelight/runtime/rx/TestDb.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/MutatorQueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/triggers/TriggerNotificationTest.kt
- sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt
- sqldelight-runtime/src/commonMain/kotlin/com/squareup/sqldelight/internal/Functions.kt
- sqldelight-runtime/src/jsMain/kotlin/com/squareup/sqldelight/internal/Functions.kt
- sqldelight-runtime/src/jvmMain/kotlin/com/squareup/sqldelight/internal/FunctionsJvm.kt
- sqldelight-runtime/src/nativeMain/kotlin/com/squareup/sqldelight/internal/Functions.kt
Background:
We have lots of queries listening to database table, and we mostly do update inside transaction. Currently the `notifyQueries` is called after each db update. Even within a transaction, the query list is built every time when `notifyQueries` is called. The cost of building the list after every single db update is high,  when most of the query list is not empty, and when the number of update is high. 
Change:
Change the interface on Transacter `notifyQueries(notifyQueries(queryList: List<Query<*>>) )`
to `notifyQueries(identifier: Int, queryList: () -> List<Query<*>>)`
If the notify happens outside a transaction, notify it right away. Otherwise cache the function with the identifier. When transaction is committed, invoke the function to build query list and do the notification. …
> only build the notify query list when the transaction is done

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
- sqldelight-gradle-plugin/src/test/kotlin-mpp-configure-on-demand/build.gradle
- sqldelight-gradle-plugin/src/test/kotlin-mpp-configure-on-demand/gradle.properties
- sqldelight-gradle-plugin/src/test/kotlin-mpp-configure-on-demand/settings.gradle
- sqldelight-gradle-plugin/src/test/kotlin-mpp-configure-on-demand/src/commonMain/sqldelight/com/sample/Test.sq
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt
this gets rid of the reference to `projectsEvaluated`, and instead makes a lot of assumptions about how the kotlin multiplatform plugin organizes the source sets based on android variants. It's not great, but the kotlin and android plugins dont really provide the API's I would need to do this proper, so here we are.
> Support for configure-on-demand

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
**Background**
By default gradle tasks do not cache. 
**Change**
* Add `@CacheableTask` annotation to custom tasks
**Test Plan**
* Tested `generateDebug${dbName}Interface` task properly fetched from cache
```
> Task :storage:generateDebugStorageDatabaseInterface FROM-CACHE
Custom actions are attached to task ':storage:generateDebugStorageDatabaseInterface'.
Appending implementation to build cache key: com.squareup.sqldelight.gradle.SqlDelightTask_Decorated@811fa9669948b4e5154393fe4a1f21aa
Appending additional implementation to build cache key: _BuildScript_$_run_closure2$_closure6$_closure7_5e678643d94af11f7401d007fc7e139d@dd98cb2818a7a973d14370b4ca5e675f
Appending additional implementation to build cache key: com.squareup.sqldelight.gradle.SqlDelightTask_Decorated@811fa9669948b4e5154393fe …
```
> Add @CacheableTask annotation to tasks

- drivers/ios-driver/build.gradle
- gradle/dependencies.gradle
- sample/common/build.gradle
- sqldelight-gradle-plugin/src/test/integration-multiplatform/ios-build.gradle
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/GradlePluginCombinationTests.kt
- sqldelight-idea-plugin/build.gradle
**Background**
https://github.com/square/sqldelight/issues/1336
Previously, the[ kotlin incremental annotation processing](https://kotlinlang.org/docs/reference/kapt.html#incremental-annotation-processing-since-1330) feature is broken once we integrated it with sqldelight. 
**Change**
* Upgrade kotlin and idea version, upgrade dependencies.
* Build locally and test it with kapt incremental annotation processing feature to verify the fix works
> Upgrade kotlin and idea version to fix kapt issue

- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/FlowAssert.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/MappingTest.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/QueryAsFlowTest.kt
rename the following `FlowAssert` functions:
`noEvents` -> `expectNoEvents`
`noMoreEvents` -> `expectNoMoreEvents`
`item` -> `expectItem`
`complete` -> `expectComplete`
`error` -> `expectError`
> refactor flow assert

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
This will hopefully allow making the plugin dependency 'compileOnly' in the future.
Refs #1362.
> Use withId instead of type-based plugin check

- drivers/ios-driver/build.gradle
- extensions/coroutines-extensions/build.gradle
- sqldelight-runtime/build.gradle
A clean checkout of master @ b07dace1d08e1e09e259edf370fd7390be00eb3d doesn't build (or even configure) on Linux for me. For example on my Linux computer `./gradlew tasks` fails with:
```
Could not determine the dependencies of task ':drivers:ios-driver:installLocally'.
> Task with path 'publishIosX64PublicationToTestRepository' not found in project ':drivers:ios-driver'.
```
These changes defer creation of the various `publish*` tasks so that they are not created during the configuration phase and so don't need to exist if they aren't used in the build. This is also in line with [Gradle's documentation](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:how_do_i_defer_creation) recommending configuration avoidance APIs be used.
As a side note, I'm not sure …
> Defer creation of install* Gradle tasks, fixing Linux clean build

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
- sqldelight-gradle-plugin/src/test/integration-multiplatform/src/commonMain/sqldelight/com/squareup/sqldelight/integration/FtsTable.sq
While looking at the FTS table issue described in #1405, I found that the error described there is actually a more general problem with inferring the type of synthesized columns.  It can be reproduced with simple statements like those below:
```
CREATE TABLE a(id INTEGER NOT NULL PRIMARY KEY);
-- Both fail with 'Failed to compile SqliteCompoundSelectStmtImpl(COMPOUND_SELECT_STMT)'
select:
SELECT * FROM a WHERE rowid = ?;
selectJustRowid:
SELECT rowid FROM a;
```
This pull request adds handling for that case and some additional test coverage around synthesized columns and FTS tables.  The fix here isn't perfect since it forces the use of a String type.  We could hard code a type for each synthesized column into SqlDelight, though it seems a bit hack-ish.  A better solution would probably …
> Fixed type inference for synthesized columns

- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/errors/ErrorTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/views/InterfaceGeneration.kt
- sqldelight-gradle-plugin/build.gradle
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/AndroidTestUtil.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PropertiesFileTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TemporaryFixture.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TestUtil.kt
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/Extensions.kt
The test code doesn't take into account the possibility of different line endings or path separators, resulting in many of the tests failing when run locally on a Windows machine.  While there may not be a Windows CI server, it does make it more difficult for those of us on Windows to verify changes when making contributions to the project.
The changes I've made here ensure that paths and line endings are transformed to an invariant representation before comparison.  In addition to that, I found that the source folders in the SqlDelightPropertiesFile file weren't in exactly the same order, causing failures there too, so I made sure that those are sorted before comparison -- I don't think the order matters there, but correct me if I'm wrong.
Even with these changes, you still need to mess …
> Fixed tests failing when run on Windows

- CHANGELOG.md
* Added in notes for the breaking change in #1370 for `Force JdbcSqliteDriver users to supply a DB URL`.  Issue found after bumping the version in "ShoppingApp" seen here: https://github.com/handstandsam/ShoppingApp/pull/21
* Fixed the 1.1.4 change log notes to match previous releases by including `: `
> Updated 1.1.4 Change Log

- sqlite-migrations/src/main/kotlin/com/squareup/sqlite/migrations/CatalogDatabase.kt
Avoids VerifyMigrationTask emitting "Could not retrieve functions" because SQLite doesn't support routines (stored procedures).
Fixes #1348
> Tell SchemaCrawler not to get routines

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/CompilationUnitTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PropertiesFileTest.kt
Currently the Gradle task that generates the source code and the VerifyMigration task both share the `build/sqldelight` directory. One of the first things that the VerifyMigration task does is to delete this directory. If a generate interfaces task has run, then that deleted directory contained the generated source code needed to compile the project!
This change avoids clobbering the generated source code generated by changing the VerifyMigration task to use a directory named `build/sqldelight-verifyMigration` instead.
It was certainly unexpected for me to discover that a check task deletes source code generated by an earlier task, so I don't think this was by design. Changing them to use separate directories fixes the racy behavior where the build will succeed or fail determined by the …
> Give VerifyMigration task its own output directory #1380

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/CompilationUnitTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PluginTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/PropertiesFileTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TestUtil.kt
- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/folding/FoldingTests.kt
This fixes an android warning during sync (https://github.com/cashapp/sqldelight/issues/1287). The warning comes from the intellij android plugin there: https://github.com/JetBrains/android/blob/40ee31fa0b3d6733aa364c6f1561354433f523e1/android/src/com/android/tools/idea/gradle/util/GeneratedSourceFolders.java#L27
This PR adds an android constraint to what is otherwise a multiplatform project but I guess this is ok ?
> move the generated files under "generated"

- .buildscript/before_linux.sh
A recent emulator update breaks a few CI projects.  This PR applies a fix suggested by Google.
https://issuetracker.google.com/issues/145622251#comment33
> Fix emulators

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
The nested mapper lambda accesses these properties from the enclosing query which required a bridge method. Since the enclosing type is private, the properties can be public. Also, for an easy performance win, mark the properties as being backed directly by a field.
Closes #1469.
> Avoid synthetic accessor in generated code

- docs/migrations.md
- mkdocs.yml
Migrations section got missed when copying over the readme to mkdocs.
> Restore missing section for migrations to mkdocs

- drivers/native-driver/build.gradle
- sample/android/src/main/java/com/example/sqldelight/hockey/data/Extensions.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/Multiplatform.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/GradlePluginCombinationTests.kt
When the project is built, a warning message appears: "The compilation.extraOpts method used in this build is deprecated. Use compilation.kotlinOptions.freeCompilerArgs instead."
This pull request uses kotlinOptions,freeCompilerArgs instead of extraOpts. In addition, it corrects some mispellings.
> Use kotlinOptions.freeCompilerArgs instead of extraOpts.

- mkdocs.yml
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2387680/71122575-ecdaa680-21ae-11ea-8158-b3af285bfe3b.png) | ![image](https://user-images.githubusercontent.com/2387680/71122659-1eec0880-21af-11ea-876e-3a20c4b88102.png) |
MkDocs' 404 page uses relative links to the organization's github page by default resulting in broken resources (stylesheets, images et al). What's worse is that the links in the navigation sidebar also get affected so manually changing the url in the address bar is the only way to exit. 
The fix is to specify the site URL explicitly ([source](https://github.com/mkdocs/mkdocs/issues/77)). A preview of this fix can be seen on my fork: https://saket.github.io/sqldelight/page-that-does-not-exist/
Once this is deployed and confirmed to …
> Explicitly specify site-url for fixing broken 404 pages

- docs/gradle.md
- docs/index.md
Turns out MkDocs expects internal links to use the exact file format instead of pointing to the page's generated URL ([source](https://www.mkdocs.org/user-guide/writing-your-docs/)). Fixes [this issue](https://github.com/cashapp/sqldelight/issues/1534#issuecomment-568208956) in #1534. This fix can be tested on my fork [here](https://saket.github.io/sqldelight/) and [here](https://saket.github.io/sqldelight/gradle/).
> Fix broken links to gradle and upgrading docs

- .github/workflows/PR.yml
- .github/workflows/Publish-Website.yml
- .github/workflows/Release.yml
- .github/workflows/gradle-wrapper-validation.yml
- Use checkout@v2 everywhere, which is substantially faster than v1
- Run gradle wrapper validation on PRs before any other gradle commands. This is good hygiene for first line of defense, as otherwise it just tries to race the other one.
> Couple small actions updates

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightProjectService.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightPropertiesFile.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightParserDefinition.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/ProjectService.kt
This means the IDE plugin also picks up dialect changes on gradle sync, however the parser is project specific so you cant mix dialects in a single project. Which I think is fine in practice? I guess we'll roll with it for now and see when it breaks
> Move dialect ownership to the parser definition

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/ExpressionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
Fixes [#1596: Return type of avg() should be nullable](https://github.com/cashapp/sqldelight/issues/1596)
> Fix the return type of avg() to be nullable

- docs/coroutines.md
- mkdocs.yml
There is documentation for RxJava [here](https://cashapp.github.io/sqldelight/rxjava/), so it made sense to add coroutines documentation in the same style.
> Add Coroutines Extension Documentation

- .github/workflows/PR.yml
This fixes CI which was broken by this change
https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/
> start MySQL on Ubuntu before running tests

- sample/common/src/iosMain/kotlin/com/example/sqldelight/hockey/data/Date.kt
Otherwise the last three digits will always be `000`
> Fix iOS timestamp multiplication to respect milliseconds.

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt
This change doesn't affect the behavior or the method but fixes compilation error with Kotlin 1.4
> Fix compilation with Kotlin 1.4

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightFileIndex.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/TestEnvironment.kt
Before, if a project was named `taco-db`, the implementation package would correctly sanitize it to `tacodb` for the package name. The `FileIndex` used to generate later references to the generated implementation didn't do this same directory name sanitizing though, so it would try to generate a a package name with ``taco-db`` in it, which wasn't right and would fail to compile.
This tries to unify their behavior with a shared function.
> Fix inconsistency in directory name sanitizing

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/DatabaseGenerator.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/TableInterfaceGenerator.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/integration/TableIntegration.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/Constants.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/MigrationParserDefinition.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/migrations/MigrationQueryTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/views/InterfaceGeneration.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/com/example/1.sqm
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/com/example/2.sqm
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/com/example/3.sqm
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/com/example/Data.sq
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/output/com/example/DataQueries.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/output/com/example/New_test.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/MigrationTest.kt
- sqldelight-gradle-plugin/src/test/migration-schema-failure/build.gradle
- sqldelight-gradle-plugin/src/test/migration-schema-failure/src/main/sqldelight/migrations/1.sqm
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/FixtureCompiler.kt
- Respects the deriveSchemaFromMigrations gradle flag
- Basic support for IDE, there's probably bugs
- Migration files now use the same dialect as queries files.
Long term this isn't the plan, but short term it enables
code gen and custom types in ALTER TABLE statements.
> Support generating schemas from migration files

- drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt
- drivers/sqlite-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcSqliteDriver.kt
- sqldelight-gradle-plugin/src/test/integration-hsql/src/test/kotlin/com/squareup/sqldelight/hsql/integration/HsqlTest.kt
- sqldelight-gradle-plugin/src/test/integration-mysql/src/test/kotlin/com/squareup/sqldelight/mysql/integration/MySqlTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/com/squareup/sqldelight/postgresql/integration/PostgreSqlTest.kt
Closes #1614
I'm not in love with this API, but need something to give connections back to the jdbcDriver implementor. I figure we just entirely forego doing connection pooling in our driver and let the dataSource handle it, which I'm assuming is how this will usually be used.
cc @nikolajakshic in case you have thoughts here
> Return connections to the data source pool

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
The test passes, this codegen is wrong
@JGulbronson
> Bind args generation fails when numbered nullable parameter used twice

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
I will update `createArguments` in a followup, since `offset` is no longer needed
> Avoid creating duplicate argument arrays for the same parameter

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/FixtureCompiler.kt
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/TestEnvironment.kt
This should actually preserve in Postgres as well, it just removes the non Sqlite specific code.
> Preserve named arguments in MySQL

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFileIconProvider.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
Based on the conversation from https://github.com/cashapp/sqldelight/pull/1715. Surprisingly not as difficult as expected!
Caveat: This gives a weird result for multi-dialect projects where the `.sq` file icon is randomly assigned to one of the project dialect icons. This is most likely due to the following `TODO`:
https://github.com/cashapp/sqldelight/blob/34ecf08f14b8caf15bc1c88125e64c064bb3ef06/sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightProjectComponent.kt#L68-L77
> Dynamically change .sq file icon based on dialect

- extensions/android-paging/src/main/java/com/squareup/sqldelight/android/paging/QueryDataSourceFactory.kt
Fixesx #1628 
Conceptually whats changing here: we should only be calling invalidate if there are invalidation listeners, meaning we should only have a query listener if there are invalidation listeners
the rx api on top of paging (and im assuming other apis) remove their listener on `dispose` dropping it to zero, which would then trigger the data source to remove the query listener
> Fix leaky DataSource

- docs/migrations.md
The Migration documentation specifies that the gradle `generateSqlDelightSchema` task should be run, but I didn't see any indication in the documentation of how to get that task. This just adds a sentence to help with that.
Related to #1488
> Migration documentation update

- .github/workflows/PR.yml
They increased the size to 5gb which should be enough for our deps now
> Also cache gradle with github actions

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
the plugin verifier doesn't like the dependency on intellij.testFramework, so this just copies the implementation essentially
> Register the project service using picocontainer directly

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryFunctionTest.kt
Fixes #1750. This isn't needed anymore, since Kotlin null-safety guarantees are improved now that we're referencing a `data class` property directly instead of going through an `interface`.
> Remove !! for intermediate types

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightLiveTemplateContextType.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightLiveTemplatesProvider.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
- sqldelight-idea-plugin/src/main/resources/liveTemplates/SqlDelight.xml
Closes (?) https://github.com/cashapp/sqldelight/issues/1154 — Not sure as the referenced issue discusses live templates that aren't in this PR.
I copied the live templates of the built-in "SQL" template group just to keep some parity between the live templates when editing raw SQL files and SQLDelight files in IntelliJ. Also note that the "SQL" template group indicates that their live templates can be used for **all** SQL dialects, meaning that the proposed SQLDelight live templates are independent of the selected dialect.
> Add SQLDelight Live Templates that mimic built-in SQL Live Templates

- drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/TransacterTest.kt
- runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt
thank you @ansman for prior art
Closes #1219 
I think this is still binary compatible?
Also open to other ideas here, I would love to overload and just have both methods be called `transaction` but the compiler was incapable of resolving to the one with a return value
> Add a new method for returning a value from a transaction

- drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/DriverTest.kt
- drivers/native-driver/src/nativeMain/kotlin/com/squareup/sqldelight/drivers/native/NativeSqlDatabase.kt
- extensions/coroutines-extensions/build.gradle
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/TestDb.kt
- runtime/src/commonMain/kotlin/com/squareup/sqldelight/internal/Atomics.kt
All execute statements can be writes, so they should use the transactionPool to not be allowed to collide with other transactions.
> Native: make execute use transaction pool

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/util/TreeUtilTest.kt
This fixes #1767 — allows any case fts5, which sqlite appears to be cool with.
> Normalize case when preparing fts5 sql

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
This is needed on the road to making AGP a compileOnly dependency.
Refs #1362
> Defer reference to AGP type

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
While it technically works to access extensions via `property()`, this is a sort of wonky Gradle behavior where `property()` calls will try properties, extensions, extra properties, and even _tasks_ to try to fulfill the request. This makes the extension lookup explicit, since that's where `sourceSets` are defined.
> Use extensions for sourceSets

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt
As far as I can tell these are the only changes required to make them work (it worked correctly in my testing), but I'm happy to make further changes if necessary.
https://www.sqlite.org/fts5.html#_auxiliary_functions_
> Add support for sqlite fts5 auxiliary functions highlight, snippet, and bm25

- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightFixtureTestCase.kt
- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightProjectTestCase.kt
Per the deprecation notice:
> Use LightJavaCodeInsightFixtureTestCase for Java-dependent tests, BasePlatformTestCase for non-Java dependent tests.
And implementation:
```java
public abstract class LightCodeInsightFixtureTestCase extends LightJavaCodeInsightFixtureTestCase {
}
```
> Fix deprecated LightCodeInsightFixtureTestCase usage

- gradle/gradle-mvn-push.gradle
- sqldelight-gradle-plugin/build.gradle
It's nice to have a default `installArchives` tasks that places the dependencies inside `mavenLocal`. For integration tests, we can define a new target.
> Separate projectArchives target to keep default installArchives task.

- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/ExpressionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/JavadocTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
- If two sq files have labeled queries with the same name that return a custom type there will be a compiler error
- The second one will have an implementation that uses the form  which is not valid Kotlin
- https://github.com/square/kotlinpoet/blob/eff1ce460f42e0c8f489155a46da479c8e9a8c15/kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeName.kt#L406
I made this more to illustrate the problem. I have a feeling this isn't the desired fix, but I wanted to get something out there.
> Fix issue with invalid Kotlin being generated

- build.gradle
- gradle/dependencies.gradle
**\*BUILD FAILURE EXPECTED\***
In reference to https://github.com/cashapp/sqldelight/pull/1955#issuecomment-695330110.
Just an initial commit to use the SNAPSHOT build of sql-psi in the branch `sql-psi-dev`. I suppose that this sort of commit will become common as, whenever there is a new sql-psi release, `sql-psi-dev` will need to: 
1. Create a commit replacing the SNAPSHOT with the new sql-psi release
2. Merge `sql-psi-dev` into `master`
3. Create a commit in `sql-psi-dev` with the next SNAPSHOT of sql-psi (basically like this PR)
Also, once this is merged, we can change the base branch of https://github.com/cashapp/sqldelight/pull/1955 to `sql-psi-dev` and see if the build passes.
> Use SNAPSHOT build of sql-psi in sql-psi-dev

- .github/workflows/sql-psi-dev.yml
As discussed in https://github.com/cashapp/sqldelight/pull/1955#issuecomment-695330110, whenever someone pushes to `master`, the branch `sql-psi-dev` will automatically rebase onto the `HEAD` of `master`.
If `git rebase master` encounters a merge conflict, this workflow will just fail ([example workflow](https://github.com/veyndan/sqldelight/runs/1138866881?check_suite_focus=true)), and the branch must be manually rebased and have its conflicts resolved (couldn't think of a better solution around this atm).
I've also already created a branch in this repo called `sql-psi-dev` (if there's a better branch name we can always change it).
> Add workflow that automatically rebases sql-psi-dev onto master

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
The whole comment stays highlighted as a todo with this small change.
> Proper indention inside TODO comments

- extensions/coroutines-extensions/build.gradle
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/DbTest.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/MappingTest.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/QueryAsFlowTest.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/TestDb.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/runTest.kt
- extensions/coroutines-extensions/src/jsTest/kotlin/com/squareup/sqldelight/runtime/coroutines/TestDb.kt
- extensions/coroutines-extensions/src/jsTest/kotlin/com/squareup/sqldelight/runtime/coroutines/runTest.kt
- extensions/coroutines-extensions/src/jvmTest/kotlin/com/squareup/sqldelight/runtime/coroutines/MappingJvmTest.kt
- extensions/coroutines-extensions/src/jvmTest/kotlin/com/squareup/sqldelight/runtime/coroutines/TestDb.kt
- extensions/coroutines-extensions/src/jvmTest/kotlin/com/squareup/sqldelight/runtime/coroutines/runTest.kt
- extensions/coroutines-extensions/src/nativeTest/kotlin/com/squareup/sqldelight/runtime/coroutines/TestDb.kt
- extensions/coroutines-extensions/src/nativeTest/kotlin/com/squareup/sqldelight/runtime/coroutines/runTest.kt
~Browser tests are currently failing.. but node tests are running fine.~ All js tests are now working!
Restructured the initialization of the `TestDb` since the JS driver needs to be initialized asynchronously. The DB is setup through a suspend function which is part of a `DbTest` interface. `runTest` is now an extension function on that interface and calls that setup function before calling `block` and also handles cleanup afterwards. The DB is passed in to `runTest` which can then be used by the tests.
Not really the prettiest, but it's just how the JS tests need to be since as far as I know `kotlin-test` doesn't support `Promise` setup functions.
> Implement JS tests for coroutines-extensions

- drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt
Per the [documentation](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#close()) of `java.sql.Connection#close()`:
> Calling the method `close` on a `Connection` object that is already closed is a no-op.
> Remove redundant check whether connection is closed

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
I was a bit stumped as to why `SqliteType#ARGUMENT` is mapped to `cursor.getBytes(Int)`, as to me it doesn't make much sense to get the bytes from an ARGUMENT when we are getting the inferred type of the argument when calling `SqlBindExpr.argumentType()`.
Though if this is a valid use case, could we add some test fixture showcasing its usage?
> Throw when calling SqliteType.ARGUMENT#resultSetGetter(Int)

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
`resultSet` is a bit misleading as the function generates code for `cursor` getters, those of which may or may not be backed by a `ResultSet`.
> Rename resultSetGetter to cursorGetter

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/BindableQuery.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/api/DialectType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/hsql/HsqlType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/mysql/MySqlType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/postgresql/PostgreSqlType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/sqlite/SqliteType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/ColumnDefMixin.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/sqlTypeName.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/Arguments.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/ExprUtil.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/BindArgsTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/BindableQueryTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt
Resolves #2012 
I was trying to make some first steps towards making https://github.com/AlecStrong/sql-psi/issues/155 a bit easier to implement, because we can now easily pull out `PostgreSqlType`, `MySqlType`, etc. into their own dialect specific modules.
We can also now move the SQLite specific type information to the `SqliteType` enum, for example: https://github.com/cashapp/sqldelight/blob/638cf97d5036bcaa9bb7b0c15f286e1041d339c7/sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt#L147-L153
This is a proposal PR more than anything, and I just wanted to fix a small subset of the dialect type problem for demonstration. LMK your thoughts, or if you had another interim API in mind.
> Fix incorrect requested types to marshal in ColumnAdapter's

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFileIndexImpl.kt
> Use empty package name for files outside of a gradle project

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FileIndexMap.kt
> Dont start the sqldelight gradle sync if the module is disposed

- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt
`SqlPreparedStatement#bindString(1, if (value) 1L else 0L)` doesn't compile.
> Fix invalid test

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightProjectService.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/GradleSystemListener.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/ProjectService.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
Anytime you do a gradle sync it will reset the index, which also means when you apply the sqldelight plugin it will properly set the index, and then any time you create/move/delete an SQ file it will regenerate the database wrapper, meaning you never need to rerun the generate gradle task
> Improve the first time setup experience so you never have to run the gradle task

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/gradle/FetchProjectModelsBuildAction.kt
This code was making a map where the keys were system-specific path strings, but the map was being looked-up using unix path strings, so the lookup always failed on systems with non-unix paths (ie Windows)
Fixes #2052 
I'm not sure why GoToDeclarationHandlerTest wasn't failing before, but I haven't been able [to start the tests on my machine](https://github.com/cashapp/sqldelight/issues/2052#issuecomment-711041884)
> Fix GoToDeclaration/FindUsages being broken on Windows due to path separator bug

- docs/common/custom_column_types.md
In case an empty list was stored as value before, the `decode` returns a list of size one with one element of empty string.
This behavior seems to come from Kotlin's `.split()`.
Anyhow for the decoding you would expect to get an empty list out if you put one in earlier.
This is a problem since it makes the original object that was inserted into the database not comparable with the one that was read from the database later -> `equals()` becomes `false`.
This cost me a bit of debugging, I guess we should update the docs on this.
> Fix returning list with size one instead of empty list

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/integrations/VariantTest.kt
Couldn't find a way to test those.
We found a case where the generated code would not compile because of that.
```kotlin
override fun testMultipleCustomers(): Query<TestMultipleCustomers> = testMultipleCustomers
{ lookup_key, display_name, hashed_alias, sms, email, has_multiple_customers ->
TestMultipleCustomers(
lookup_key,
display_name,
hashed_alias,
sms,
email,
has_multiple_customers
)
}
```
> NBSP before lambdas

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
Had no idea where this was coming from after migrating from an Android module to KMP
> Improve missing packageName error message

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateMigrationOutputTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightWorkerTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
- sqldelight-gradle-plugin/src/test/migration-success-noisolation/build.gradle
This ensures that tasks that have this disabled aren't run concurrently.
> Fix concurency issue when disabling classLoadIsolation

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/api/DialectType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/hsql/HsqlType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/mysql/MySqlType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/dialect/postgresql/PostgreSqlType.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/MutatorQueryTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
For example, when binding `SMALLINT`, it is (currently) bound with `bindLong(smallint)`, but `SMALLINT` is implicitly `kotlin.Short`. With this PR we'd do `bindLong(smallint.toShort())` for this to compile.
This feels like a pretty major bug as all of the non-SQLite dialects we support will fail unless you only use a specific subset of the supported dialect types (e.g.,  `BIGINT` is implicitly `kotlin.Long`, so there's no type conversion to do there).
> Fix incompatible types in generated bind* and cursor.get* statements

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
> Merged columns with same Java type should persist Java type

- docs/jvm_postgresql/types.md
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/sqlTypeName.kt
An interim solution to #1882, as even though retrieving `NUMERIC` and `DECIMAL` as `kotlin.Double` fails to fully represent the type (per the issue description), retrieving them as `kotlin.Double` at least allows them to represent floating point numbers compared to the status quo of `kotlin.Long`.
> Retrieve NUMERIC and DECIMAL as Double in PostgreSQL

- docs/common/index_server.md
In the [docs](https://cashapp.github.io/sqldelight/jvm_postgresql/#typesafe-sql), no version is showing up for the driver dependency.
> Fix no version displaying for Gradle dependency in docs

- runtime/src/commonMain/kotlin/com/squareup/sqldelight/Query.kt
This adds a note about the circumstances around calls to queryResultsChanged
> Improve documentation for queryResultsChanged

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
Fix bug introduced in #2116 where an invalid cursor equality check (`check(setOf(…).size == 1) {  "…" }`) was being generated for columns being merged with different nullabilities, but neither of them had a column adapter.
> Fix erroneous cursor equality check

- gradle/updateDependencies.gradle
When working with the SQLDelight project I seemed to end up with IntelliJ downloading every time Gradle ran its configuration phase which is a bit wasteful.
The `overwrite` flag does what you'd expect, while `tempAndMove`: 
> `true` if the file should be downloaded to a temporary location and, upon successful execution, moved to the final location. If `overwrite` is set to false, this flag is useful to avoid partially downloaded files if Gradle is forcefully closed or the system crashes.
> Only download IntelliJ if no local copy exists

- sqldelight-gradle-plugin/src/test/integration-android-library/build.gradle
- sqldelight-gradle-plugin/src/test/integration-android/build.gradle
- sqldelight-idea-plugin/build.gradle
- sqlite-migrations/build.gradle
`compile` and `testCompile` are removed in Gradle 7.
> Update to Gradle 7-compatible dependency configurations

- build.gradle
Fixes application of source & target compatibility so it works as intended. See https://github.com/cashapp/sqldelight/issues/2079#issuecomment-782794215
> Set source & target compatibility for Kotlin JVM subprojects

- .github/workflows/Release.yml
- gradle/dependencies.gradle
- gradle/gradle-mvn-push.gradle
Updates the plugin to the latest version which fixes a compatibility issue with Kotlin 1.4.30. I've also replaced some deprecated bits:
- the old targets API is replaced by Gradle's native API to declare publishing repositories
- new property syntax for credentials so that we can use Gradle's credentials APIs
- replace custom `uploadArchives` with the standard Gradle task
> update maven publish plugin to 0.14.2

- .github/workflows/PR.yml
- gradle/dependencies.gradle
- sqldelight-idea-plugin/build.gradle
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
Switch to the equivalent Gradle task to verify plugin compatibility.
During testing I found IntelliJ 2019.1 & 2019.2 reported "compatibility problems" that might lead to `NoMethodFoundError`s so bumped the minimum supported version of the plugin.
> Use runPluginVerifier task to verify IntelliJ plugin compatibility

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightRenameProcessor.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFix.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFoldingBuilder.kt
Only the quick fix code is not just a direct replacement with an updated API, but I'm assuming good test coverage exists for that.
This will address all deprecated usages on platform 193 once https://github.com/AlecStrong/sql-psi/pull/237 makes its way to the plugin.
> Fix deprecation warnings on IntelliJ platform 193

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightClassCompletionContributor.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/ExpandColumnNamesWildcardQuickFix.kt
https://plugins.jetbrains.com/docs/intellij/performance.html#avoid-expensive-methods-in-psielement
> getText() traverses the whole tree under the given element and concatenates strings, consider textMatches() instead.
> Replace text equality checks with textMatches

- drivers/sqljs-driver/build.gradle
This fixes #1667 now that the project is using the newest version of the publish plugin.
> Enable sqljs-driver publication

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
Hello! I recently ran into a compiler issue while trying to use `offsets()` queries for an FTS3 table. The fix seemed straightforward, and seems to work for my usage. I wasn't quite sure which tests would be helpful to update, but tried to add a unit test for now. Let me know if there's additional context or testing needed!
**Issue**
SQLDelight supports FTS3/4 tables, but the compiler does not understand the `offsets()` function ([SQLite documentation](https://sqlite.org/fts3.html#offsets)). The result of `offsets()` is a string, which can be parsed as sets of 4 integers. For simplicity, this PR only models the result as a single string, and leaves further parsing up to the caller.
When used in queries where no rows match, the result may return `null`, which is why I chose to mark it …
> Add compiler support for SQLite offsets()

- drivers/android-driver/build.gradle
- drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AndroidDriverTest.kt
- drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AndroidQueryTest.kt
- drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AndroidTransacterTest.kt
- extensions/android-paging/build.gradle
- extensions/android-paging/src/test/java/com/squareup/sqldelight/android/paging/QueryDataSourceFactoryTest.kt
- extensions/android-paging3/build.gradle
- extensions/android-paging3/src/test/java/com/squareup/sqldelight/android/paging3/OffsetQueryPagingSourceTest.kt
- gradle/dependencies.gradle
Per http://robolectric.org/androidx_test, `RuntimeEnvironment.application` has been deprecated and should be replaced with `ApplicationProvider.getApplicationContext()` from the AndroidX Test APIs.
> Replace RuntimeEnvironment.application with ApplicationProvider.getApplicationContext()

- extensions/android-paging3/src/main/java/com/squareup/sqldelight/android/paging3/OffsetQueryPagingSource.kt
- extensions/android-paging3/src/test/java/com/squareup/sqldelight/android/paging3/OffsetQueryPagingSourceTest.kt
I'm just trying out the new AndroidX Paging3 extension and I'm getting an `IndexOutOfBoundsException` when my table is empty (i.e., `countQuery.executeAsOne() == 0`). I'm new to the Paging3 library, but I'd assume that the table being empty shouldn't throw an exception.
> Don't throw exception on empty data in AndroidX Paging3 extension

- .github/workflows/PR.yml
- sqldelight-gradle-plugin/build.gradle
Going off of these issues for ideas of fixing:
https://discuss.gradle.org/t/testkit-how-to-turn-off-daemon/17843
https://discuss.gradle.org/t/travis-ci-org-gradle-launcher-daemon-client-daemondisappearedexception-gradle-build-daemon-disappeared-unexpectedly-it-may-have-been-killed-or-may-have-crashed/13106
> Attempt to tune the jvm size for testkit spawned processes

- .github/workflows/PR.yml
- build.gradle
- gradle/dependencies.gradle
- sqldelight-compiler/build.gradle
- sqldelight-gradle-plugin/build.gradle
- sqldelight-idea-plugin/build.gradle
- sqlite-migrations/build.gradle
well, its back to 50mb but im pretty sure it is a lot bigger than it needs to be. If I just inspect the jar manually its bloated as hell presumably with stuff we dont need.
BUT now the intellij dependency is in a different package, which is good, and our local setup is way more sane since we dont download it every time. So I think this is still the best option. Ideally we follow up by trying to prune more - im not sure how shadow works entirely but it looks like its also shading things like guava so maybe theres a way to avoid shadowing some transitive dependencies and have them show up in the pom...regardless this is a good first step
> Use a shaded jar for intellij

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/tables/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/views/InterfaceGeneration.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightProjectTestCase.kt
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/FixtureCompiler.kt
The Kotlin compiler warns that many of the parameters used in `SqlDelightCompiler` are unused. Removing them will obviously get rid of the warnings, but it would also be less surprising for callers of the functions if they're not passing in values which are ultimately ignored.
> Remove unused parameters

- gradle.properties
As far back as Java 8 the CMSClassUnloadingEnabled option was set true by default, making this flag redundant, while in later versions the CMS GC has been removed along with the CMS command line flags which stops the Gradle daemon from starting on recent Java versions.
> Remove redundant CMSClassUnloadingEnabled flag

- docs/common/multiplatform.md
- sqldelight-gradle-plugin/src/test/integration-multiplatform/settings.gradle
- sqldelight-gradle-plugin/src/test/kotlin-mpp-1.3.20/settings.gradle
- sqldelight-gradle-plugin/src/test/kotlin-mpp-configure-on-demand/settings.gradle
- sqldelight-gradle-plugin/src/test/kotlin-mpp/settings.gradle
- sqldelight-gradle-plugin/src/test/multi-module/settings.gradle
It's a no-op since Gradle 6 and removed in Gradle 7.
The instructions can be removed from the multiplatform docs since it's enabled from Gradle 6 onwards and Gradle 6 is required for MPP since Kotlin 1.4.
> Stop enabling GRADLE_METADATA feature preview

- sqldelight-idea-plugin/build.gradle
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/AddImportIntention.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/Intentions.kt
https://user-images.githubusercontent.com/14963604/114088334-96bad680-98bd-11eb-8408-66f25e0ea7fa.mov
How do I unit test this?
closes #683
> Add import quick fix for unknown type

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedImportInspection.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/lang/SqlDelightImportOptimizer.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedImportInspectionTest.kt
- sqldelight-idea-plugin/testData/inspections/expected.xml
- sqldelight-idea-plugin/testData/inspections/src/AlterTable.sqm
- sqldelight-idea-plugin/testData/inspections/src/CreateTable.sq
https://user-images.githubusercontent.com/14963604/114242319-5ded3100-9993-11eb-90dd-c9e3c5b9ca8b.mov
closes #1161
> Add unused import inspection

- sqldelight-gradle-plugin/build.gradle
It's an expensive operation to do locally every time you want to re-run gradle plugin tests.
> Only create the shadow jar on CI

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightFileIndex.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightPropertiesFile.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/SqlDelightFile.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateMigrationOutputTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/PropertiesImpl.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/VerifyMigrationTask.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TemporaryFixture.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/TestUtil.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/CompilationUnitTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/PropertiesFileTest.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/FileIndex.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFileIndexImpl.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFindUsagesHandlerFactory.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightRenameProcessor.kt
- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightFixtureTestCase.kt
- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/SqlDelightProjectTestCase.kt
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/TestEnvironment.kt
This does not have any behavior change yet in the codegen, every compilation unit still uses the same output directory, so this should pass all tests and still be broken, but it sets up the API to enable using multiple output directories.
> Switch to using an output directory per compilation unit

- docs/multiplatform_sqlite/index.md
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/integrations/IntegrationTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/CompilationUnitTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/PluginTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/PropertiesFileTest.kt
Closes #1039
also unignores that test i made
We could also support target-specific sql but that would require using expect/actual. It also STILL wouldn't enable using test-specific sql which I feel like is a more sought-after feature, so i decided to just disable/document that we only support `commonMain` in KMM modules.
It's possible this breaks some folks builds. It was never really documented that you could do target specific sql, it was also terribly broken because of the output directory clobbering thing, so I don't think anyone was using that feature. If someone was, I would prefer a new issue to track and to give an even more thorough rethink of the dependency/sourceset aspects of sqldelight codegen, but at least this sequence of changes has improved the current state by enabling …
> Properly support android variants, and remove support for KMM target-specific sql

- drivers/jdbc-driver/src/main/kotlin/com/squareup/sqldelight/sqlite/driver/JdbcDriver.kt
> Check that autocommit is set to true before beginning a transaction

- gradle/dependencies.gradle
Minor version bump that makes the native db connection pointer available for configuration on create.
> Sqliter 1.0.1 to make db ptr visible

- drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AndroidTransacterTest.kt
- drivers/native-driver/src/nativeMain/kotlin/com/squareup/sqldelight/drivers/native/NativeSqlDatabase.kt
- runtime/src/commonMain/kotlin/com/squareup/sqldelight/Query.kt
- runtime/src/commonMain/kotlin/com/squareup/sqldelight/Transacter.kt
- runtime/src/commonMain/kotlin/com/squareup/sqldelight/internal/Functions.kt
- runtime/src/jsMain/kotlin/com/squareup/sqldelight/internal/Functions.kt
- runtime/src/jvmMain/kotlin/com/squareup/sqldelight/internal/FunctionsJvm.kt
- runtime/src/nativeMain/kotlin/com/squareup/sqldelight/internal/Functions.kt
Resolves #2235.
Profiling of our production apps shows, that a vast majority of time being spent in write transacitons is in the Kotlin runtime entry point `FreezeSubgraph()`. There are three root contributors to calls into `FreezeSubraph()`:
* The `SharedSet<Listener>` in **every** `Query<T>` created, regardless whether the query is listened to or not.
* The native driver `Transaction` being frozen in `NativeSqliteDriver.newTransaction()`.
* Within the `Transactor.Transaction` base class in sqldelight-runtime, the `SharedSet`s and `SharedMap` used to hold registered callbacks.
What we observe in practice is that:
* The transaction object should never have escaped the thread it is created on, since connections are only temporarily aligned to a thread, and so by extension the transactions …
> Improve native transaction performance by avoiding freezing and shareable data structures when possible.

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/ExecuteQueryGenerator.kt
**Background**
Notify queries do not produce deterministic output. This might break some cache systems if they are depending on the output of `generateDebugDatabaseInterface`
**Changes**
* sort the generated code for notifyQueries function call by the query id (which is gauranteed to be deterministically produced by this prior fix https://github.com/cashapp/sqldelight/pull/1377)
**Test Plan**
* Verify it works locally
> [Sqldelight] Sort `notifyQueries` to have consistent kotlin output file

- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedImportInspection.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/AddImportIntention.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/util/PsiClassSearchHelper.kt
This should fix issues reported by @ursusursus [here](https://github.com/cashapp/sqldelight/pull/2260#issuecomment-828072605), [here](https://github.com/cashapp/sqldelight/pull/2260#issuecomment-828078002), [here](https://github.com/cashapp/sqldelight/pull/2260#issuecomment-828078279) and [here](https://github.com/cashapp/sqldelight/pull/2260#issuecomment-828100519)
> Add nested classes support to import inspection and class annotator

- runtime/src/commonMain/kotlin/com/squareup/sqldelight/db/SqlDriver.kt
- runtime/src/commonTest/kotlin/com/squareup/sqldelight/logs/SqlDriverMigrationCallbackTest.kt
- sqldelight-gradle-plugin/src/test/integration-migration-callbacks/src/test/java/com/squareup/sqldelight/integration/IntegrationTests.kt
Introduced in 1.5.0, SQLDelight had an off-by-one error
for determining when to invoke an `AfterMigration` callback.
This commit corrects the version range for which callbacks
are invoked.
Closes #2393.
> Correct migration callback AfterVersion range filter

- gradle/dependencies.gradle
This just bumps the version of sql.js that is depended upon by the sqljs driver.
Purely coincidental that the latest versions of SQLDelight, Kotlin (ignoring 1.5.10...), and sql.js are all 1.5.0.
> Upgrade sql.js to 1.5.0

- extensions/coroutines-extensions/src/commonMain/kotlin/com/squareup/sqldelight/runtime/coroutines/FlowExtensions.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/com/squareup/sqldelight/runtime/coroutines/QueryAsFlowTest.kt
Avoid a race condition between these events by propagating the initial notification through the same mechanism that the listener uses. With this we can register the listener and then start the notification loop which will immediately trigger having been seeded with an initial notification.
> Ensure we register query listener before notifying

- docs/android_sqlite/index.md
- docs/common/index_gradle_database_pre_dialect.md
- sqldelight-gradle-plugin/src/test/buildscript.gradle
Per the [documentation](https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html#third-party-dependencies):
> Usages of deprecated URL https://jetbrains.bintray.com/intellij-third-party-dependencies must be replaced with https://cache-redirector.jetbrains.com/intellij-dependencies in build scripts.
> Replace deprecated IntelliJ Platform Artifacts Repositories url

- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/queries/SelectQueryTypeTest.kt
- Kotlin 1.5.20 produces a warning when a constructor property type that is an inline class is annotated with `@JvmField`
- Since there is no way to know if the property is an inline class at compile time, `@JvmField` should be removed for now until there's a solution
- if there ever is one
Fixes #2449
> Don't annotate select query class properties with `@JvmField`

- docs/js_sqlite/index.md
- sample/web/webpack.config.d/fs.js
Update docs for the JS driver:
* Use config.resolve to disable fallbacks
* Use latest copy-webpack-plugin API
Add crypto to disabled fallbacks to suppress a warning
> Update docs to reflect Webpack 5 requirements

- build.gradle
- extensions/android-paging/build.gradle
- extensions/android-paging3/build.gradle
- gradle/dependencies.gradle
- sample/android/build.gradle
- sample/build.gradle
- sqldelight-gradle-plugin/src/test/integration-android-library/build.gradle
- sqldelight-gradle-plugin/src/test/integration-android-variants/build.gradle
- sqldelight-gradle-plugin/src/test/integration-android/build.gradle
- sqldelight-gradle-plugin/src/test/integration-multiplatform/android-build.gradle
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/properties/PropertiesFileTest.kt
Per the [release notes](https://developer.android.com/studio/releases/gradle-plugin#4-2-0), AGP now uses Java 8 by default.
> Upgrade Android Gradle Plugin

- sample/build.gradle
The `kotlinx-html-js` version we're using is on Maven Central (https://github.com/cashapp/sqldelight/pull/2478/commits/11b274d0bbfec20e3367eb77930f637b75810ce2) so we can remove the Bintray repository url that was required for previous versions.
> Remove unnecessary Bintray repository url

- build.gradle
- sample/build.gradle
Starting with Kotlin 1.5, the [new default JVM target is 1.8](https://kotlinlang.org/docs/whatsnew15.html#new-default-jvm-target-1-8), so we don't have to explicitly specify it anymore.
> Remove explicit setting of JVM target

- sqldelight-idea-plugin/src/main/resources/liveTemplates/SqlDelight.xml
The default name for an update statement started with "delete" instead of "update".
> Fix update live template

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt
Hello!
this adds ROW_COUNT function to mysql
(ps: is the omission is intentional?
-- I mean, from some discussions, I was wondering if this function was omitted because it shouldn't be called directly
> add row_count function to mysql

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/TypedColumn.kt
- sqldelight-idea-plugin/src/test/kotlin/com/squareup/sqldelight/intellij/inspections/MismatchJoinColumnInspectionTest.kt
- sqldelight-idea-plugin/testData/join-inspections/src/DifferentTypes.sq
> Don't warn with "Join compares two columns of different types" when joining nullable with non-nullable type

- .github/workflows/Publish-Website.yml
Looks similar to my original failing setup here: https://github.com/cashapp/paparazzi/pull/242
So I figure the same problem exists in this repo?
> Update pip requirements path for Github Actions website publishing

- .github/workflows/Release.yml
This fixes the linux publication as the linux targets for x64 were renamed from `linux` to `linuxX64` with https://github.com/cashapp/sqldelight/pull/2548. This updates the deploy workflow to execute `publishLinuxX64PublicationToMavenRepository` rather than the now non existent `publishLinuxPublicationToMavenRepository`.
> Fix linux publication task execution

- .github/workflows/Release.yml
Same issue as there was for linux and was fixed in this PR: #2557 
This fixes the windows publication as the windows targets for x64 were renamed from `mingw` to `mingwX64` with #2548. This updates the deploy workflow to execute `publishMingwX64PublicationToMavenRepository` rather than the now non existent `publishMingwPublicationToMavenRepository`.
> Fix windows publication task execution

- build.gradle
This is similar to https://github.com/square/kotlinpoet/pull/1000 ﻿and makes sure Gradle metadata doesn't require Java11 if the project is built with Java11 (or greater)
> Set Java compatibility to Java8

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/kotlin/SourceRoots.kt
Follow up from https://github.com/cashapp/sqldelight/pull/2518. It turns out that calling `sourceSet.srcDir()` is not enough to have Android Studio pickup the generated folder.
This commit fixes this.﻿
> Fix IDE autocomplete for generated files for Android

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt
See https://github.com/cashapp/sqldelight/issues/2344
Gradle < 7.0 ships with Kotlin 1.3 and has missing `kotlin.jvm.internal.FunctionReferenceImpl`
> Explicitely require Gradle 7.0

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/psi/FunctionExprMixin.kt
The functions currently supported are seemingly random. 
I added the missing increments as per mysql docs https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html
> Add missing functions for time increments

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/test/errors/duplicate-sqlite-identifiers/failure.txt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/ImportTests.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/errors/DuplicateSqlIdentifiers.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/errors/InsertStmtErrors.kt
- sqldelight-compiler/src/test/kotlin/com/squareup/sqldelight/core/errors/SyntaxErrors.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/integrations/VariantTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/FailureTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/MigrationTest.kt
- test-util/src/main/kotlin/com/squareup/sqldelight/test/util/FixtureCompiler.kt
With the new error syntax you can jump to the problematic line by simple clicking the error message in IntelliJ. This is very useful with long `sq` files.
https://user-images.githubusercontent.com/22521688/143685699-c4abef68-415b-41d7-957a-81aaa0bf9709.mov
> Fix error message to allow jumping to error

- docs/common/index_gradle_database.md
Updated getting started documentation with information when using Kotlin for Gradle.
The Getting Started documentation was missing the information on how to get it running, at least I had difficulty getting with it, so for completeness I added the missing information.
> Updated getting started documentation 

- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-idea-plugin/build.gradle
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateInsertIntoQueryAction.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/GenerateSelectAllQueryAction.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/actions/QueryByPrimaryKeyHandler.kt
`ModuleRootManagerImpl` was removed in IntelliJ 2021.2. Usage in SQLDelight was introduced by #1912, though I'm not clear on why it was needed based on a quick look through the SQLDelight codebase and a search within Gradle's codebase. Tests pass without it.
The update to use of `listApplicableTemplates` (also removed in 2021.2) will have no impact, as the old method just passed the parameters directly to the replacement method I've used.
> Verify plugin compatibility on IntelliJ 2021.2

- build.gradle
- extensions/android-paging3/src/test/java/com/squareup/sqldelight/android/paging3/KeyedQueryPagingSourceTest.kt
- extensions/android-paging3/src/test/java/com/squareup/sqldelight/android/paging3/OffsetQueryPagingSourceTest.kt
- gradle/dependencies.gradle
- runtime/src/commonMain/kotlin/app/cash/sqldelight/Transacter.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/main/kotlin/com/squareup/sqldelight/core/lang/IntermediateType.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/assertions/FileSubject.kt
- sqldelight-idea-plugin/build.gradle
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightCopyPasteProcessor.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/SqlDelightFindUsagesHandlerFactory.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedColumnInspection.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/inspections/UnusedImportInspection.kt
- sqldelight-idea-plugin/src/main/kotlin/com/squareup/sqldelight/intellij/intentions/QualifyColumnNameIntention.kt
- sqlite-migrations/src/main/kotlin/com/squareup/sqlite/migrations/DatabaseFilesCollector.kt
Compiling and testing the Idea plugin on Kotlin 1.5 can lead to runtime errors when bundled Kotlin version is used.
IntelliJ 2020.2, the min supported version, bundles 1.3.70, and plugin dependencies in `plugin.xml` can't specify a required minimum version ([IDEABKL-7906](https://youtrack.jetbrains.com/issue/IDEABKL-7906)) so users could be using any Kotlin version from 1.3.70 to the max supported on that platform (1.5.31).
Compilation and test will now be done against the bundled Kotlin version. A few compilation errors that resulted are also fixed.
Also note that runtime dependencies will need to be updated to target API version 1.3 as well - I believe this only impacts sql-psi, see https://github.com/AlecStrong/sql-psi/pull/301.
Possibly fixed (I was seeing red text in IntelliJ in …
> Correct Idea Kotlin plugin dependency

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightQueriesFile.kt
Previously it was iterating over all PsiElements including individual tokens in a file when trying to find more files
> Use faster APIs for iterating files and dont explore the entire PSI graph

- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
Snapshot failed to publish so we need to continue using the old id
> Use the old id for the intellij plugin

- CHANGELOG.md
In the changelog of 1.5.3, there is a missing line compared to the release notes of 1.5.3
> Update 1.5.3 changelog to match 1.5.3 release notes

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt
Useful when using Kotlin DSL and Gradle type safe project accessors and another DB as dependency
```kt
// before
sqldelight {
database("SchemaDB") {
dialect = "postgresql"
packageName = "schema.data"
dependency(projects.dataSchema.dependencyProject)
}
}
// after
sqldelight {
database("SchemaDB") {
dialect = "postgresql"
packageName = "schema.data"
dependency(projects.dataSchema)
}
}
> Add shortcut for Gradle type safe project accessors

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightPlugin.kt
This allows for projects that are other Kotlin project types (and not jvm or multiplatform) to still have the runtime dep automatically added. This also avoids an issue where the jvm dependency would be added if it was just a JS project.
> Explicitly support js/android plugins when adding runtime

- docs/js_sqlite/index.md
- docs/js_sqlite/multiplatform.md
- drivers/sqljs-driver/build.gradle
- sample/README.md
- sample/web/build.gradle
- sample/web/webpack.config.d/resources.js
- sample/web/webpack.config.d/wasm.js
The title is a bit counterintuitive, but here's the problem that this solves:
If you want to add additional SQLite modules (like FTS5) to sql.js you have to recompile it yourself with additional compile flags, which is relatively easy to do. Unfortunately, it is currently not possible to use these custom builds of sql.js with the sqljs-driver. The compiled wasm binary needs to be loaded with the matching JS script generated by Emscripten during that particular compilation, otherwise you can end up with [weird out of memory errors](https://github.com/sql-js/sql.js/issues/201#issuecomment-751487367), or the app simply hanging. In other words, you can't simply copy in the new wasm binary because the sqljs-driver depends on a different build of sql.js which will have an incompatible …
> Remove sql.js dependency from sqljs-driver

- sqldelight-gradle-plugin/src/test/integration-mysql-schema/build.gradle
- sqldelight-gradle-plugin/src/test/integration-mysql/build.gradle
- sqldelight-gradle-plugin/src/test/integration-postgresql/build.gradle
- sqldelight-gradle-plugin/src/test/integration-sqlite-3-24/build.gradle
- sqldelight-gradle-plugin/src/test/multithreaded-sqlite/build.gradle
At least TestContainers `1.16.0` is need to run the integration tests on a M1 Mac.
> Update TestContainer and driver in integrationTests

- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/Group.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/Player.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/SelectNull.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/Team.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamForCoach.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/player/SelectStuff.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/team/SelectStuff.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryInterfaceGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/TableInterfaceGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/tables/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/views/InterfaceGeneration.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/output/com/example/New_test.kt
- sqldelight-compiler/src/test/query-interface-fixtures/query-requires-type/output/com/sample/JoinedWithUsing.kt
- sqldelight-compiler/src/test/table-interface-fixtures/requires-adapter/output/com/sample/Person.kt
- sqldelight-compiler/src/test/view-interface-fixtures/only-table-type/output/com/sample/Person.kt
- sqldelight-compiler/src/test/view-interface-fixtures/requires-adapter/output/com/sample/Person.kt
- sqldelight-compiler/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonAndFriends.kt
- sqldelight-compiler/src/test/view-interface-fixtures/requires-adapter/output/com/sample/PersonCool.kt
The current custom implementation existed only for the reason that historically, an interface and an implementation was generated named `Impl`. This lead to all classes printing their names as Impl.
As this is no longer the case the custom toString is no longer necessary.
I noticed this when I analyzed the generated code and oversaw that an actual data class was generated. The fact that it had a toString implementation made me think that it was not a data class so I was initially googling how to let sqldelight generate data classes - which it already does.
So this PR simplifies that and just uses kotlins built in toString implementation.
> Remove the custom toString generation of generated data classes.

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/GradleCompatibility.kt
This is so that we can do alpha/beta/internal/etc releases and the IDE plugin will continue to work
> Filter out all characters when computing integer versions for the semver

- gradle/libs.versions.toml
Stops us from seeing unnecessary renovate PRs like https://github.com/cashapp/sqldelight/pull/2858.
> Remove unused Guava dependency

- docs/common/gradle-common-groovy-properties.md
Just learned about https://github.com/cashapp/sqldelight/pull/2315. Thought we should mention it in our docs. Thoughts?
> Update gradle docs to mention that a sqlite dialect version is auto picked on android

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/MismatchJoinColumnInspection.kt
A crash here was showing up in the logs if an .sq file was open during a gradle sync, this resolves that case
> Dont attempt to inspect mismatched columns if the project index is not yet initialized

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/ProjectService.kt
- This stops us from competing with the gradle sync for gradle's time,
which appeared to be causing a deadlock.
- Also having the dialect initialized to null means that once the
configuration is loaded, if the dialect is sqlite:3.18 it will
correctly reload and reparse all already open .sq files.
> Dont initialize the file index until a gradle sync has occurred

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/notifications/FileIndexingNotification.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
Closes #2511
Instead of the persistent loading message at the bottom of the IDE there will be a banner in .sq files showing the status of the intellij plugin
> Add an editor banner while SQLDelight is syncing

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/DatabaseGenerator.kt
This fixes remote build cache misses when the files have different outputs based on file system ordering across different OS's.
This is a port of my patch for the 1.5.3 tag, which can be found here: https://github.com/ZacSweers/sqldelight/commit/b45540ac942738972c76d979ddd85fd835a8ba60
Tested the 1.5.3 patch at least and confirmed this fixes things on our side
> Sort files when generating code to ensure idempotent outputs

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
In practice this is only a problem for the IDE during indexing, but still the crashes were annoying
> If a reference cannot be resolves use a blank java type

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/SqlDelightProjectService.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/GradleSystemListener.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/ProjectService.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/notifications/FileIndexingNotification.kt
This beefs up the logic to be more resilient to gradle sync timing / if a gradle sync never needs to happen at all. Found problems with the previous logic where opening a project in intellij would never sync because only android projects force a gradle sync every open. Also realized if the user just manually syncs during a sqldelight import that would also cause issues, so this just ensures no matter when a gradle sync happens we cancel our import.
> Cancel the SQLDelight import if a gradle sync begins

- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/MutatorQueryFunctionTest.kt
HSQL supports named arguments since sql-psi 0.3.16.
> Run named arguments test against HSQL

- drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt
This enables dialects that use the JDBC driver to access JDBC APIs directly instead of needing to convert to one of the SQLite types.
These bindings should be fairly universal amongst JDBC drivers. In cases where they might not be desirable, such as SQLite, they don't need to be used. Each dialect has to opt-in to calling the methods. Date/time types are not included as I believe different drivers have different opinions on using the types from java.time vs java.sql, and the date/time APIs have more variance. This is something that can be improved as we see driver implementation arrive.
#2821 #2128
> Add common types to JdbcDriver

- dialects/sqlite-3-18/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_18/SqliteDialect.kt
- sqldelight-idea-plugin/build.gradle
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/ProjectService.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
The plugin class loader is what gets used for any classes the plugin registers (like the type holder in this example).
I'm getting a little crazy with what I'm doing here, there are actual APIs that exist to add jars to the UrlClassLoader (intellij type), but there aren't any to _remove_ the jars, which makes sense I'm sure thats not happening anywhere at runtime. That said, the ClassPath does have a reset API which I'm calling and the usages of `files` which I reflectively change are all immutable (ie no one has a hard reference on that field that I would need to worry about not getting invalidated). So, hacky, but it works and after trying a bunch of other stuff is the thing I am happiest with.
> Correctly add the dialect jar to the plugin class loader

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/IntermediateType.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightQueriesFile.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
The following results in generated code that doesn't compile. This PR has a failing test that highlights the problem, and I will look into fixing it.
What would be the right place to add a test for something like this?
```
Test.sq
CREATE TABLE Table1(
id TEXT PRIMARY KEY NOT NULL,
status TEXT AS Status NOT NULL
);
CREATE TABLE Table2(
id TEXT PRIMARY KEY NOT NULL,
status TEXT AS Status NOT NULL
);
findAllStatus:
SELECT id, status FROM Table1
UNION ALL
SELECT id, status FROM Table2
ORDER BY id DESC;
```
Results in:
```kotlin
public class TestQueries(
private val driver: SqlDriver,
private val Table1Adapter: Table1.Adapter
) : TransacterImpl(driver) {
public fun <T : Any> findAllStatus(mapper: (status: Status) -> T): Query<T> {
check(setOf(Table1Adapter.statusAdapter, …
```
> Same adapter type from different tables causing a compilation error in 2.0 alpha

- drivers/android-driver/src/main/java/app/cash/sqldelight/driver/android/AndroidSqliteDriver.kt
- drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt
- drivers/native-driver/src/nativeMain/kotlin/app/cash/sqldelight/driver/native/NativeSqlDatabase.kt
- drivers/sqljs-driver/src/main/kotlin/app/cash/sqldelight/driver/sqljs/JsSqlDriver.kt
- runtime/src/commonMain/kotlin/app/cash/sqldelight/db/SqlDriver.kt
- runtime/src/commonMain/kotlin/app/cash/sqldelight/logs/LogSqliteDriver.kt
- runtime/src/commonTest/kotlin/com/squareup/sqldelight/logs/LogSqliteDriverTest.kt
This will be important for throwing when an optimistic lock update fails
> Return the updated row count from the drivers execute method

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/MutatorQueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedMutator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/MutatorQueryTypeTest.kt
Closes https://github.com/cashapp/sqldelight/issues/1018
> Support updating a view which has a INSTEAD OF trigger

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
Closes https://github.com/cashapp/sqldelight/issues/1882
Everything online suggests that JDBC Postgres implementations all coerce NUMERIC types as BigDecimal, so just going with that instead of trying to be too complex
> Support PostgreSQL NUMERIC type

- docs/js_sqlite/index.md
- drivers/sqljs-driver/build.gradle
- drivers/sqljs-driver/karma.config.d/wasm.js
- drivers/sqljs-driver/webpack.config.d/fs.js
- extensions/coroutines-extensions/build.gradle
- extensions/coroutines-extensions/karma.config.d/wasm.js
- extensions/coroutines-extensions/webpack.config.d/fs.js
- sample/kotlin-js-store/yarn.lock
Update test configuration for sqljs-driver and coroutines-extensions
Mocha only runs in node.
Add documentation for using JS driver with Karma
> Use Karma for js browser tests

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/SqliteTypeResolver.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
Closes https://github.com/cashapp/sqldelight/issues/3079
> Ensure updates and deletes with RETURNING statements execute queries

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/Arguments.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
Closes https://github.com/cashapp/sqldelight/issues/2442
> Correctly infer argument types in compound selects

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/SelectQueryable.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
Closes https://github.com/cashapp/sqldelight/issues/2952
> Common tables do not generate data classes so dont return them

- .github/workflows/PR.yml
Closes #3075 
~~Testing things out~~
@AlecStrong @JakeWharton looks like this might not be as useful because of https://youtrack.jetbrains.com/issue/KT-32608
Any thoughts / ideas?
> Test results action

- gradle/libs.versions.toml
- sqldelight-idea-plugin/build.gradle
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/android/SqlDelightRunAnnotator.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/com.squareup.sqldelight-withAndroid.xml
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
Closes https://github.com/cashapp/sqldelight/issues/1778
> Add support for the android studio DB inspector

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/SchemaNeedsMigrationInspection.kt
cc @vanniktech this also was probably causing problems
> Find the top migration file faster

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt
See [here](https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html?from=jetbrains.org#background-processes-and-processcanceledexception)
> All code working with PSI, or in other kinds of background processes, must be prepared for [ProcessCanceledException](https://upsource.jetbrains.com/idea-ce/file/idea-ce-4d741bc560dd19306d4624d7c8a88aea537f4e6f/platform/util/base/src/com/intellij/openapi/progress/ProcessCanceledException.java) being thrown from any point. This exception should never be logged but rethrown, and it'll be handled in the infrastructure that started the process.
> Dont swallow process canceled exceptions

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/DatabaseGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ImportStmtMixin.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/sqldelight.bnf
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightGotoDeclarationHandler.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/SchemaNeedsMigrationInspection.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedImportInspection.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedQueryInspection.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/lang/SqlDelightFileViewProviderFactory.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/refactoring/SqlDelightSuggestedRefactoringExecution.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/util/PsiClassSearchHelper.kt
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/ReferenceContrubutorTest.kt
Apparently there were other places in the compiler doing this too, so this should speed up compilation
> Restrict the full tree search to sql types so i stop shooting myself in the foot

- gradle/wrapper/gradle-wrapper.properties
- sqldelight-gradle-plugin/build.gradle
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/GenerateMigrationOutputTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightWorkerTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/VerifyMigrationTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/kotlin/SourceRoots.kt
See commits for details.
None of these changes will have any user impact.
> Minor cleanups and tweaks to the Gradle plugin

- drivers/native-driver/build.gradle
- extensions/coroutines-extensions/build.gradle
I wanted to compile it on a Linux Fedora distribution, but the compilation ended with an error that the sqlite3 library could not be found. After double-checking that indeed the correct development package is installed and that the correct file is in place on the system, I figured out that the problem is elsewhere.
The problem is that Fedora uses different paths for libraries than Ubuntu, for example, does.
Here is an example of how this can be worked around:
```kotlin
kotlin {
linuxX64("native") {
binaries {
executable {
entryPoint = "me.mira.main"
// A hack for Fedora since Fedora has the libraries under /usr/lib64 compared to other distros
freeCompilerArgs += listOf("-linker-options", "-lsqlite3 -L/usr/lib/x86_64-linux-gnu -L/usr/lib -L/usr/lib64")
}
}
}
...
``` …
> updated paths to the sqlite3 libs

- dialects/mysql/build.gradle
- dialects/postgresql/build.gradle
- dialects/sqlite-3-24/build.gradle
- dialects/sqlite-3-25/build.gradle
- dialects/sqlite-3-30/build.gradle
- dialects/sqlite-3-35/build.gradle
- dialects/sqlite-3-38/build.gradle
- sqldelight-compiler/build.gradle
- sqldelight-idea-plugin/build.gradle
Should fix these warnings:
```
> Task :sqldelight-compiler:compileTestKotlin
Execution optimizations have been disabled for task ':sqldelight-compiler:compileTestKotlin' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/home/runner/work/sqldelight/sqldelight/dialects/mysql/build/libs/mysql-2.1.0-SNAPSHOT.jar'. Reason: Task ':sqldelight-compiler:compileTestKotlin' uses this output of task ':dialects:mysql:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
- Gradle detected a problem …
```
> Declare dependency on shadowJar output to fix missing implicit task dependency

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/DatabaseGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueryWrapperTest.kt
> Skip unused adapters

- sqldelight-idea-plugin/build.gradle
Without this, someone using e.g. Java 17 LTS to run Gradle will run into build failures.
> Force build and run sqldelight-idea-plugin using Java 11

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/VerifyMigrationTask.kt
- sqlite-migrations/src/main/kotlin/app/cash/sqlite/migrations/ObjectDifferDatabaseComparator.kt
Closes https://github.com/cashapp/sqldelight/issues/3115
> Add a flag to ignore schema definitions during migration checks

- drivers/sqljs-driver/src/main/kotlin/app/cash/sqldelight/driver/sqljs/worker/JsWorkerException.kt
- drivers/sqljs-driver/src/main/kotlin/app/cash/sqldelight/driver/sqljs/worker/JsWorkerSqlDriver.kt
- drivers/sqljs-driver/src/main/kotlin/app/cash/sqldelight/driver/sqljs/worker/WorkerMessages.kt
- drivers/sqljs-driver/src/test/kotlin/com/squareup/sqldelight/drivers/sqljs/JsWorkerDriverTest.kt
For some reason the new exception handling test fails when running under the legacy compiler. In actual application builds the exception is thrown normally, but in the legacy tests the exception is completely ignored somehow.
So with the legacy compiler hopefully on the way out in the near future, I think it's best just to skip the legacy version of the test.
> Clean up JS worker exception handling

- sqldelight-gradle-plugin/build.gradle
- sqldelight-gradle-plugin/gradle.properties
Like for the Kotlin Gradle Plugin ([YouTrack comment](https://youtrack.jetbrains.com/issue/KT-41142)), there is no need to expose `kotlin-stdlib` as a runtime dependency as Gradle will provide its own version on the classpath. 
This fixes some `Runtime JAR files in the classpath should have the same version` warnings.
> Do not add kotlin-stdlib as a runtime dependency of the Gradle plugin

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/squash/MigrationSquashTask.kt
VirtualFile.getPath() returns a string with file separator chars replaced with '/', so returning the substring before File.separatorChar on Windows will fail (as it's matching on '\\')
> Set migration directory safely in MigrationSquashTask

- sqldelight-gradle-plugin/build.gradle
- sqldelight-gradle-plugin/src/dockerTest/kotlin/app/cash/sqldelight/dialect/DialectIntegrationTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/dialect/DialectIntegrationTests.kt
There are three tests that fail when Docker isn't installed. I have searched but cannot find an easy to integrate runtime check to see if Docker is installed before running the tests, so I've put the tests behind a flag instead, defaulting to not run.
This makes things easier for casual contributors like myself who don't have Docker installed, but I can understand if this is knocked back.
If there are better solutions for this please provide pointers, thanks!
> Put tests using Docker behind a flag

- drivers/native-driver/src/nativeMain/kotlin/app/cash/sqldelight/driver/native/NativeSqlDatabase.kt
- drivers/native-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/native/NativeDriverTest.kt
- drivers/native-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/native/NativeQueryTest.kt
- drivers/native-driver/src/nativeTest/kotlin/com/squareup/sqldelight/drivers/native/NativeTransacterTest.kt
Native driver modified to support in-memory connections. Added a helper function to create the driver. Not sure if that would be preferred in a companion object, or try to rework the constructor instead.
> In-memory single-connection driver support for native

- gradle.properties
My understanding this would only have been required for two reasons:
1. If publishing using the `maven` plugin - which was removed in Gradle 7, so no longer relevant
2. If external repository being published to does not support the newer checksums - I believe artifacts are only published to Maven Central, JetBrains Marketplace, Gradle Plugin Portal & Sonatype's snapshots repo, which I assume all support these checksums by now.
> Stop publishing with insecure checksums

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/CopyMixin.kt
- dialects/postgresql/src/test/fixtures_postgresql/copy/Sample.s
Old implementation: Error `Multiple columns found with name name`
> Postgres: Fix copy with same name in multiple tables

- kotlin-js-store/yarn.lock
Many Kotlin releases bump JS dependencies needed for a js build (not for the consumers), which results into an updated yarn.lock file during each build.
> Bump automatically generated JS build dependencies

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncSelectQueryTypeTest.kt
This fixes some codegen that was missed in the last async PR.
The overridden `execute` method for `Query` classes shouldn't have a suspend modifier and the execute block should not be awaited in the generated async code.
> Remove suspend and await from `Query<T>.execute()` overrides

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightQueriesFile.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/MutatorQueryTypeTest.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/output/com/example/DataQueries.kt
- sqldelight-gradle-plugin/src/test/adapter-questionmark/build.gradle
- sqldelight-gradle-plugin/src/test/adapter-questionmark/settings.gradle
- sqldelight-gradle-plugin/src/test/adapter-questionmark/src/main/kotlin/foo/M.kt
- sqldelight-gradle-plugin/src/test/adapter-questionmark/src/main/sqldelight/schema/Foo.sq
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/IntegrationTest.kt
Fixes #3233
Rather a hack, but works...
> Fix adapter with question mark only

- drivers/android-driver/src/main/java/app/cash/sqldelight/driver/android/AndroidSqliteDriver.kt
- drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt
- drivers/native-driver/src/nativeMain/kotlin/app/cash/sqldelight/driver/native/NativeSqlDatabase.kt
- drivers/r2dbc-driver/src/main/kotlin/app/cash/sqldelight/driver/r2dbc/R2dbcDriver.kt
- drivers/sqljs-driver/src/main/kotlin/app/cash/sqldelight/driver/sqljs/JsSqlDriver.kt
- drivers/sqljs-driver/src/main/kotlin/app/cash/sqldelight/driver/sqljs/worker/JsWorkerSqlDriver.kt
- drivers/sqljs-driver/src/test/kotlin/com/squareup/sqldelight/drivers/sqljs/JsWorkerTransacterTest.kt
- runtime/src/commonMain/kotlin/app/cash/sqldelight/Transacter.kt
- runtime/src/commonMain/kotlin/app/cash/sqldelight/db/QueryResult.kt
- runtime/src/commonMain/kotlin/app/cash/sqldelight/db/SqlDriver.kt
- runtime/src/commonMain/kotlin/app/cash/sqldelight/logs/LogSqliteDriver.kt
- runtime/src/commonTest/kotlin/com/squareup/sqldelight/logs/LogSqliteDriverTest.kt
- sample/kotlin-js-store/yarn.lock
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/GroupQueries.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/DatabaseGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueriesTypeGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/Constants.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/async/AsyncQueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncSelectQueryTypeTest.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/output/com/example/DataQueries.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/output/com/example/DataQueries.kt
This piggybacks on the new `QueryResult` mechanism to enable transactions to be started and ended asynchronously.
The `Transaction` class and most of the logic is shared between blocking and async transactions, but since the transaction function and block must both be suspending a new set of functions and interfaces needed to be added to enable them.
```kotlin
// blocking
database.transaction { // this: TransactionWithoutReturn
transaction {
// Nested transaction
}
}
// async
database.suspendingTransaction { // this: SuspendingTransactionWithoutReturn
transaction {
// Nested transaction
}
}
```
This also adjusts the codgen to allow grouped statements to use `suspendingTransaction` when generating async code.
> Add support for suspending transactions

- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/TypeResolver.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightFile.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt
- sqldelight-gradle-plugin/src/test/custom-dialect/build.gradle
- sqldelight-gradle-plugin/src/test/custom-dialect/dialect/build.gradle
- sqldelight-gradle-plugin/src/test/custom-dialect/dialect/src/main/kotlin/foo/FooDialect.kt
- sqldelight-gradle-plugin/src/test/custom-dialect/dialect/src/main/resources/META-INF/services/app.cash.sqldelight.dialect.api.SqlDelightDialect
- sqldelight-gradle-plugin/src/test/custom-dialect/settings.gradle
- sqldelight-gradle-plugin/src/test/custom-dialect/src/main/sqldelight/schema/Foo.sq
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/dialect/DialectIntegrationTests.kt
Tried to find a better api for simplifying adding custom functions, but adding `customFunction(functionExpr: SqlFunctionExpr): IntermediateType?` to `TypeResolver` results only into overriding the child `customFunction`, but not the parent one, which is called.
So I only add a test but it could be linked in the docs later (in an advanced section)
> Add test for user defined functions

- dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlDialect.kt
- dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlTypeResolver.kt
- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlDialect.kt
- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlDialect.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/SqliteTypeResolver.kt
- dialects/sqlite-3-38/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_38/SqliteDialect.kt
- drivers/android-driver/src/main/java/app/cash/sqldelight/driver/android/AndroidSqliteDriver.kt
- drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt
- drivers/r2dbc-driver/src/main/kotlin/app/cash/sqldelight/driver/r2dbc/R2dbcDriver.kt
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/RuntimeTypes.kt
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/SqlDelightDialect.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/DatabaseGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueriesTypeGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueryWrapperTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-rename-column/output/com/example/DataQueries.kt
Make Jake happy: https://github.com/cashapp/sqldelight/pull/2672#issuecomment-1016581976
Because delegating works only with interfaces the queries need to take `SqlDriver` instead: https://github.com/cashapp/sqldelight/pull/2918#issuecomment-1153214004
> Revert opening dialect and driver classes, use delegating instead

- docs/common/migrations.md
I think it's not super clean where migration files can be stored. Here's a recent discussion: https://kotlinlang.slack.com/archives/C5HT9AL7Q/p1656067059855929.
> Mention folder directory for migration files in docs

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/IntermediateType.kt
- sqldelight-gradle-plugin/src/test/custom-dialect/dialect/src/main/kotlin/foo/FooDialect.kt
~I don't understand, why it works. I use almost the same code but kotlin poet is unable to resolve the extension function.~
Don't use `CodeBlock.of` without `%L`.
Fixes #3338
> Fixes #3338

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ColumnTypeMixin.kt
Related to #3338
I didn't found more wrong usages of CodeBlock.of :)
> Fix escaping CodeBlock.of("${CodeBlock.toString()}")

- extensions/android-paging3/src/main/java/app/cash/sqldelight/paging3/QueryPagingSource.kt
This is expected, as per the documentation:
https://github.com/cashapp/sqldelight/blob/e4b10641ca83e3f9e15f8d302f7f17db4ce7a1ab/docs/android_sqlite/android_paging.md?plain=1#L95
> Add a default dispatcher to the KeyedQueryPagingSource backed QueryPagingSource function

- docs/android_sqlite/android_paging.md
- extensions/android-paging3/src/main/java/app/cash/sqldelight/paging3/OffsetQueryPagingSource.kt
- extensions/android-paging3/src/main/java/app/cash/sqldelight/paging3/QueryPagingSource.kt
- extensions/android-paging3/src/test/java/app/cash/sqldelight/paging3/OffsetQueryPagingSourceTest.kt
Breaking API change! Maybe it's okay as we're releasing SQLDelight 2 soon…
Previously, we're just upcasting `state.anchorPosition` to a `Long`, which screws things up when we have between `Int.MAX_VALUE` and `Long.MAX_VALUE` items in our pager. This is because, when we refresh the paging source, `getRefreshKey(state: PagingState)` is called, and we'll end up with a very wrong `state.anchorPosition`, as it's no longer the "most recently accessed index in the list", but some truncated form of it. The result of `getRefresKey(…)` will end up being passed to `load(params: LoadParams)` in the form of `params.key`, and bad things will happen as it's not the value we're expecting.
The "fix" is just to force a maximum of `Int.MAX_VALUE` items instead of `Long.MAX_VALUE`. Room does the same thing …
> Make OffsetQueryPagingSource only work with Int

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/test/fixtures_postgresql/custom-functions/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dates.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Fixes https://github.com/AlecStrong/sql-psi/issues/413
> Add NOW() to PostgreSQL

- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlType.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
> `getObject`  method supports automatic filling of the actual type.

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightReferenceContributor.kt
Uses an ugly reflection hack to access the `KotlinTopLevelTypeAliasFqNameIndex` in the newer Kotlin plugin on IDEA 2022.2 / Kotlin 1.7.x.
Fixes #3324
> Fix NoSuchFieldError in newer Kotlin plugins

- gradle/gradle-mvn-push.gradle
Similar to https://github.com/square/wire/blob/master/wire-library/build.gradle.kts#L150-L167.
Thanks @jrodbx for originally writing it, and @oldergod for pointing me to the implementation.
> Simplify creation of internal releases

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt
It is not valid SQL, but SqlDelight supports it.
> Don't allow ABS("foo")

- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/TypeResolver.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/BindArgsTest.kt
- sqldelight-gradle-plugin/src/test/custom-dialect/src/main/sqldelight/schema/Foo.sq
- sqldelight-gradle-plugin/src/test/custom-dialect/src/test/kotlin/Testing.kt
Fixes #3416
It only infers the Kotlin type, if all other parameters of the function have the same type:
`MAX(Int, Int, ARG) = > Arg = Int`.
So `MAX(Int, Text, ARG)` would result into an error, because the type is ambiguous.
> Support inferring kotlin type from other parameters

- .github/workflows/prepare_mkdocs.sh
- .gitignore
- build.gradle
- docs/css/logo-styles.css
- extensions/android-paging3/android-test/build.gradle
- gradle/gradle-mvn-push.gradle
- mkdocs.yml
This upgrades the generated API doc pages for 2.x by using Dokka's HTML format, and also adds links for 2.x throughout the other pages.
The generated pages are customized a bit to make it pretty and easier to navigate back to the main docs.
The 1.x links are still broken, but I'll leave that for a future PR.
> Upgrade API docs and add 2.x API links

- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/IntegrationTest.kt
- sqldelight-gradle-plugin/src/test/selectWithoutFrom/build.gradle
- sqldelight-gradle-plugin/src/test/selectWithoutFrom/settings.gradle
- sqldelight-gradle-plugin/src/test/selectWithoutFrom/src/main/sqldelight/com/sample/MainTable.sq
Fixes #3468 
This also affects other code generation:
Before:
```kotlin
public fun <T : Any> selectNull(mapper: (expr: Void?) -> T): Query<T> = Query(106890351, emptyArray(), driver, "Player.sq", "selectNull", "SELECT NULL") { cursor ->
mapper(
null
)
}
```
Now:
```kotlin
public fun <T : Any> selectNull(mapper: (expr: Void?) -> T): ExecutableQuery<T> = Query(106890351, driver, "Player.sq", "selectNull", "SELECT NULL") { cursor ->
mapper(
null
)
}
```
I don't see a reason to use `Query` with `emptyArray()` as listener, because the listener is an empty array. Now the super class `ExecutableQuery` is used without listener support at all.
> Fix compiler error: missing listener with SELECT without tables

- .github/workflows/Publish-Website.yml
Use the new GitHub Pages Action instead of a (useless) branch, which can be dropped later.
This change requires a config change at Settings -> Pages.
https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/
> Use GitHub Pages Action

- .github/workflows/Release.yml
If you merge two PRs very fast it is possible that the first workflow is slower than the second one. This results in non-consistent releases because the changes from the second later merged PR are not included in the first and the SNAPSHOT release misses these changes.
> Prevent overwriting concurrent releases

- extensions/async-extensions/src/commonMain/kotlin/app/cash/sqldelight/async/coroutines/QueryExtensions.kt
`Query` is the subclass of `ExecutableQuery`, so you can't use these extensions with `ExecutableQuery`.
> Move await* to upper class ExecutableQuery

- drivers/r2dbc-driver/src/main/kotlin/app/cash/sqldelight/driver/r2dbc/R2dbcDriver.kt
The new 1.0.0 release does not send a value when executing a sql statement (eg create a database). Instead, the `Publisher` is finished without a value, thus `awaitSingle` fails. Preparation for https://github.com/cashapp/sqldelight/pull/3375 which will enable the R2DBC tests.
> Adopt R2DBC changes which do not always send a value

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-gradle-plugin/src/test/derive-schema-no-queries/build.gradle
- sqldelight-gradle-plugin/src/test/derive-schema-no-queries/settings.gradle
- sqldelight-gradle-plugin/src/test/derive-schema-no-queries/src/main/sqldelight/app/cash/sqldelight/1.sqm
- sqldelight-gradle-plugin/src/test/derive-schema-no-queries/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/IntegrationTest.kt
> Always create the database implementation

- extensions/coroutines-extensions/src/commonMain/kotlin/app/cash/sqldelight/coroutines/FlowExtensions.kt
- extensions/coroutines-extensions/src/commonTest/kotlin/app/cash/sqldelight/coroutines/QueryAsFlowTest.kt
Would rather be verbose and safe than introduce the default dispatcher unknowingly in situations where it would cause issues
> Remove default params to flow extensions

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/TableInterfaceGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/integration/JavadocText.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/dialects/DialectTypes.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/JavadocTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
> Relax javaDoc and add it to custom mapper function too

- CHANGELOG.md
Mention the breaking changes from here: https://github.com/cashapp/sqldelight/pull/3322/files
> Changelog: Dialect and Driver classes are final.

- drivers/android-driver/build.gradle
- drivers/android-driver/src/main/AndroidManifest.xml
- sample/android/build.gradle
- sample/android/src/main/AndroidManifest.xml
> Migrate to AGP namespaces

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/MutatorQueryTypeTest.kt
If a single variable with an array type is used in multiple queries inside the same transaction the compiler generates multiple `val ${name}Indexes = createArguments(count = ${name}.size)` lines (one for each query).
This PR adds a test for the behaviour and a simple fix to prevent all but the first generation. The fix tries to reuse the code from commit cc524c70 which fixed the behaviour when using only a single query.
Running "./gradlew sqldelight-compiler:build" did not change any file under version control. I assume the change on the codegen did not affect any existing integration tests.
> Fix duplicate generation of ${name}Indexes variables when using transactions

- drivers/android-driver/src/main/java/app/cash/sqldelight/driver/android/AndroidSqliteDriver.kt
- drivers/android-driver/src/test/java/com/squareup/sqldelight/android/AndroidDriverTest.kt
Fixes #3571
`androidx.sqlite.db.SupportSQLiteOpenHelper.Callback` is a class, so delegation does not work.
> Make the Callback open again

- docs/multiplatform_sqlite/resources.md
The current link https://gh.jdoneill.com/2020/06/28/sqldelight/ 404's
The correct link is https://gh.jdoneill.com/2020/06/29/sqldelight/
> docs: fix 404 link to jdoneill.com article

- .gitattributes
GitHub doesn't add syntax highlighting for `.sq` and `.sqm` files.
Add `.gitattributes` instructions to add `SQL` syntax to these files. As seen in https://github.com/github/linguist/blob/master/docs/overrides.md.
Works for `.sq` and `.sqm` files, both when browsing code or when reviewing diffs.
Compare browsing a `.sq` or `.sqm` file on [cashapp/sqldelight](https://github.com/cashapp/sqldelight/blob/master/sample/common/src/commonMain/sqldelight/com/example/sqldelight/hockey/data/Player.sq) VS on [vitorhugods/sqldelight](https://github.com/vitorhugods/sqldelight/blob/master/sample/common/src/commonMain/sqldelight/com/example/sqldelight/hockey/data/Player.sq).
----
> chore: enable GitHub SQL highlight for .sq files

- docs/css/app.css
- mkdocs.yml
Adds a light/dark mode toggle to the docs
Live example: https://asemy.github.io/sqldelight/
Documentation here: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
Example config here: https://github.com/squidfunk/mkdocs-material/blob/2569d4f0884b9fe3be934215ce0cfddf8efc94b8/mkdocs.yml#L60-L72
> mkdocs: add light/dark mode toggle

- .github/workflows/Renovate.yml
- .github/workflows/requirements.txt
mkdocs currently requires a version of Markdown that is <3.4.
This also adds an action to check renovate upgrades on the requirements.txt
> Downgrade Markdown to 3.3.7

- build.gradle
- sample/build.gradle
https://classic.yarnpkg.com/lang/en/docs/cli/#toc-concurrency-and-mutex
> When running multiple instances of yarn as the same user on the same server, you can ensure only one instance runs at any given time (and avoid conflicts) by passing the global flag --mutex followed by file or network.
See https://github.com/cashapp/sqldelight/pull/3700#issuecomment-1327775716
> Ensure single instance of yarn runs at once

- .github/workflows/Publish-Website.yml
- renovate.json
Follow-up for #3793 to prevent Renovate from updating the compiled requirements (`pip-compile` output) independently. (Sorry again. I should've caught this initially.)
> Configure Renovate to ignore compiled pip dependencies

- drivers/r2dbc-driver/src/main/kotlin/app/cash/sqldelight/driver/r2dbc/R2dbcDriver.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql-async/src/test/kotlin/app/cash/sqldelight/postgresql/integration/async/PostgreSqlTest.kt
The JDBC driver exposes the connection, so the r2dbc driver should do this too.
Use-case: Use the copy api from postgres: https://github.com/pgjdbc/r2dbc-postgresql/blob/87a058ec52006e83746ecb07e85b82b972b35402/src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java#L230
To compare:
https://github.com/cashapp/sqldelight/blob/master/drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt
> R2DB2 Driver: Expose the connection

- drivers/r2dbc-driver/src/main/kotlin/app/cash/sqldelight/driver/r2dbc/R2dbcDriver.kt
- gradle/libs.versions.toml
- sqldelight-gradle-plugin/src/test/integration-mysql-async/build.gradle
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/test/kotlin/app/cash/sqldelight/mysql/integration/async/MySqlTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql-async/build.gradle
I replaced the MySQL driver with the [MariaDB driver](https://github.com/mariadb-corporation/mariadb-connector-r2dbc), because the development of the MySQL one looks stopped: https://github.com/mirromutth/r2dbc-mysql
> Support R2DBC 1.0

- renovate.json
Fixes a slight configuration error introduced in e2a9d627b8a74bc227340ae4600d67e2368d8341. Renovate does not validate the constraint and, thus, deems the configuration valid. However, this leads to failure further down the road for some dependency updates (see #3816).
(I suggested a potential documentation fix upstream https://github.com/renovatebot/renovate/pull/19855 to stop others from running into this.)
> Use a PEP440 compliant Python version constraint for Renovate

- drivers/r2dbc-driver/src/main/kotlin/app/cash/sqldelight/driver/r2dbc/R2dbcDriver.kt
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/main/sqldelight/app/cash/sqldelight/mysql/integration/async/Dog.sq
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/test/kotlin/app/cash/sqldelight/mysql/integration/async/MySqlTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql-async/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/async/Dog.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql-async/src/test/kotlin/app/cash/sqldelight/postgresql/integration/async/PostgreSqlTest.kt
R2DBC requires boxed primitives, otherwise, the driver cannot encode a null value.
> R2DBC: Fix primitive null values in bindStatement

- docs/common/gradle-common-groovy-properties.md
The configuration from the docs gives this error on Gradle 8:
```
* What went wrong:
A problem was found with the configuration of task ':foo:generateCommonMainBlob2DatabaseInterface' (type 'SqlDelightTask').
- Gradle detected a problem with the following location: 'foo/src/commonMain/sqldelight/blob2'.
Reason: Task ':foo:generateCommonMainBlob2DatabaseInterface' uses this output of task ':foo:generateCommonMainBlob2DatabaseSchema' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```
That's because the input to the codegen task is the whole directory, including the generated schema db (even if not used). Moving it to a sibling directory fixed the issue.
> [1.5 branch] documentation: do not output schema next to .db files

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/DatabaseGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueryWrapperTest.kt
PRAGMA statements defined in migrations, such as switching to WAL mode for SQLite, or toggling foreign keys, are executed as part of the migrate(SqlDriver, Int, Int) function, but are not executed as part of create(SqlDriver). They should be executed as part of both.
I suspect there may be a better way/location to write this test, and am happy to change it as requested.
> Include PRAGMAs from migrations in database create(SqlDriver)

- gradle/libs.versions.toml
- sqldelight-compiler/dialect/build.gradle
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/PragmaWithResults.kt
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/SelectQueryable.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/ParserUtil.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightQueriesFile.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ColumnTypeMixin.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/Arguments.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/validation/OptimisticLockValidator.kt
Use-case:
Implement  `QueryWithResults` defined in `dialect` module in the DB2 dialect but I also need to create SelectQueryable
```kotlin
override fun queryWithResults(sqlStmt: SqlStmt): QueryWithResults? {
val ext = sqlStmt.extensionStmt
if (ext != null) {
val set = (ext as Db2ExtensionStmt).setStmt
set.compoundSelectStmtInternal?.let { SelectQueryable(it) }
return Db2SetQueryWithResults(set)
}
val compoundSelectStmt = sqlStmt.compoundSelectStmt
return if (compoundSelectStmt is Db2CompoundSelectMixin) {
return compoundSelectStmt.queryWithResults()
} else parentResolver.queryWithResults(sqlStmt)
}
```
> Move SelectQueryable to Dialect module

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/test/fixtures_postgresql/uuids/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Uuids.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Adds support for [gen_random_uuid()](https://www.postgresql.org/docs/current/functions-uuid.html) postgres function, which comes out of the box since v13
I'm unable to run the build on my local (m1 mac) so I haven't been able to test it. Is there a way to build on m1 mac?
> add support and test for gen_random_uuid()

- sqldelight-gradle-plugin/build.gradle
- sqldelight-gradle-plugin/src/grammarkitTest/kotlin/app/cash/sqldelight/GrammarkitDialectIntegrationTests.kt
- sqldelight-gradle-plugin/src/test/buildscript.gradle
- sqldelight-gradle-plugin/src/test/settings.gradle
Instead, specify the version explicitly. For example, using `+` does not work when adding the snapshot repo because there is a 2.1.0-SNAPSHOT version.
> Don't use + as sqldelight version in tests

- drivers/web-worker-driver/src/main/kotlin/app/cash/sqldelight/driver/worker/WebWorkerDriver.kt
Code gen and api use `SqlCursor`
> Don't expose JsWorkerSqlCursor

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/sqlite-3-35/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_35/SqliteTypeResolver.kt
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/FlattenCompounded.kt
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/ReturningQueryable.kt
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/SelectQueryable.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/PgInsertReturningTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dog.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
- sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/src/main/sqldelight/app/cash/sqldelight/integration/Person.sq
- sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt
This fixes a bug in the codegen of RETURNING clauses for Postgres and SQLite INSERT statements.
Previously, the generated code did not compile if multiple, but not all, columns of the table were returned.
The same bug likely exists for UPDATE and DELETE, but I didn't check or try to fix those.
> Fix codegen for RETURNING clause

- gradle/wrapper/gradle-wrapper.properties
- sample/gradle/wrapper/gradle-wrapper.properties
Unblocks #3857 while we wait for Gradle 8.0 compatibility (#3879).
> Upgrade to Gradle 7.6.1

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightExtension.kt
Just a few small things I thought I'd toss up for consideration
- Add `@SqlDelightDsl` DSL marker. This prevents accidentally nesting multiple sqldelight DSL calls.
- Use `project.objects` for initializing properties with conventions, allowing `SqlDelightDatabase` to avoid "accessing non-final property in constructor" warnings.
- Use `detachedConfiguration()`, which is functionally achieving the same as before but a first-party API from gradle for accomplishing the same thing (i.e. plugin-internal configurations).
> Small Gradle plugin QoL improvements

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightClassNameElementAnnotator.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightReferenceContributor.kt
> Fix unresolved kotlin types

- sqldelight-gradle-plugin/src/test/integration-sqlite-3-24/build.gradle
- sqldelight-gradle-plugin/src/test/integration-sqlite-3-35/build.gradle
- sqldelight-gradle-plugin/src/test/multithreaded-sqlite/build.gradle
Fixes #3915 - Deleted two of the `org.xerial:sqlite-jdbc` dependency entries that were duplicates (version catalog entries already existed), and moved the dependency in `multithreaded-sqlite` to use the version catalog entry instead.
> Fixes #3915 - Move test dependencies for SQLite-JDBC to version catalog

- drivers/web-worker-driver/src/main/kotlin/app/cash/sqldelight/driver/worker/WebWorkerDriver.kt
Fixed bytes in WebWorkerDriver being converted from ByteArray to Array<Byte> (toTypedArray()) which translates to Array of numbers instead of Int8Array in JS and therefore cannot be read by sqlite-wasm.
> Fixed bytes in WebWorkerDriver being converted from ByteArray to Array<Byte>

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/ProjectService.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightTreeStructureProvider.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
https://user-images.githubusercontent.com/14963604/227230899-e9bf9b89-506d-493a-b512-95dc662432b4.mov
closes #40
> Compact middle packages in project tree

- sqldelight-compiler/integration-tests/src/test/kotlin/app/cash/sqldelight/core/integration/IntegrationTest.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/GroupQueries.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/SelectFromTable2.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/testmodule/TestDatabaseImpl.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SqlDelightCompiler.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/model/NamedQuery.kt
Closes #4001
You can still query/insert them, they just wont have table-specific types for them.
This enables using virtual tables with incompatible modules / columns that are never used from kotlin
> Dont generate types for virtual tables

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightColumnRenameProcessor.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightFindUsagesHandlerFactory.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/inspections/UnusedQueryInspection.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/FindUsagesTest.kt
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/SqlDelightColumnRenameProcessorTest.kt
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/SqlDelightFixtureTestCase.kt
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/SqlDelightIdentifierHandlerTest.kt
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/inspections/UnusedQueryInspectionTest.kt
- sqldelight-idea-plugin/testData/find-usages/Example.kt
- sqldelight-idea-plugin/testData/find-usages/Example.sq
- sqldelight-idea-plugin/testData/find-usages/ExampleQueries.kt
- sqldelight-idea-plugin/testData/find-usages/Main.kt
- sqldelight-idea-plugin/testData/find-usages/MainAfter.kt
- sqldelight-idea-plugin/testData/find-usages/Query.kt
- sqldelight-idea-plugin/testData/unused-query-inspection/expected.xml
- sqldelight-idea-plugin/testData/unused-query-inspection/src/SomeTable.sq
- sqldelight-idea-plugin/testData/unused-query-inspection/src/main/kotlin/com/example/Main.kt
[Screencast from 30.03.2023 21:13:33.webm](https://user-images.githubusercontent.com/14963604/228927949-383f3dfb-2123-4ae6-a428-91a0ce406488.webm)
and find usages
[Screencast from 30.03.2023 21:14:53.webm](https://user-images.githubusercontent.com/14963604/228928105-b5b77a4e-0338-437a-85f9-f10d052b0cce.webm)
closes #2077
> Rename named argument and parameter usage on column rename

- docs/multiplatform_sqlite/index.md
Had a great day. everything in life is going so well 
woke up today and chose to build a multiplatform app. 
while copy-pasting the code from docs for the sqldelight setup in my multiplatform project
suddenly my brain was trying to figure out why the code from the docs is giving error.
Ah, the missing variable type.  
I'd let others have a great day with this PR.
> driverFactory variable in docs missing the type of the variable.

- runtime/src/commonMain/kotlin/app/cash/sqldelight/db/QueryResult.kt
Kotlin 1.8 lifted the restriction on generic value classes.
In almost all cases, these classes will still be boxed anyway since the return types of any relevant methods will be the `QueryResult` interface. We _could_ narrow the return types on specific driver implementations, and the Kotlin compiler can statically dispatch method calls to those specialized driver types and keep these classes inlined, but it's not generally applicable.
> Make `QueryResult` implementations value classes

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/lang/completion/SqlDelightKeywordCompletionContributor.kt
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/lang/completion/SqlDelightKeywordCompletionContributorTest.kt
https://user-images.githubusercontent.com/14963604/233858840-e91e5404-3796-4a50-a3cb-e48bdfdf5dd5.mov
> Add join clause completion

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/intentions/CreateViewIntention.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
- sqldelight-idea-plugin/src/main/resources/intentionDescriptions/CreateViewIntention/description.html
- sqldelight-idea-plugin/src/main/resources/liveTemplates/SqlDelight.xml
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/intentions/CreateViewIntentionTest.kt
https://user-images.githubusercontent.com/14963604/232889511-4ace3fdc-e82a-4362-9327-fe9ec4b791d4.mov
> Create view intention and live template

- .github/workflows/PR.yml
- .github/workflows/Publish-Website.yml
- .github/workflows/Release.yml
Don't execute all tests in the gradle-plugin again during instrumentation, we already test them on linux.
Idea: Put all tests requiring a real device into instrumentationTest and remove the existing `Instrumentation` annotation.
> CI: Clean Gradle home before uploading caches & cache dokkaHtml

- drivers/sqljs-driver/build.gradle
Deleting the driver altogether will take some more work since it's really baked into the coroutines and paging tests, but this will unblock a release candidate.
See #4094
> Disable publication of the sqljs driver

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/test/fixtures_postgresql/alter-table-add-constraint/1.s
Minimal support for Postgres alter table add constraint as learning how all this works.
``` sql 
ALTER TABLE test
ADD CONSTRAINT idx_external_event_id
UNIQUE (external_event_id);
```
The changes are made here on sqldelight as the postgressql grammer was moved from sql-psi
Noticed that issue was raised in https://github.com/AlecStrong/sql-psi/issues/286
*Have signed contributors agreement.*
---
TODOs
Check constraints - there needs to be support for type `expr` functions like `char_length`
e.g
``` sql
ALTER TABLE distributors ADD CONSTRAINT zipchk CHECK (char_length(zipcode) = 5);
```
> Alter table add constraint postgres

- .github/workflows/PR.yml
- buildLogic/toolchain-convention/build.gradle
- buildLogic/toolchain-convention/src/main/kotlin/app/cash/sqldelight/toolchain/ToolchainConventions.kt
AGP 8 (#4059) requires JDK 17 to run, but some integration tests are running with JDK 11 from the toolchain settings.
This sets the toolchain version to 17 for all projects, and configures the source/target compatibility to be 8 or 11 instead.
> Split toolchain versions and JDK target versions

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/test/fixtures_postgresql/column_types/Sample.s
close #4122
* Add PostgreSql specific grammar
* Update fixture test
This brings the PostgreSql grammar to similar level of MySql support for Interval
Provides grammar for:
``` sql
some_interval_a INTERVAL DEFAULT INTERVAL '5 days',
some_interval_b TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP - INTERVAL '5 days',
some_interval_c TIMESTAMP NOT NULL DEFAULT NOW() - INTERVAL '5 days',
some_interval_d INTERVAL DEFAULT INTERVAL '3h' + INTERVAL '20m'
```
Note:- Does not support
arithmetic e.g INTERVAL ’1 day’ * 7
“::interval” short-hand
“5 days” validation of literals
Modifiers e.g INTERVAL ‘5’ DAY
Other examples of Interval expressions that could be supported
https://github.com/postgres/postgres/blob/master/src/test/regress/sql/interval.sql
> Add postgreSql column default interval

- drivers/r2dbc-driver/src/main/kotlin/app/cash/sqldelight/driver/r2dbc/R2dbcDriver.kt
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/test/kotlin/app/cash/sqldelight/mysql/integration/async/MySqlTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql-async/src/test/kotlin/app/cash/sqldelight/postgresql/integration/async/PostgreSqlTest.kt
The current `close` api of the R2DBC driver does not await the result or failure of the close request. Because we can't use a suspend call, I added a normal plain old callback.
> R2DBC: Await closing the driver

- .github/workflows/Publish-Website.yml
`mike` builds the docs on its own but the environment variable with the version wasn't set on those steps. This also means we can leave out a redundant build of the docs in an earlier step.
> Fix automatic version text in docs

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/LiteralValueMixin.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/BindArgsTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dates.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
closes #4144  Look into approach for supporting INTERVAL literal column results
`SELECT INTERVAL '1 day';`
Override Literals, test returns `PGInterval` type.
TODOs
Literals for CURRENT_DATE, CURRENT_TIME, CURRENT_DATE_TIME should also be considered.
Support `SELECT NOW() + INTERVAL '1 day';`
> Add postgreSql interval column result

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/test/fixtures_postgresql/custom-functions/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dates.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Fixes https://github.com/AlecStrong/sql-psi/issues/427
I didn't implement `EXTRACT` because its syntax is somehow complex and `date_part` is also available.
> PostgreSQL: Add date_part

- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/MySql.bnf
- dialects/mysql/src/test/fixtures_mysql/insert-on-duplicate-key/Test.s
There appears to be a grammar error with mysql dialect. This PR fixes it.
e.g. It is not possible to have query expression like below. 
```
...
ON DUPLICATE KEY UPDATE
col = col + 1;
```
> Updating mysql grammar to support additional expressions for 'on duplicate update'.

- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlMigrationSquasher.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/squash/AnsiSqlMigrationSquasher.kt
`Overwritten method has a different parameter name.`
> Remove some compiler warnings

- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt
- sqldelight-gradle-plugin/src/test/integration-mysql/src/main/sqldelight/app/cash/sqldelight/mysql/integration/Numbers.sq
- sqldelight-gradle-plugin/src/test/integration-mysql/src/test/kotlin/app/cash/sqldelight/mysql/integration/MySqlTest.kt
Simple binary expressions like `bigint*bigint` did not work.
`sum(bigint)` previously returned REAL, while in reality it returns INTEGER except when REAL is passed in
Added tests for min/max while I was here
> MySQL: support mysql types for binary expr and sum

- sqldelight-gradle-plugin/src/instrumentationTest/kotlin/app/cash/sqldelight/integrations/IntegrationTest.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/test/integration-android-variants/build.gradle
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/properties/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/properties/PropertiesFileTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/CompilationUnitTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/MigrationTest.kt
Always include the variant name as part of output path
Closes #4267
> Use stable output path for generated source

- drivers/web-worker-driver/build.gradle
- drivers/web-worker-driver/sqljs/build.gradle
I don't know why any of this is necessary, but that's just how the Dokka plugin is.
> Fix dokka build failure

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/GenerateMigrationOutputTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightPlugin.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/VerifyMigrationTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/kotlin/SourceRoots.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/squash/MigrationSquashTask.kt
Some Gradle plugin tweaks that can hopefully make it into 2.0 RC2.
> Gradle tweaks

- extensions/androidx-paging3/src/commonMain/kotlin/app/cash/sqldelight/paging3/KeyedQueryPagingSource.kt
- extensions/androidx-paging3/src/commonMain/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSource.kt
- extensions/androidx-paging3/src/commonMain/kotlin/app/cash/sqldelight/paging3/QueryPagingSource.kt
- extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/KeyedQueryPagingSourceTest.kt
- extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSourceTest.kt
Fixes #4291
The QueryPagingSource API is extended not only to support a blocking Transacter, but a more generic TransacterBase which includes SuspendingTransacter.
The solution is rather crude, but I think it's better than copying two large blocks of code which only differ by one line.
> Add support for SuspendingTransacter in QueryPagingSource

- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/grammar/MySql.bnf
- dialects/mysql/src/test/fixtures_mysql/number-types/Number.s
MySQL 8 deprecates int display width
> MySQL: support unsigned ints without display width

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/kotlin/LinkSqlite.kt
We should not expose this internal function to our public Gradle plugin api. Users should use the sqldelight extension.
> Gradle plugin: Don't expose linkSqlite

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncSelectQueryTypeTest.kt
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/main/sqldelight/app/cash/sqldelight/mysql/integration/async/Dog.sq
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/test/kotlin/app/cash/sqldelight/mysql/integration/async/MySqlTest.kt
> Fix result expression for grouped statements

- sqldelight-compiler/integration-tests/src/test/kotlin/app/cash/sqldelight/core/integration/IntegrationTest.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/Arguments.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
Supports https://github.com/AlecStrong/sql-psi/pull/411
> Support multi-column-expr when doing a SELECT

- .github/workflows/PR.yml
Instead of just building every artifact, we should just let each job build the artifacts it needs as part of each step.
This may also help to cut down our cache footprint, which is way over Github's limit (we're likely dropping caches as we create new ones, which is not helping our cache hit rate!)
> Do not run assemble task et al. in jobs

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/create-index/Sample.s
PostgreSql extension allows [Create Index Concurrently](https://www.postgresql.org/docs/current/sql-createindex.html)
Copy inherited `create_index_stmt` with new rule added
Add fixture test
fixes #4531
> Add PostgreSql Create Index Concurrently

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/SqlDeleteStmtLimitedMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/SqlInsertStmtMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/UpdateStmtLimitedMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/cte-multiple-auxiliary-statements/Sample.s
This is implemented in PostgreSql Dialect as PostgreSQL allows CTEs to contain INSERT/UPDATE/DELETE statements. 
Add an override `SqlInsertStmtMixin` , `SqlDeleteStmtLimitedMixin` , `UpdateStmtLimitedMixin`
Add test fixtures 
closes #4441
> Fix 4441 PostgreSql Dialect auxilary CTE

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/AlterTableRenameColumnMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/alter-table-rename-column/1.s
🌵 `SqlColumnAlias` element doesn't implement `SqlColumnName` but is added to table columns for querying later. 
After the columns were modified during a rename the element was not found on subsequent query of `SqlColumnName` types.
Now, implementing as `SqlColumnName` it takes the first child element of the pair of `SqlColumnName` types representing the `a` to `b` rename.
fixes #3916
> Fix 3916 PostgreSql rename column

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Numbers.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Based off this PR https://github.com/cashapp/sqldelight/pull/4254 but in Postgres
> Postgres Dialect: Support proper types for binary expr and sum

- drivers/sqlite-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/sqlite/JdbcSqliteDriver.kt
The type is AutoCloseable and we should close it. Failing to do so leaks the PreparedStatement.
> Close temporary PreparedStatement in Sqlite JDBC Driver

- .github/workflows/PR.yml
The 'test' job is really short, while the 'gradle-plugin-test' job is really long (the longest). This should help balance things out a little more.
> Move sample build to 'test' job

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/DistinctOnExpressionMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/select-distinct-on/Test.s
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/select-distinct-on/failure.txt
Initial grammar and fixture test
Mixin for Distinct On columns
Annotate Distinct On using the basic rule "The DISTINCT ON column(s) must match the leftmost ORDER BY column(s)" see https://github.com/cockroachdb/cockroach/blob/b994d025c678f495cb8b93044e35a8c59595bd78/pkg/sql/opt/optbuilder/distinct.go#L91. This should catch at compile time, instead of runtime where columns are not matching.
fixes #4580
> Fix 4580 Add PostgreSql Select Distinct On

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Json.sq
It's not unreasonable for someone to use these functions in a SELECT, so we should have return types for them.
This does not cover any of the functions that return "setof", as those would essentially be a virtual table.
> Add Postgres JSON function definitions

- .github/workflows/PR.yml
- .github/workflows/Publish-Website.yml
- .github/workflows/Release.yml
- gradle.properties
Fixes #4646 
Moves the `org.gradle.jvmargs` back to `gradle.properties`, from CI workflows
> Fix `OutOfMemory` build error

- drivers/driver-test/src/commonMain/kotlin/com/squareup/sqldelight/driver/test/EphemeralTest.kt
- drivers/sqlite-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/sqlite/JdbcSqliteDriver.kt
- drivers/sqlite-driver/src/test/kotlin/com/squareup/sqldelight/driver/sqlite/SqliteEphemeralTest.kt
Fixes #4018 
This PR fixes a an issue when choosing which type of `ConnectionManager` should be utilized, depending on what parameters are passed via url where a static connection is needed to be maintained.
> Fix `JdbcSqliteDriver` url parsing when choosing `ConnectionManager` type

- docs/common/migrations.md
This matches what the docs say and wires things up automatically for anyone who doesn't use the check task directly.
> ... a new `verifySqlDelightMigration` task will be added to the gradle project, and it will run as part of the `test` task ...
https://cashapp.github.io/sqldelight/2.0.0/multiplatform_sqlite/migrations/#verifying-migrations
> Make gradle `test` run verifyMigrationTask instead of `check`

- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/gradle/FileIndexMap.kt
fixes #4686 
🧪 Have tested locally with snapshot IDEA plugin against reproducibles (Spring Boot Plugin + JAVA_HOME JDK 11) 
getAvailableJdk() checks for project JDK first, then for the most recent JDK version and finally the internal JDK that could be JAVA_HOME
Explicit fallback to JAVA_HOME may not be needed as getAvailableJdk() appears to do this anyway
> Fix 4686 Use IDEA Project JDK first

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Functions.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Adds `generate_series` PostgreSql function 
Adds integration test
This is simpler than adding support for generate_series as a table source.
```sql
SELECT generate_series(
CAST('2023-09-01T00:00:00Z' AS TIMESTAMPTZ),
CAST('2023-09-02T00:00:00Z' AS TIMESTAMPTZ),
CAST('1 hour' AS INTERVAL)
);
```
closes #4616
> Fix 4616 generate series for PostgreSql

- docs/android_sqlite/testing.md
The old syntax produces this error:
```groovy
GroovyRuntimeException: Cannot set the value of read-only property 'force' for DefaultExternalModuleDependency{group='org.xerial', name='sqlite-jdbc', version='3.32.2', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
```
> Use gradle's new syntax for locking a dependency's version

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
It's not unreasonable for someone to use these functions in a SELECT, so we should have return types for them.
> Add additional Postgres String function definitions

- drivers/native-driver/build.gradle
- extensions/coroutines-extensions/build.gradle
- runtime/build.gradle
#4788 bumped sqliter to 1.3.0 which includes linuxArm64 support. This PR enables this target.
Also closes https://github.com/cashapp/sqldelight/issues/4257
> Native-driver: add support for linuxArm64

- buildLogic/toolchain-convention/src/main/kotlin/app/cash/sqldelight/toolchain/BugsnagKey.kt
- buildLogic/toolchain-convention/src/main/kotlin/app/cash/sqldelight/toolchain/PluginVersion.kt
- sqldelight-compiler/build.gradle
- sqldelight-idea-plugin/build.gradle
With these changes we can run `assemble` with the config cache. We can't run `build` because Dokka does not support the CC and we run Dokka for the integration tests indirectly by calling publish local directory.
Open question: Do you want to set the Gradle property `org.gradle.configuration-cache=true` or do you prefer local opt-in without committing?
> Refactor build logic to support configuration cache

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dates.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
This change adds the possibility to use the `max` and `min` functions in PostgreSQL for the DATE data type.
> Add DATE PostgreSQL type to min and max aggregate functions

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/Arguments.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/BindArgsTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/BinaryArguments.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #4504
🤾  This PR is just to try out and see if any quick fixes 
Try and lookup the parent `SqlColumnExpr` to get the type of the column
Only the parent column can tell us what the type actually is declared as e.g Instant
Currently the tests pass and local snapshot works with cases
```
import java.time.Instant;
CREATE TABLE session (
id UUID PRIMARY KEY,
created_at TIMESTAMP AS Instant NOT NULL,
updated_at TIMESTAMP AS Instant NOT NULL
);
selectSession1:
SELECT *
FROM session
WHERE created_at = :createdAt - INTERVAL '2 days' OR updated_at = :updatedAt + INTERVAL '2 days';
selectSession2:
SELECT *
FROM session
WHERE created_at BETWEEN :createdAt - INTERVAL '2 days' AND :createdAt + INTERVAL '2 days';
```
📓 The user will be required to implement and provide a ColumnAdapter for Instant …
> Bind arguments with SqlBinaryExpr

- docs/index.md
Where does the icon came from? Found it: https://simpleicons.org/
> Add link to Oracle dialect

- sample/android/src/main/java/com/example/sqldelight/hockey/data/GetInstance.kt
The receiver parameter is never used, removes unnecessary qualifier names in `Db.getInstance()`
> Removes redundant qualifier names in GetInstance.kt

- sample/common/src/iosTest/kotlin/com/example/sqldelight/hockey/BaseTest.kt
jvmCommon uses an in-memory database, but iosCommon uses an on-disk database. This PR makes iosCommon to use in-memory database.
I was creating my project based on the sample, and I faced an issue: changing schema led to failures in IosSchemaTest. This PR fixes that.
> Makes sample/common/iosTest base test setup to use in memory DB

- drivers/android-driver/src/main/java/app/cash/sqldelight/driver/android/AndroidSqliteDriver.kt
Android has the concept of a cursor window, where a query will try to preemptively load data up to a certain size (by default [2MB](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/config.xml#2369)). However if individual rows are too big to fit that size, a `SQLiteBlobTooBigException` will be thrown.
A few issues where this happens:
- https://github.com/cashapp/sqldelight/issues/1584
- https://github.com/cashapp/sqldelight/issues/1627
- https://github.com/cashapp/sqldelight/issues/1862
- https://github.com/apollographql/apollo-kotlin/issues/4072
More context about CursorWindow in [this blog post](https://medium.com/androiddevelopers/large-database-queries-on-android-cb043ae626e8).
Since Android 28+ this can be mitigated by controlling the window …
> Add a windowSizeBytes parameter to AndroidSqliteDriver

- dialects/hsql/src/main/kotlin/app/cash/sqldelight/dialects/hsql/HsqlTypeResolver.kt
- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/MySqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/TypeResolver.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/ExprUtil.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/ExpressionTest.kt
- For preferKotlinType in the homogeneous types case, the first type is selected
- For a function like coalesce that's not correct since any non null arg makes the return not nullable
- The previous behavior is maintained by making the nullability parameter null (which is the default)
Fixes #4870
> Allow overriding the type nullability in encapsulatingType

- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/ReturningQueryable.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/migrations/MigrationQueryTest.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/varying-query-migration-packages/com/example/migrations/1.sqm
- sqldelight-compiler/src/test/migration-interface-fixtures/varying-query-migration-packages/com/example/queries/Data.sq
- sqldelight-compiler/src/test/migration-interface-fixtures/varying-query-migration-packages/output/com/example/migrations/Test.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/varying-query-migration-packages/output/com/example/queries/DataQueries.kt
fixes #4448 
🦑 This is for both Sqlite and Postgresql dialects that support `RETURNING *`
`app.cash.sqldelight.dialect.api.ReturningQueryable` now returns the parent table reference instead of the statement table reference to use the correct package name that is taken from the source file
`SelectQueryable` works already
e.g the `CREATE TABLE Test ... ` is contained in `com\example\migration\1.sqm`
`INSERT INTO Test()...RETURNING*` is contained in `com\example\queries\Data.sq`
The generated `DataQueries` must contain `import com.example.migration.Test`
The other migration fixtures assume that `sqm` and `sq` are co-located in same directory and thus work.
> Fix 4448 missing import for table model

- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/migrations/MigrationQueryTest.kt
Have seen an improvement to be made in MigrationQueryTest, where a test passed but was a "false positive" 🔋 
⚠️ A test can succeed even if there is a compiler error.
👮 Ensure test fails when there is a compiler error and show errors.
For example -
* an invalid column in Data.sq must show the error "Data.sq: (6, 58): No column found with name x"
* an insert query missing a non default value "Data.sq: (5, 0): Cannot populate default value for column x, it must be specified in insert statement."
> Update MigrationQueryTest.kt to show compiler error

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/column_types/Sample.s
fixes #4932 - compiler error when functions are used as `DEFAULT` column values 
😑 Currently the work-around/escape-hatch is to enclose the function in parentheses as this matches the grammar rule`LP expr RP`
Add `{function_expr}` to the `default_constraint` rule
Other consideration is that ideally the function result type must be assignable to the column type 🔡 🔢 and would need to be compiler checked - currently none of the `DEFAULT` types are checked and can be any type of expression 🤭 
```
CREATE TABLE t1(
c1 UUID DEFAULT gen_random_uuid(),
c2 INTEGER DEFAULT nextval('some_seq')
);
```
---
💡 Ideally - SqlDelight would provide error
```
CREATE TABLE t1(
c1 INTEGER DEFAULT gen_random_uuid()
);
```
Postgresql does provide error
`error: column "c1" is of type integer but default expression …
> Fixes 4932 postgresql default constraint functions

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/AlterTableAlterColumnMixin.kt
🆙  More updates to improve Postgresql migration support
* Adds override to annotate the compiler message for missing column name
* Remove some redundant variables
* Issue where Queries was using `old` column name if had been previously renamed  😖 
Support several migrations - individually or as a group
Check if `nullableColumn` exists to use the `nullableColumn` value
Check if a `SqlColumnType` exists to use the alter column `SqlColumn`
```
ALTER TABLE test ALTER COLUMN x SET NOT NULL; -- change nullability, set the nullable property on the QueryColumn element
ALTER TABLE test ALTER COLUMN x TYPE BIGINT; -- change column type, set the element property to columnName
ALTER TABLE test ALTER COLUMN x DROP IDENTITY; -- no changes, keep current element and nullable properties
```
Additional …
> Update Postgresql AlterTableAlterColumnMixin

- sqldelight-idea-plugin/build.gradle
Our PR builds are failing due to the instrumentation runners running out of disk space. I think downloading four IDEA versions could be a contributor?
We could consider splitting these tests into a test matrix that runs the tests against one (or two) intelliJ version(s) per runner so that we don't use up a ton of disk space just to run these tests.
> Drop Flamingo tests and reduce number of tested IDEA versions

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/AlterTableAddConstraintMixin.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/migrations/MigrationQueryTest.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-add-constraint/com/example/1.sqm
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-add-constraint/com/example/2.sqm
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-add-constraint/com/example/Data.sq
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-add-constraint/output/com/example/DataQueries.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-add-constraint/output/com/example/TestCompound.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-add-constraint/output/com/example/TestSingle.kt
Fixes #5018 
🧑‍🍳 🧇  Adds a mixin to the grammar to handle nullable types when adding a  `PRIMARY KEY` with `ALTER TABLE`.
PostgreSql Primary Key columns are NOT NULL 
AlterTableAddConstraintMixin
This takes a lazyQuery as input, checks if the table constraint is a primary key, updates matching columns to not nullable, and returns a new lazyQuery with the transformed columns. This has the effect of propagating primary key nullability constraints to the columns when altering the table.
New `MigrationQueryTest` added
tested locally with https://github.com/griffio/sqldelight-postgres-01
> Fixes 5018 PostgreSql add Primary Key not nullable types

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
It's not unreasonable for someone to use these functions in a SELECT, so we should have return types for them.
> Add Postgres Regex function definitions

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightWorkerTask.kt
Closes https://github.com/cashapp/sqldelight/issues/4414
We found that the intermittent errors reported in the issue linked above happen when multiple `generateDatabaseInterface` tasks are run in parallel. Specifically, when reading intellij registry properties from a file, the input stream could be closed by another gradle worker running at the same time. This seems like a good use case for process isolation (https://docs.gradle.org/current/userguide/worker_api.html#creating_a_worker_daemon). Changing to process isolation solves the intermittent failures for our builds.
> Use process isolation for gradle workers

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/AggregateExpressionMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/aggregate-expressions/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Dog.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
🚧 🍔 
fixes #4703 
Supports `string_agg` - function requires a `separator` argument with optional `ORDER BY`
See fixture tests for variations
``` sql
SELECT articles.id, slug, title, description,
COALESCE (string_agg (DISTINCT tag, ',' ORDER BY tag DESC) 
FILTER (WHERE tag IS NOT NULL)) AS articleTags
FROM articles
LEFT JOIN tags ON articles.id = tags.article_id
JOIN users ON articles.author_id = users.id
GROUP BY articles.id, users.id;
```
Keep existing function `string_agg` for the simple use and new grammar for complex cases
Supports `array_agg` and single parameter use-case. Returns `kotlin.Array<T>`
``` sql
SELECT breed,
array_agg(DISTINCT name ORDER BY name DESC) FILTER (WHERE is_good = 1)
FROM dog
GROUP BY breed
ORDER BY breed;
```
Adds Integration tests
* Including Array types in …
> Fixes 4703 aggregate expressions

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- drivers/jdbc-driver/src/main/kotlin/app/cash/sqldelight/driver/jdbc/JdbcDriver.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Json.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5028
🚧 🍔 👷 
With JDBC, setObject...Types.OTHER can be used to bind a String to a JSON type
Add new binding method* in JdbcDriver
Keep the `jsonDataType` as a String for reading and writing
Add JSON type for setObject...Types.OTHER binding to write as a String. Read a result String as normal
Add Docker Integration tests (none were being run for json with PostgresDialect)
*This may come in useful for other types like TSVector
> Fixes 5028 PostgreSql json

- gradle/libs.versions.toml
Technically, we don't need to increase the minSDK, but the Play Store requires 21 since August 2023 and Jetpack Compose requires 21 too. So I don't see a reason to keep this low level. 
Any thoughts?
[(Theoretically with api 21 the min sqlite version increased from 3.7 to 3.8 but this has no real effect for us because there is no <3.7 dialect.)](https://developer.android.com/reference/android/database/sqlite/package-summary)
See also https://apilevels.com
> Increase Android minSDK to 21

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/JsonExpressionMixin.kt
- dialects/postgresql/src/test/kotlin/app/cash/sqldelight/dialects/postgres/PostgreSqlFixturesTest.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/json_functions/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Json.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5040 
🚧 🍔 based on branch `griffio:fix-5028-postgresql-json` as requires JSON type
Adds Json Path operator to grammar
Adds jsonExpression to return JSON type in resolver
Adds Integration Tests - json functions
Note: `?` '?|' `?&' operators require the Sql statement to use an additional ?` see https://jdbc.postgresql.org/documentation/query/#using-the-statement-or-preparedstatement-interface
`||`, `-` JSON type used with existing operators
Fix json functions to allow Json type binding with `setObjectOther`
> Fixes 5040 PostgreSql json operators

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/JsonExpressionMixin.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Json.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
📟  Follow up from PR https://github.com/cashapp/sqldelight/pull/5041
Added the binary operator expressions support
Added Integration tests for binary operator binding
e.g 
```sql
SELECT *
FROM TestJson
WHERE datab @> ?;
```
👐  This required making the json expression use a column expression with the json operator so that a sql expression is evaluated
> Fixes json operator binding for 5040

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/MatchOperatorExpressionMixin.kt
- dialects/postgresql/src/test/kotlin/app/cash/sqldelight/dialects/postgres/PostgreSqlFixturesTest.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/json_functions/Test.s
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/text-search-functions/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/TextSearch.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5082
Added `TSVECTOR` type and updated `@@` match operator to work with `JSONB` and `TSVECTOR`
Added several text search functions for now  - as there are many more functions that could be added to a custom dialect for advanced uses.
Added integration tests
🧪 Tested snapshot with local project https://github.com/griffio/sqldelight-postgres-textsearch
> Fixes 5082 tsvector

- sqldelight-gradle-plugin/src/test/schema-output/build.gradle
Follow up to #5117 
---
The `migrationOutputDirectory` configuration in the gradle plugin's build file is using `Project.getBuildDir()`, which was [deprecated in Gradle 8.3](https://github.com/gradle/gradle/issues/20210).
This PR updates that to use the recommended `ProjectLayout.getBuildDirectory()` method instead. Note: `getBuildDirectory()` was introduced in Gradle 4.1.
> Update deprecated usage of Project.getBuildDir() in gradle plugin build file

- .github/workflows/PR.yml
- dialects/hsql/build.gradle
- dialects/mysql/build.gradle
- dialects/postgresql/build.gradle
- dialects/sqlite-3-18/build.gradle
- dialects/sqlite-3-24/build.gradle
- dialects/sqlite-3-25/build.gradle
- dialects/sqlite-3-30/build.gradle
- dialects/sqlite-3-33/build.gradle
- dialects/sqlite-3-35/build.gradle
- dialects/sqlite-3-38/build.gradle
- dialects/sqlite/json-module/build.gradle
- gradle/libs.versions.toml
- sqldelight-compiler/environment/build.gradle
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/MigrationParserDefinition.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightParserDefinition.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/psi/ColumnTypeMixin.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/validation/OptimisticLockValidator.kt
- sqldelight-gradle-plugin/build.gradle
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/core/annotators/OptimisticLockCompilerAnnotator.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightLiveTemplateContextType.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightReferenceContributor.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightTreeStructureProvider.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/intentions/AddOptimisticLockIntention.kt
- sqldelight-idea-plugin/src/main/resources/META-INF/plugin.xml
- sqldelight-idea-plugin/src/test/kotlin/app/cash/sqldelight/intellij/FindUsagesTest.kt
- test-util/build.gradle
- test-util/src/main/kotlin/app/cash/sqldelight/test/util/TestEnvironment.kt
> Bump intellij version

- dialects/sqlite-3-18/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_18/SqliteDialect.kt
> Use the extensions array instead of stream

- sample-web/settings.gradle
- sample/settings.gradle
- settings.gradle
Otherwise we get this warning due the changed api.
```
WARNING: Error invoking build scan publishingCondition action
Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.lang.reflect.InvocationHandler.invoke(Object, java.lang.reflect.Method, Object[])" is null
```
> Fix local Gradle execution without a BuildScan

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/CreateIndexMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/create-index/Sample.s
fixes #5059
* Updated `CREATE INDEX` to support operator classes e.g `jsonb_path_ops`, storage parameters e.g `gin_pending_list_limit` and index methods for `BRIN`, `BTREE`,  `GIN`, `GIST`, `HASH`
* Added integration tests for index methods and storage parameters
There are many op classes and it may not be possible to validate them, extra ones are added by extensions, and the data types they support
The optional WITH clause specifies storage parameters for the index. Each index method has its own set of allowed storage parameters.  https://www.postgresql.org/docs/16/sql-createindex.html#SQL-CREATEINDEX-STORAGE-PARAMETERS
Index storage parameters **are** possible to validate, along with the arguments
```
'autosummarize' | 'buffering' | 'deduplicate_items' | 'fastupdate' | 'fillfactor' | …
```
> Fixes 5059 add brin gist

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/RegExMatchOperatorExpressionMixin.kt
- dialects/postgresql/src/test/kotlin/app/cash/sqldelight/dialects/postgres/PostgreSqlFixturesTest.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/regex-match-ops/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/RegExOps.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5137 
POSIX regular expressions provide a more powerful means for pattern matching than the LIKE and SIMILAR TO operators.
GiST and GIN index operator classes that allow you to create an index over a text column for the purpose of very fast similarity searches. These index types support similarity operators, and additionally support trigram-based index searches for LIKE, ILIKE, ~, ~*
* Added regex operators in grammar
```
text ~ text → boolean
text ~* text → boolean
text !~ text → boolean
text !~* text → boolean
```
* Added integration tests
```sql
CREATE TABLE regexops(
t TEXT NOT NULL
);
insert:
INSERT INTO regexops (t) VALUES (?);
matchRegExOps:
SELECT concat(t, 'test') ~ ?, t ~* ?, t !~ ?, t !~* ?
FROM regexops;
matchRegExWhere:
SELECT t
FROM regexops
WHERE t ~ ?;
```
> Add 5137 PostgreSql Regex operators

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/select-distinct/Test.s
fixes #5172 
For some reason the additional optional [ distinct_on_expr ] causes the SELECT not to match DISTINCT.
Removed as it seems to work with `distinct_on_expr` or optionally distinct/all
There appears not to be any tests for `SELECT DISTINCT` - if so it would have found the regression 👿 
* Updated Grammar
* Added fixture tests
> Fix 5172 PostgreSql select distinct

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
fixes #5173 
Previously in 2.0.0 `IS NOT NULL`, `IS NULL` worked but stopped working after changes to `SqlExpr.postgreSqlType()`
The Sql expression `SqlIsExpr` was incorrectly being matched to `SqlBinaryExpr` (as it implements `SqlBinaryExpr`). The parent Ansi type resolver never gets called as it would handle any `SqlIsExpr` elements.
* Create an explicit `SqlIsExpr` when clause and return Boolean
* Add Interface table tests as the compiled type must be generated as Boolean
* Add in some missing types to `SqlBinaryExpr` - though this isn't needed for this issue
> Fix 5173 PostgreSql isNull isNotNull types

- runtime/src/commonMain/kotlin/app/cash/sqldelight/Transacter.kt
The capacity of `StringBuilder` was calculated wrongly leading to unnecessary reallocations.
> Fix StringBuilder capacity

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/WindowDefinitionMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/window_functions/Test.s
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Functions.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/WindowFunctions.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5155 
🚧 Initial implementation was tried from hsql 😖 That doesn't appear to work though as no way to resolve to an `expr`
Current approach is to use `function_expr` so the `expr` resolves to a `IntermediateType`, then define additional functions `rank`, `row_number` etc and still able to use existing `sum`, `avg` etc
- Adds Windows Functions to PostgreSqlTypeResolver https://www.postgresql.org/docs/15/functions-window.html 
- Adds test for interface table generation has correct columns
- Adds integration tests of various window functions
- Not supported is validating clause `FILTER (WHERE ... )` when `FILTER is not implemented for non-aggregate window functions` and other validations https://github.com/postgres/postgres/blob/b29cbd3da4e37db17026b9fe58fb46fe83f467bf/src/backend/parse …
> Fix 5155 PostgreSql window functions

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/order-by-nulls/Sample.s
fixes #5199
* Added override `ordering_term` grammar for PostgreSql  https://www.postgresql.org/docs/current/queries-order.html
* Added fixture test
Other `ORDER BY` rules in grammar use `ordering_term`
> Add 5199 support postgresql order by nulls

- docs/common/gradle.md
The gradle docs for `generateAsync` should state `for use` instead of `for us`. Thanks!
> Fix typo in generateAsync description

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncMutatorQueryTypeTest.kt
fixes #5313 
Uses [`app.cash.sqldelight.dialects.postgresql.grammar.mixins.BindParameterMixin`](https://github.com/cashapp/sqldelight/blob/6a8142b6fbbdd81874285114de4ffe3fbd43003f/dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/BindParameterMixin.kt#L8) to set correct bind parameter `$index` or `?`
Added test for generated code show correct indexed parameters are encoded
> Fix 5313 Postgresql async bind parameter

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/xml-type/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Xml.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5331 
https://www.postgresql.org/docs/16/datatype-xml.html
```
CREATE TABLE Test(
x XML
);
insert:
INSERT INTO Test(x) VALUES ('<simple>test</simple>');
insertX:
INSERT INTO Test(x) VALUES (?);
```
```
sample.xQueries.insertX("<a>test</a>")
```
* Added `XML` data type works with String input and output
*  type is supported for insert (binds to SQLXML) and select (String)
*  none of the functions are supported https://www.postgresql.org/docs/16/functions-xml.html
* Added integration test
Note: 
Support for "::xml" type casting is already in another pr https://github.com/cashapp/sqldelight/pull/5261
> Fix 5331 add PostgreSql XML type

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/like-operators/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Like.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5330 
https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE
* Added `ILIKE` operator - extended existing rule even though it has Sqlite operators GLOB, MATCH, REGEX, 
* Added Regex
* operator `~~` is equivalent to LIKE, and `~~*` corresponds to ILIKE. There are also `!~~` and `!~~*` operators 
that represent NOT LIKE and NOT ILIKE
* Added integration test
> Fix 5330 add Postgresql ILIKE operator

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/alter-table-drop-constraint/1.s
fixes #5288 
* Added grammar `DROP CONSTRAINT [ IF EXISTS ]  constraint_name [ RESTRICT | CASCADE ]`
* moved higher in precedence as `DROP COLUMN` conflicts     
* Added fixture test
Note: Currently there is no way, at compile time, to verify that a named check constraints exist
> Fix 5288 adds PostgreSql drop constraint

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/DistinctOnExpressionMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/select-distinct-on/Test.s
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/select-distinct-on/failure.txt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/DistinctOn.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #5345
Update DistinctOnExpressionMixin to expose tables (if prefix present) or use previous code that exposes columns
- When exposing tables there could be DISTINCT ON columns with the same table prefix then remove duplicate tables
Update fixture test to include queries with multiple tables and columns
Add Integration test to validate compiled queries and prevent regressions
> Fix 5345 PostgreSql  SELECT DISTINCT ON

- docs/jvm_sqlite/index.md
- docs/multiplatform_sqlite/index.md
The JVM code samples do not use the `PRAGMA user_version`-based migration logic, which is a bit misleading because samples for other platforms do.
The inconsistency is particularly visible in the Multiplatform case, where the android and native samples will set `user_version=1`, but the JVM sample will produce `user_version=0`, resulting in some headaches down the road.
> Make JVM samples consistent with other platforms

- dialects/sqlite/json-module/src/main/kotlin/app/cash/sqldelight/dialects/sqlite/json/module/grammar/json.bnf
- dialects/sqlite/json-module/src/main/kotlin/app/cash/sqldelight/dialects/sqlite/json/module/grammar/mixins/TableOrSubqueryMixin.kt
- dialects/sqlite/json-module/src/testFixtures/resources/fixtures_sqlite_json/json_table_functions/Test.s
- sqldelight-gradle-plugin/src/test/integration-sqlite-json/src/main/sqldelight/app/cash/sqldelight/integration/JsonTable.sq
fixes #5372 
* Add grammar for alias
* Update mixin to use table alias if available
* Add fixture test
* Update integration test to include use of alias
> fix 5372 add alias to json table function

- sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/test/integration-android-variants/build.gradle
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/integrations/IntegrationTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/properties/MultiModuleTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/properties/PropertiesFileTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/CompilationUnitTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/com/squareup/sqldelight/tests/MigrationTest.kt
Backports a fix from #4269 to the `1.5.3` branch.
> Backport stable output path fix from (#4269) to 1.5.x

- sqldelight-gradle-plugin/src/grammarkitTest/kotlin/app/cash/sqldelight/GrammarkitDialectIntegrationTests.kt
- sqldelight-gradle-plugin/src/instrumentationTest/kotlin/app/cash/sqldelight/WithCommonConfiguration.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/WithCommonConfiguration.kt
Reduces the amount of disk space needed to run tests by sharing installs/caches
Part of why our CI runs are failing right now is because we're running out of disk space. The gradle test kit directory eats up a lot of space and a separate one is created for each test suite.
> Share gradle test kit directory between test suites

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
fixes #5399 
After https://github.com/cashapp/sqldelight/issues/1882 there are some functions and expression that can use `NUMERIC`
and need to compile to `BIGDECIMAL` in the query interface
* Add `NUMERIC` to resolver functions/expressions 
* Add Interface tests to check generation
> Fix 5399 PostgreSql numeric resolver

- .github/workflows/PR.yml
These tasks are run when we publish library artifacts to the local repository for our Gradle test kit tests and sample builds, but we don't actually use this documentation for anything and it just takes up a bunch of time.
> Skip dokkaHtml task in PR tests

- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/GradleVersionsTest.kt
Test against the minimum and current versions of gradle (that SQLDelight was built against)
This slightly reduces the amount of stuff we need to download (by a few hundred MB)
> Reduce the number of gradle versions we check

- .github/workflows/PR.yml
The old versions take 40 GB, but deleting them is incredibly slow: 3-4 minutes.
> Remove unused Xcode installations to free some space

- docs/common/gradle.md
Add an explanation of what the linkSqlite option does. Add a discussion of alternative options for properly linking sqlite when compiling a static framework.
> docs: explain the Gradle linkSqlite option

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/core/SqlDelightEnvironment.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/VariantTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/FailureTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/MigrationTest.kt
You can click on it from the Terminal but it does not get the correct line/offset.
I don't know how many times I've clicked on it and always landing on the very first line. The formatting is also consistent now with the Kotlin Compiler:
> Compiler: Improve error message such that path links are clickable with the correct line & char position.

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/json_functions/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Json.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
🚧 💔 Fix some of the existing JSON functions that use table/alias references. Currently broken.
e.g returns json representation of row tuples or value
```sql
SELECT row_to_json(myTable) FROM myTable;
SELECT json_agg(myTable) FROM myTable;
SELECT to_json(myTable) FROM myTable;
SELECT to_jsonb(myTable.t) FROM myTable;
SELECT to_jsonb('Hello World'::text);
WITH myTable_cte AS (
SELECT t FROM myTable
)
SELECT row_to_json(myTable_cte) FROM myTable_cte;
```
* Add a rule `json_function_stmt` to match table/aliases on functions
* functions like `to_json` use either a column or table  - the function resolver will stay the same
* Add fixture tests
* Add integration test
TODO - create an issue for this PR
> Fix Postgresql to_json

- extensions/androidx-paging3/src/commonMain/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSource.kt
- extensions/androidx-paging3/src/commonTest/kotlin/app/cash/sqldelight/paging3/OffsetQueryPagingSourceTest.kt
If items are removed then the initial key for a refresh may be close enough to the end of the list that fewer than a screens-worth of items may be loaded causing the UI to jump. Changed to handle similarly to the case where the initial key larger than count and load loadSize items from the end.
> paging refresh initial load fix

- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/SqlDelightFile.kt
Issue when looking into SqlDelightModules for potential use with PostgreSql Extensions - noticed that the typeResolver order is incorrect when loading a module `DialectTypeResolver -> ModuleTypeResolver -> AnsiTypeResolver` .
Currently it worked for Sqlite JsonModule as only added functions and not any types 
Fix returns the typeResolver and parent resolver(s) composed of either:
`DialectTypeResolver -> AnsiTypeResolver` - no SqlDelightModule
`ModuleTypeResolver -> DialectTypeResolver -> AnsiTypeResolver` - with SqlDelightModule
This ensures that the Module TypeResolver methods are called first and can delegate to the dialect parent resolver for any inherited types and then the Ansi Resolver
> Fix SqlDelightModule type resolver order

- gradle.properties
This replaces the custom name with an SPDX identifier to enable tooling to automatically detect the correct license. Using an SPDX identifier is recommended [by the official Maven documentation](https://maven.apache.org/pom.html#Licenses).
See https://spdx.org/licenses/Apache-2.0.html
> Use SPDX identifier in POMs

- docs/common/migrations.md
A project of mine is using `commonMain` and has a custom DB name, so the given docs are wrong at the moment:
> Clarify docs for generating schemas via gradle

- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/ExecuteQueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/QueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncSelectQueryTypeTest.kt
Fixes:
- #4975 
- #3743
- #4618
- #5001 
-----
By modifying the `QueryGenerator` to make sure all child classes have access to `tablesUpdated()`, and centralising the query notification into the `executeBlock` function, make sure the following is added to the generated code of grouped statements.
```kotlin
} .also {
notifyQueries(queryId) { emit ->
// emit table names
}
}
```
I am not completely sure of this approach and I'd love some feedback before I dedicate more time into it.
Annoying space before `.also {`. I'll learn a bit more of Kotlinpoet :)
- What's the importance of the Query ID? I noticed in some tests it is hardcoded, in some it figures it out from the compiler. I can modify the `notifyQueriesBlock()` to accept the QueryId and make it match one of the statements.
I am not …
> Notify queries when executing group statements with result

- runtime/build.gradle
- runtime/src/commonMain/kotlin/app/cash/sqldelight/logs/LogSqliteDriver.kt
- runtime/src/commonTest/kotlin/com/squareup/sqldelight/logs/LogAsyncSqliteDriverTest.kt
If sqlDriver.newTransaction returns a QueryResult.AsyncValue, QueryResult.value throws an exception.
> Fix crash in LogSqliteDriver when real driver is Async

- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/GenerateSchemaTask.kt
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/VerifyMigrationTask.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/GenerateSchemaTest.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/tests/MigrationTest.kt
- sqldelight-gradle-plugin/src/test/migration-driver-initializer/build.gradle
- sqldelight-gradle-plugin/src/test/migration-driver-initializer/driverInit/build.gradle.kts
- sqldelight-gradle-plugin/src/test/migration-driver-initializer/driverInit/src/main/kotlin/DriverInitializerImpl.kt
This PR extends the work done for the VerifyMigrationTask in https://github.com/sqldelight/sqldelight/pull/3986 to the `GenerateSchemaTask`.
I [added a test](https://github.com/sqldelight/sqldelight/commit/4670689a8825d52b0b0012e8d9596a53a7c160c8), and also [expanded](https://github.com/sqldelight/sqldelight/commit/8ae0a8d67f63df7c283fba85b177ebcdd3c60362) the existing test added in the previous PR to actually test for our use case which is using a custom driver to connect to the sqlite db during these tasks.
> Execute `DriverInitializer` before `GenerateSchemaTask`

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/ContainsOperatorExpressionMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/OverlapsOperatorExpressionMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/RangeOperatorExpressionMixin.kt
- dialects/postgresql/src/test/kotlin/app/cash/sqldelight/dialects/postgres/PostgreSqlFixturesTest.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/ts-ranges/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/TemporalRanges.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Add some support for TS Range type https://www.postgresql.org/docs/16/rangetypes.html
#RANGETYPES-EXAMPLES
Types are mapped to string representations as there is no client side data type such as a range that is compatible (Kotlin ranges only implement open/closed on upper bounds). This is consistent with JSON, TSVECTOR, INTERVAL types and uses OTHER type to bind the literal value for INSERTS and String for results (Ideally there would be a type mapping for the PostgreSql JDBC driver to use the PgObject type, however only `PostgreSqlType` is available to map types for both Jdbc/R2dbc ).
Note: Bind parameters for ranges must be cast e.g.
```sql
SELECT ?::tstzmultirange - range_agg(slot) AS availability …
```
> Add PostgreSql TSRANGE/TSTZRANGE support

- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/TableFunctionColumnAliasMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/TableFunctionNameMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/TableFunctionTableAliasMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/TableOrSubqueryMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/unnest/Test.s
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/TableFunctionRowType.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Unnest.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
Support `Unnest` Function - expand an array to a set of rows
fixes #5346 
🪹 🏗️ Work
🚧 🪺 In Progress  
* Add "unnest" to PostgreSql.bnf
* Add mixins to help with column resolving as there are new aliases used by "unnest" in `FROM`
* Update PostresqResolver to handle converting Array<T> to T - this was not supported by IntermediateType
* Add TableFunctionRowType to allow new concept of nested type to row type - not an actual table
* Add fixture and integration tests
Prototype use project https://github.com/griffio/sqldelight-postgres-unnest
* PostgreSQL allows a function (e.g unnest) to be written directly as a member of the FROM list. Allows multiple arrays to be unnested
* SELECT unnest() allows a single array to be unnested
Examples:
Allows  "Array DML" - e.g bulk inserts, updates and …
> Support PostgreSql UnNest Array to rows 

- docs/index.md
Supposedly if someone wants snapshot they want the latest, v2.0+.
> Point to the new snapshot coordinates in docs

- dialects/sqlite-3-25/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_25/SqliteTypeResolver.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/ExpressionTest.kt
fixes #5758
Adds call super to resolve inherited functions from 3.18
Adds suitable test to prevent regressions from any future Sqlite dialects
Tested local snapshot with change
Fixture tests don't fail when functions are not resolved in queries - it returns null - only the FunctionExprMixin annotates errors
> Fix 5758 3.18 functions missing

- CHANGELOG.md
- sqldelight-gradle-plugin/src/main/kotlin/app/cash/sqldelight/gradle/SqlDelightDatabase.kt
- sqldelight-gradle-plugin/src/test/integration-sqlite-json-version-catalogs/build.gradle
- sqldelight-gradle-plugin/src/test/integration-sqlite-json-version-catalogs/settings.gradle
- sqldelight-gradle-plugin/src/test/integration-sqlite-json-version-catalogs/src/main/sqldelight/app/cash/sqldelight/integration/JsonTable.sq
- sqldelight-gradle-plugin/src/test/integration-sqlite-json-version-catalogs/src/test/java/app/cash/sqldelight/integration/IntegrationTests.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/integrations/IntegrationTest.kt
This PR changes the logic for adding a dependency on a module, this has the advantage that it can accept version catalogs, wich the current logic can't
the dialect function already calls the same function
Fixes #5282
> Use DependencyHandler for modules

- CHANGELOG.md
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/CommentOnMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/comment-on/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql-migrations/src/main/sqldelight/migrations/app/cash/sqldelight/postgresql/integration/V1__Product.sqm
- sqldelight-gradle-plugin/src/test/integration-postgresql-migrations/src/main/sqldelight/migrations/app/cash/sqldelight/postgresql/integration/V2__Product_alter.sqm
- sqldelight-gradle-plugin/src/test/integration-postgresql-migrations/src/main/sqldelight/migrations/app/cash/sqldelight/postgresql/integration/V3__Product_alter.sqm
Fixes #5806 
* Adds limited support for PostgreSql https://www.postgresql.org/docs/current/sql-comment.html - tables, views and columns only
* This is due to SqlDelight dialects currently not having access to internal sql-psi schema like indexes  
* Adds fixture test
* Adds integration migration test
Note: See also https://github.com/sqldelight/sqldelight/issues/4998
---
> Add limited support for PostgreSql Comment On statement

- CHANGELOG.md
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/GroupQueries.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/PlayerQueries.kt
- sqldelight-compiler/integration-tests/src/test/kotlin/com/example/TeamQueries.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/SelectQueryGenerator.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/Constants.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/QueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/async/AsyncQueriesTypeTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/ExpressionTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/InterfaceGeneration.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/JavadocTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/PgInsertReturningTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/SelectQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncQueryFunctionTest.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/test/FunSpecExtensions.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table-add-constraint/output/com/example/DataQueries.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/alter-table/output/com/example/DataQueries.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/create-or-replace-view/output/com/example/DataQueries.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/create-or-replace-view/output/com/example/queries/DataQueries.kt
- sqldelight-compiler/src/test/migration-interface-fixtures/varying-query-migration-packages/output/com/example/queries/DataQueries.kt
- sqldelight-gradle-plugin/src/test/kotlin/app/cash/sqldelight/WithCommonConfiguration.kt
**No functional difference**
Made a change to the generated code from `SelectQueryGenerator` to reduce generated LoC and complexity, especially for big queries with lots of columns.
Previously we'd get two generated queries, like:
```kotlin
public fun <T : Any> getData(id: Long, mapper: (id: Long, parent_id: Long?) -> T): Query<T> = GetDataQuery(id) { cursor ->
mapper(
cursor.getLong(0)!!,
cursor.getLong(1)
)
}
public fun getData(id: Long): Query<GetData> = getData(id) { id_, parent_id ->
GetData(
id_,
parent_id
)
}
```
The first one stays as-is, but now the latter one is replaced with:
```kotlin
public fun getData(id: Long): Query<GetData> = getData(id, ::GetData)
```
Or if there are no query parameters:
```kotlin
public fun getData(): Query<GetData> = getData(::GetData)
```
Most diffs …
> Simplify generated code by using constructor references

- CHANGELOG.md
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/compiler/ExecuteQueryGenerator.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/queries/async/AsyncSelectQueryTypeTest.kt
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/main/sqldelight/app/cash/sqldelight/mysql/integration/async/Dog.sq
- sqldelight-gradle-plugin/src/test/integration-mysql-async/src/test/kotlin/app/cash/sqldelight/mysql/integration/async/MySqlTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql-async/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/async/Dog.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql-async/src/test/kotlin/app/cash/sqldelight/postgresql/integration/async/PostgreSqlTest.kt
Fixes #5753 
Fixed -  Return `QueryResult.AsyncValue<Long>` for async transaction blocks
Fixed - `grouped statements same parameter` Test fixture code isn't valid because return type was `kotlin.Long`
Added - tests that actually compile generated code as there are no async Sqlite driver runtime tests
(e.g adding MySql, PostgreSql async integration tests will catch any compilation problems)
Note:
The issue occurred since executable statements in a transaction block were changed to return the underlying driver result value - returning a count value for executable statements in a transaction block may not be that useful as only the last statement value is used.
The work-around was If the last statement was a `SELECT` then the compiler produced an ExecutableResult avoiding the issue.
---
> Fix async result type for transaction blocks returning Long

- CHANGELOG.md
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/is_json_expressions/Test.s
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Json.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
SqlJson functions for PostgreSql 16 
https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-MISC
```
expression IS [ NOT ] JSON [ { VALUE | SCALAR | ARRAY | OBJECT } ] [ { WITH | WITHOUT } UNIQUE [ KEYS ] ]
```
```
pg_input_is_valid ( string text, type text ) → boolean
```
Test if expression can be parsed as JSON, possibly of a specified type. If SCALAR or ARRAY or OBJECT is specified, the test is whether or not the JSON is of that particular type. If WITH UNIQUE KEYS is specified, then any object in the expression is also tested to see if it has duplicate keys.
Useful for check constraints to validate json 
```sql
CREATE TABLE TestJsonCheck(
js_1 JSON CHECK (js_1 -> 'scores' IS NOT NULL AND js_1 -> 'scores' IS JSON ARRAY),
js_2 JSON CHECK ((js_2 -> 'scores'::TEXT) …
```
> Add PostgreSql 16 SqlJson expression

- sqldelight-compiler/environment/build.gradle
- sqlite-migrations/environment/build.gradle
- Declares `duplicatesStrategy` and `failOnDuplicateEntries` as I suggested in the Shadow 9 changelog.
- It is possible to pass version catalog accessors for `dependency` in Shadow 9.
```
OLD: migrations-environment-2.2.0-SNAPSHOT.jar.old
NEW: migrations-environment-2.2.0-SNAPSHOT.jar.new
JAR   │ old      │ new      │ diff
───────┼──────────┼──────────┼──────
class │  2.2 MiB │  2.2 MiB │  0 B
other │ 24.5 MiB │ 24.5 MiB │  0 B
───────┼──────────┼──────────┼──────
total │ 26.7 MiB │ 26.7 MiB │  0 B
CLASSES │ old  │ new  │ diff
─────────┼──────┼──────┼───────────
classes │  742 │  742 │ 0 (+0 -0)
methods │ 7641 │ 7641 │ 0 (+0 -0)
fields │ 2343 │ 2343 │ 0 (+0 -0)
```
---
> Minor tweaks about ShadowJar configurations

- CHANGELOG.md
- dialects/mysql/src/main/kotlin/app/cash/sqldelight/dialects/mysql/ide/MySqlConnectionDialog.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/ide/PostgresConnectionDialog.kt
- dialects/sqlite-3-18/src/main/kotlin/app/cash/sqldelight/dialects/sqlite_3_18/SelectConnectionTypeDialog.kt
- sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/run/ArgumentsInputDialogImpl.kt
fixes #5899 
The Plugin UI Dialog components can't initialise in 2025.2
Long deprecated UI components have been finally removed from recent JetBrains IntelliJ Plugins and cause exceptions to be reported as some methods cannot be referenced.
For example: `package com.intellij.ui.layout`
``` kotlin
@ApiStatus.ScheduledForRemoval
@Deprecated("Use Kotlin UI DSL Version 2")
fun textField(getter: () -> String, setter: (String) -> Unit, columns: Int? = null) = textField(PropertyBinding(getter, setter), columns)
```
Need to migrate UI components to supported DSL - https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html#2025
Migration to JetBrains UI DSL v2 https://plugins.jetbrains.com/docs/intellij/kotlin-ui-dsl-version-2.html#migration-from-version-1
The code changes are …
> Fix SqlDelight Plugin UI components

- .github/workflows/prepare_mkdocs.sh
While looking into updating Python  https://github.com/sqldelight/sqldelight/pull/5950
I can see the current `Prep Mkdocs` job is broken and printing sed command errors.
The job still completes successfully as the `sed` command is just unable to perform a replacement  
Error `sed: -e expression #1, char 66: unknown option to 's'` is repeated for every html file e.g
https://github.com/sqldelight/sqldelight/actions/runs/18037360978/job/51327355255  see `Prep Mkdocs` job
This is caused because the sed escape character '/' needs to be different from the replacement character '/'
Fix: use another character for sed replacement command e.g s@/@/@g
Also means the forward slash '\/' doesn't need to be escaped now - so this now `/`
The purpose of the sed command is to append a favicon before the …
> Fix prepare_mkdocs.sh error in sed command

- CHANGELOG.md
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlType.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/PostgreSqlTypeResolver.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/PostgreSql.bnf
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/CreateEnumTypeMixin.kt
- dialects/postgresql/src/main/kotlin/app/cash/sqldelight/dialects/postgresql/grammar/mixins/DropEnumTypeMixin.kt
- dialects/postgresql/src/testFixtures/resources/fixtures_postgresql/create-enum/Sample.s
- sqldelight-compiler/dialect/src/main/kotlin/app/cash/sqldelight/dialect/api/PreCreateTableInitialization.kt
- sqldelight-compiler/src/main/kotlin/app/cash/sqldelight/core/lang/util/TreeUtil.kt
- sqldelight-compiler/src/test/kotlin/app/cash/sqldelight/core/util/TreeUtilTest.kt
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/main/sqldelight/app/cash/sqldelight/postgresql/integration/Enums.sq
- sqldelight-gradle-plugin/src/test/integration-postgresql/src/test/kotlin/app/cash/sqldelight/postgresql/integration/PostgreSqlTest.kt
fixes #4339
🔢 🐘 Support for PostgreSql Enum types  - https://wiki.postgresql.org/wiki/Enum
These are mapped as `String` type,  *there is no compiler support yet for generating as Kotlin Enum classes*. see https://github.com/sqldelight/sqldelight/issues/3773. This would be tricky as the Enum Type can be changed with `ALTER TYPE` - so currently type safety outside the database is lost.
*Recommend SqlDelight enum type adapters used instead* as these are type safe, there maybe some performance reasons for using native enums or using them as ranges.
`CREATE ENUM` must be executed before `CREATE TABLE` in create schema - there is a change to `TreeUtil` to add a marker interface `PreCreateTableInitialization` to process these statements before `createTableStmt`. Statements in migration files are …
> Add PostgreSql CREATE ENUM
